### PR TITLE
update da.json to v2.18.0

### PR DESCRIPTION
**Pull request by The-Exterminator**
```
{
	"LOADING": "Indlæser &hellip;",

	"TODAY": "I dag",
	"TOMORROW": "I morgen",
	"DAYAFTERTOMORROW": "I overmorgen",
	"RUNNING": "Slutter om",
	"EMPTY": "Ingen kommende begivenheder.",
	"WEEK": "Uge {weekNumber}",

	"N": "N",
	"NNE": "NNØ",
	"NE": "NØ",
	"ENE": "ØNØ",
	"E": "Ø",
	"ESE": "ØSØ",
	"SE": "SØ",
	"SSE": "SSØ",
	"S": "S",
	"SSW": "SSV",
	"SW": "SV",
	"WSW": "VSV",
	"W": "V",
	"WNW": "VNV",
	"NW": "NV",
	"NNW": "NNV",

	"FEELS": "Føles som {DEGREE}",
	"PRECIP": "PoP",

	"MODULE_CONFIG_CHANGED": "Konfigurationsmulighederne for {MODULE_NAME} modulet er ændret.\nSe venligst dokumentationen.",
	"MODULE_CONFIG_ERROR": "Fejl i {MODULE_NAME} modulet. {ERROR}",
	"MODULE_ERROR_MALFORMED_URL": "Forkert url.",
	"MODULE_ERROR_NO_CONNECTION": "Ingen internetforbindelse.",
	"MODULE_ERROR_UNAUTHORIZED": "Godkendelse mislykkedes.",
	"MODULE_ERROR_UNSPECIFIED": "Tjek logfiler for flere detaljer.",

	"NEWSFEED_NO_ITEMS": "Ingen nyheder i øjeblikket.",

	"UPDATE_NOTIFICATION": "MagicMirror² opdatering tilgængelig.",
	"UPDATE_NOTIFICATION_MODULE": "Opdatering tilgængelig for {MODULE_NAME} modulet.",
	"UPDATE_INFO_SINGLE": "Den nuværende installation er {COMMIT_COUNT} commit bagud på {BRANCH_NAME} branch'en.",
	"UPDATE_INFO_MULTIPLE": "Den nuværende installation er {COMMIT_COUNT} commits bagud på {BRANCH_NAME} branch'en."
}
```

### CODE REVIEW

**Comment by rejas** [comment]
You got to base the PR against develop (you can edit that, no need to close an dreopen the PR)

**Comment by The-Exterminator** [comment]
@rejas what is wrong. ???

**Comment by rejas** [comment]
Take a look under the "Files changed" tab, there are way to many files changed. This is probably happening because you didnt work on the develop branch or didnt base your PR against the develop branch.

The expected workflow is to create a new branch for your changes from the current develop branch. And when creating the PR you have to tell github that it should be applied to the develop branch (not the master branch)

**Comment by The-Exterminator** [comment]
@rejas I press on the "develop" options

**Comment by KristjanESPERANTO** [comment]
This should work:

1. Click at the edit button here on this site:
Ekrankopio de 2022-01-31 22-41-59

2. Click drop down button "base:master" and the select "develop":
Ekrankopio de 2022-01-31 22-41-26

**Comment by The-Exterminator** [comment]
@KristjanESPERANTO 
I van not chance it "you write to me"
2. Click drop down button "base:master" and the select "develop":

**Comment by KristjanESPERANTO** [comment]
@The-Exterminator To cut this long story short, would it be okay if I created a new PR to bring in your changes?

**Comment by KristjanESPERANTO** [comment]
I created the new PR :slightly_smiling_face:  You can close this one.

**Comment by The-Exterminator** [comment]
@KristjanESPERANTO thanks for the help 👍

**Pull request closed without merging**
