### PR TITLE
Convert HTML entities, codes and tag

### PR DESCRIPTION
**Pull request by bugsounet**
related to PR [#3092](https://github.com/MichMich/MagicMirror/pull/3092)

maybe best way is using `html-to-text` library

sample: `&quotHello World&quot` will be transformed to `"Hello World"`

### CODE REVIEW

**Comment by rejas** [comment]
Good idea, any idea why the tests are failing there for node 20? Can you check that out?

**Comment by bugsounet** [comment]
I will take a look this evening

I have not try any test suite in  local

**Comment by bugsounet** [comment]
@rejas:

```
 PASS   e2e  tests/e2e/modules_position_spec.js
  Position of modules
    ✓ should show text in top_bar (205 ms)
    ✓ should show text in top_left (202 ms)
    ✓ should show text in top_center (202 ms)
    ✓ should show text in top_right (203 ms)
    ✓ should show text in upper_third (201 ms)
    ✓ should show text in middle_center (202 ms)
    ✓ should show text in lower_third (203 ms)
    ✓ should show text in bottom_left (202 ms)
    ✓ should show text in bottom_center (202 ms)
    ✓ should show text in bottom_right (204 ms)
    ✓ should show text in bottom_bar (203 ms)
    ✓ should show text in fullscreen_above (204 ms)
    ✓ should show text in fullscreen_below (200 ms)
```

```
Test Suites: 39 passed, 39 total
Tests:       565 passed, 565 total
Snapshots:   9 passed, 9 total
Time:        153.811 s
Ran all test suites in 3 projects.
Force exiting Jest: Have you considered using `--detectOpenHandles` to detect async operations that kept running after all tests finished?
bugsounet@Kubuntu:~/MagicMirror-dev$ node -v
v20.5.1
```

it's works in local with node v20.5.1
another `test suite` whim?

**Comment by khassel** [comment]
did re-run the tests and it was successful.

@rejas we have still problems with failing e2e tests but this is unrelated to this PR.

**Review by rejas — APPROVED** [review]

**Pull request merged**
