### PR TITLE
Refactor clock module 

### PR DESCRIPTION
**Pull request by rejas**
Lots of code cleanup resulting in less lines :-)

- Added showTime parameter to clock module for enabling/disabling time display in analog clock
- analogShowDate is obsolete (should we deprecate it?) since showTime and analogPlacement does the job too
- Uses css grid for displaying the clocks
- Also fixes https://github.com/MichMich/MagicMirror/issues/2462

Normally I would have refactored more and removed a lot of parameters that could be replaced with more general ones but maybe thats for another day? Whats you opinions @khassel @MichMich ?

### CODE REVIEW

**Comment by khassel** [comment]
LGTM.

> Normally I would have refactored more and removed a lot of parameters that could be replaced with more general ones but maybe thats for another day? Whats you opinions @khassel @MichMich ?

The problem is removing such paramters will generate support because the clock is not worling anymore as expected with the next release. On the other side the project must move on and get rid of old stuff. May it is sufficient to log a warning if the old parameter is used with a short message how to solve it (may with a link).

Another idea is to replace such old parameters automatically on start up with the new ones in the `config.js` (including saving the old config).

**Comment by MichMich** [comment]
I think showing a warning (and alert on the UI?) is the best option. It is easy to implement and helps the user to understand things change.

**Comment by rejas** [comment]
> Another idea is to replace such old parameters automatically on start up with the new ones in the `config.js` (including saving the old config).

That would be optimal but writing logic for replacing parameters with other would be very hard if it is more than just a simple "replace nameY with nameX"

Adding a UI warning and in the console would be a good start. So maybe have it deprecated for one or two releases and print a warning and then remove it after that?

**Comment by rejas** [comment]
But of course any of that stuff would happen in another PR ;-)

**Comment by MichMich** [comment]
Maybe the easiest way is to create a list of json paths that are deprecated and if one of those paths occur in the config it shows the alert to check the log, and fix the config. 

The alert/messages can be displayed as long as people have it in their config. I don't think it is a good idea to only do this for two releases since a lot of people only update one a year. 

Automatically change the config requires A LOT of code, generates a big risk of messing things up, and doesn't teach the user a thing. I don't think we should take this route, IMHO.

**Comment by MichMich** [comment]
The json paths can be supplied by a method of the module. This way all modules can hook into this feature. A nice additional feature for the core.

**Comment by khassel** [comment]
> Automatically change the config requires A LOT of code, generates a big risk of messing things up, and doesn't teach the user a thing. I don't think we should take this route, IMHO.

I'm aware that the automatically change of the config is a bigger thing and I won't code it ;)

So the json paths idea is my favorite at the moment.

**Comment by rejas** [comment]
> Maybe the easiest way is to create a list of json paths that are deprecated and if one of those paths occur in the config it shows the alert to check the log, and fix the config

Sounds good, will you create an enchancment-ticket for this? So people with time can take a stab at it ;-)

> The alert/messages can be displayed as long as people have it in their config. I don't think it is a good idea to only do this for two releases since a lot of people only update one a year.

Well, one could always declare the spring release as the one that cleans stuff up and removes deprecated stuff ;-)
 
> Automatically change the config requires A LOT of code, generates a big risk of messing things up, and doesn't teach the user a thing. I don't think we should take this route, IMHO.

Agreed.

**Pull request merged**
