### PR TITLE
Improves backwards compatibility for safari

### LINKED ISSUE #1897: 'Undefined' module header on safari < 11
Hey guys,
So i use MM as server only set up in a docker container and an old ipad as a screen. After last couple updates i noticed that my setup is all messed up with `UNDEFINED` headers above every module. So i check it on my laptop (chrome, w10) and everything is fine. Then i checked it on an iPhone (current ios) and also everything is fine. Thought this might be browser support issue so i tried browserstack.com for legacy safari versions and sure enough:
Safari 11.1:
image

Safari 10.1:
image

Safari 9.1:
image

I don't know if thats really a large issue for the whole community or how much we want to support older browsers but sure enough it worked fine circa december 2019. Thanks!

### PR DESCRIPTION
**Pull request by sejka**
fixes #1897

### CODE REVIEW

**Comment by sejka** [comment]
i have no idea why that build is failing :/

**Comment by sejka** [comment]
is it that tests are flaky or should i investigate more? @MichMich

**Comment by MichMich** [comment]
It is flaky indeed ... but somehow your PR is the only on consistently failing. Could you try rebasing your PR?

**Comment by sejka** [comment]
no luck, maybe there's something to be found after all 🤔 ? I'll look into it on Monday

**Comment by khassel** [comment]
your changes break the newsfeed module, it is not visible, no error messages ...

**Comment by sejka** [comment]
that's right! no idea why though. probably also doing some styling via `style` attributes 🤷‍♂ . Switched to using `classList.add` and `.hidden` class which should've been done anyway. Waiting for TravisCI to come back from maintenance.

**Comment by sejka** [comment]
@MichMich ready to merge

**Comment by MichMich** [comment]
Thanks. The reason why I haven’t merged yet is because I want to check out the code behind the header. If we aren’t going to display the header. Why add it to the dom? Adding a hidden class feels like a bandage on a issue that should be solved else where. There might be a good reason to do it this way, but I want to confirm before I merge this. 

Thoughts?

**Comment by aghster** [comment]
I think this has been answered in the original issue https://github.com/MichMich/MagicMirror/issues/1897#issuecomment-577555074

**Comment by aghster** [comment]
As it [seems](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style), the problem with the style property is that it is considered read-only. Correctly, one should not write directly to style, but set individual sub-properties of style. This means: 

`element.style = "display: none;";`

should become

`element.style.display = "none";`

Older versions of Safari apparently are more strict in this regard.

**Comment by sejka** [comment]
I think @MichMich is more reffering to wheather headers should be in the DOM at all. I understand @tbouron intent with doing so. I'm just here to help people reuse older devices instead of throwing them away. Hopefully there is a way of having everyone happy.

**Comment by aghster** [comment]
In fully understand that @MichMich is checking whether unnecessary headers can simply not be created instead of being created and then hidden. With my above reference to @tbouron's  comment I only intended to point @MichMich to why the current approach apparently had been implemented.

@sejka, I totally share your intention to improve compatibility with older browsers. I myself want to use MagicMirror in serveronly mode and use an old 3rd generation iPad running on iOS 9 as client. I tried to find out why some code does not work in Safari 9. This is what I have found out so far. 

- As mentioned above, Safari 9 is strict with HTMLElement.style being read-only. Therefore one should replace `element.style = "display: none;";` with `element.style.display = "none";`.
- Safari 9 does not understand ES6 [arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions). They should therefore be replaced by ordinary functions.
- Safari 9 does not understand ES6 [let statements](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let). They should be replaced by `var` statements.
- Safari 9 does not understand ES6 concise method definitions as object properties. A definition such as `obj = { foo(a, b) { … } };` should be replaced by `obj = { foo: function(a, b) { … } };`.
- Safari 9 does not understand ES6 [default parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters). I suggest replacing `function(param = default) { … }` by `function(param) { param = param || default; … }`.
- Safari 9 does not understand [class declarations](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/class). They should be replaced by ordinary [class expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/class).

Probably this list is incomplete. But in my [fork (branch `improve-compatibilty-with-old-browsers`)](https://github.com/aghster/MagicMirror/tree/improve-compatibilty-with-old-browsers) of MagicMirror applying these replacements was enough to obtain a serveronly version running without apparent problems in Safari on my iPad running iOS 9. 

I do not want to compete with your PR. I just wanted to share my results.

**Comment by buxxi** [comment]
Wouldn't it be much better to use a transpiler (like babeljs or something) for compability in older browsers than forcing the code to be stuck in the past (IE6 flashbacks...)?

**Comment by sejka** [comment]
great work @aghster!
I think in most cases we'd like to use newest features of JS and not make devs think twice before using a feature. Honestly I didn't think there's so many changes - that's why I've only changed that one thing.

I think we have two separate conversations going on - to have headers in the DOM despite them being empty and general backwards compatibility for browsers.

When it comes to second one i totally support @buxxi approach with babel.

**Comment by sejka** [comment]
looked into babel a little bit - i think we would need to ditch class.js for es6 classes though. Also found this issue: https://github.com/MichMich/MagicMirror/issues/694 which suggests that @MichMich isn't interested in complicating codebase that much. Maybe something changed though.

**Comment by buxxi** [comment]
Ditching custom class-creation for es6 classes doesn't sound like complicating it :smile: 

Guessing babel would be a part of the gruntfile if it would be used. Could also be part of a specific Dockerimage to avoid having the core of MagicMirror have to support older browsers (and require a build-step) since the main target is electron.

But there really should be something in the Contributing Guidelines about what browsers it needs to work in or what features of JS can/can't be used.

**Comment by MichMich** [comment]
Indeed. We will not use any pre-compilers. (see https://docs.magicmirror.builders/getting-started/manifesto.html) Sorry :)

**Comment by sejka** [comment]
I understand. What's your recommendation for users recycling their old devices for that use case? Should we create MagicMirrorLegacyDevices fork? Are we adding additional build step for legacy devices users? Maybe another docker image since most of older devices users are running host-client setup anyways?

**Comment by MichMich** [comment]
You can always run an older version of MagicMirror.

**Comment by PoojaAmin29** [comment]
Where will I get older version of magic mirror sorry for this silly
question but I am new to this

**Comment by MichMich** [comment]
Closing this for now because I don't see where we go with this. Feel free to reopen.

**Pull request closed without merging**
