### PR TITLE
Add Scrutinizer to the project

### PR DESCRIPTION
**Pull request by nhubbard**
This is an awesome code quality tool, but @MichMich will need to do some work after this, mainly:

* Enabling it on the main repository **after merging**
* Emailing [support@scrutinizer-ci.com](mailto:support@scrutinizer-ci.com) to enable the security analysis feature

I think this has a future... what are your thoughts?

### CODE REVIEW

**Comment by nhubbard** [comment]
Anyone? @MichMich?

**Comment by MichMich** [comment]
Hi @nhubbard,

Sorry for the slow response. I've been a bit busy the past few weeks. I agree that the project might benefit from scrutinizer. But I think this is something for version 2. (On which I will be working the coming 3 weeks.)

Version 2 will focus on a modular system which will allow anyone to create modules for the magic mirror.

**Comment by nhubbard** [comment]
Got it @MichMich. So... this shall be marked as idle.

**Comment by MichMich** [comment]
Hi @nhubbard. Is it ok if I close this issue so that we might reopen it for v2?

**Pull request closed without merging**
