### PR TITLE
Hide cursor and updated electron params

### PR DESCRIPTION
**Pull request by paviro**

### CODE REVIEW

**Comment by CFenner** [comment]
With the css set, can I ommit the installation of 'unclutter' on raspbian?

**Comment by paviro** [comment]
Yes, exactly my idea :)

**Comment by djsunrise19** [comment]
Which of these tools are necessary now: http://michaelteeuw.nl/post/83188136918/magic-mirror-part-v-installing-the-raspberry-pi

As I can see I need:
- screen rotation and some things in /boot/config.txt

But these installations are not necessary anymore:
- php, apache, unclutter, chromium / kioskmode

Am I right? Do I need to put the node script in my init. for reboot? Or does it starts automatically?

**Comment by paviro** [comment]
Jup haven't tested it yet but hopefully the only thing you need is that and node start in `/etc/xdg/lxsession/LXDE-pi/autostart`.

**Comment by MichMich** [comment]
I'll merge this request after I solve a newsfeed bug.

**Comment by CFenner** [comment]
A browser is thou still neded right? At the moment I use midori as chromium does not work anymore.

**Comment by paviro** [comment]
No its not!

**Pull request merged**
