### PR TITLE
Electron13

### PR DESCRIPTION
**Pull request by khassel**
Managed to get the e2e tests running with electron v13 and spectron v15.

Tested new electron version on pi3 and ubuntu desktop.

Related to #2408.

### CODE REVIEW

**Comment by MichMich** [comment]
Great work!

I notice that almost all changes are the same electron options object in all different tests. Maybe it's worth it to extract that to a separate file so it can be reused?

**Comment by khassel** [comment]
> Maybe it's worth it to extract that to a separate file so it can be reused?

You mean something like

```js
	defaultElectronOptions: {
		webPreferences: {
			nodeIntegration: true,
			enableRemoteModule: true,
			contextIsolation: false
		}
```

in a seperate file and then 

```js
	electronOptions: defaultElectronOptions
```

in every test config?

**Comment by MichMich** [comment]
Jean, or even better. A default test config that can be extended. 
   
    let config = testConfig({foo: bar})

The testConfig method will return the default config (including the electronOptions) and it will extend/overwrite with whatever you add as an argument. 

Of course this can be a separate PR. But it might save some work in the future and makes PR's like these much cleaner.

**Comment by khassel** [comment]
o.k., will try this in a new PR.

**Review by rejas — APPROVED** [review]
LGTM!

**Pull request merged**
