### PR TITLE
Added general advice

### PR DESCRIPTION
**Pull request by E3V3A**
> Please send your pull requests the develop branch.
> Don't forget to add the change to CHANGELOG.md.

**Note**: Sometimes the development moves very fast. It is highly
recommended that you update your branch of `develop` before creating a
pull request to send us your changes. This makes everyone's lives
easier (including yours) and helps us out on the development team.
Thanks!

* Does the pull request solve a **related** issue?
* If so, can you reference the issue?
* What does the pull request accomplish? Use a list if needed.
* If it includes major visual changes please add screenshots.

### CODE REVIEW

**Comment by MichMich** [comment]
Please send all PR’s to de develop branch. Thanks.

**Comment by E3V3A** [comment]
@MichMich 
> Please send all PR’s to de develop branch. Thanks.

Oops, I missed that. Sorry. 
Just updated README as well. 

Thanks for your kind support! :) 🥇

**Comment by E3V3A** [comment]
Dammit! I thought this was the issue! 
I closed it by mistake.

**Comment by roramirez** [comment]
Good point in module readme file :D

**Pull request merged**
