### PR TITLE
Jared

### PR DESCRIPTION
**Pull request by cs499Mirror**
> Please send your pull requests the develop branch.
> Don't forget to add the change to CHANGELOG.md.

* Does the pull request solve a **related** issue?
* If so, can you reference the issue?
* What does the pull request accomplish? Use a list if needed.
* If it includes major visual changes please add screenshots.

### CODE REVIEW

**Comment by fewieden** [comment]
First of all pr have to go into develop branch and second what is this about, it makes no sense for me at all

**Comment by MichMich** [comment]
This doesn't make sense.

**Comment by wcdanh2** [comment]
It looks like It should have been a commit to a fork instead of a PR to the main project.

**Comment by cs499Mirror** [comment]
Sorry, I'm still learning git and Github...this PR was submitted in mistake. Indeed, I meant this to be a push to my fork. Sorry for the confusion.

**Comment by qistoph** [comment]
Why not add it to your config instead of modifying the defaults of the module?

**Pull request closed without merging**
