### PR TITLE
Added electron wrapper

### PR DESCRIPTION
**Pull request by paviro**
I know it is not the focus right now so feel free to ignore this pull request anyway I think it would be a nice addition to v2.

### CODE REVIEW

**Comment by MichMich** [comment]
Hi @paviro, could you elaborate a little bit on the added value of the electron wrapper? I have no experience yet with this lib.

Thanks!

**Comment by paviro** [comment]
I don't have much yet either however the biggest advantage I see is that there no longer is a need to install a webserver or browser which makes it easier for people who don't have much experience with shells. They only have to execute two commands to get the interface up and running. I guess in the future it should also make it possible to directly run node.js helper scripts this way but no guarantee on that, I just started reading some of their documentations.

**Comment by MichMich** [comment]
It looks promising. But as far as I can see, Raspberry Pi is not yet supported. Which is the main platform we develop for.

**Comment by paviro** [comment]
Well this [mirror](http://docs.smart-mirror.io/docs/supported_hardware.html) uses it and the Pi is under supported platforms, so it seems to work somehow.

**Comment by paviro** [comment]
I added another commit, this will now automatically start any helper script called "node_helper.js" inside a module folder. The helper can then host a socket, it works for example for my call monitor any comments are welcome!

**Comment by paviro** [comment]
If you are interested [here](https://github.com/paviro/MMM-FRITZ-Box-Callmonitor) an example module that uses this pull request. I tested it on a Raspberry Pi works as expected!

**Pull request merged**
