### PR TITLE
Fix updatenotification

### PR DESCRIPTION
**Pull request by bugsounet**
Sometime, `pm2 jlist` don't send an json reponse
Catch error if happen

### CODE REVIEW

**Comment by bugsounet** [comment]
Note:

For me, best way is using `pm2` library directly because with command line sometine we can have some pm2 warn (update warn for example) and it break response
but there is some `moderate severity vulnerabilities` with this library

@rejas: So, what can I do ?

**Comment by rejas** [comment]
@bugsounet do you have a link to that vulnarbility?

**Comment by bugsounet** [comment]
seams to be last current `axios` vulnerabilities

```sh
# npm audit report

axios  0.8.1 - 1.5.1
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
fix available via `npm audit fix --force`
Will install pm2@2.10.4, which is a breaking change
node_modules/axios
  @pm2/js-api  *
  Depends on vulnerable versions of axios
  node_modules/@pm2/js-api
    pm2  >=3.0.0
    Depends on vulnerable versions of @pm2/js-api
    node_modules/pm2

3 moderate severity vulnerabilities
```

**Review by rejas — APPROVED** [review]

**Comment by bugsounet** [comment]
I try to code (recode) it why `pm2` library in draft and we see ?

**Pull request merged**
