### PR TITLE
Update de.json in calendar

### PR DESCRIPTION
**Pull request by djsunrise19**
"Endet in" isn't correct. "Noch" fits better in this case.

### CODE REVIEW

**Comment by MichMich** [comment]
Worked! Thanks!

**Comment by djsunrise19** [comment]
Finally... ;).

**Comment by MichMich** [comment]
Did you also find old documentation? Or was that already updated?

**Comment by djsunrise19** [comment]
I'll do that next. We can delete a few points in the calendar wiki doc.

**Comment by MichMich** [comment]
Thanks for your contribution! 👍

**Pull request merged**
