### PR TITLE
Fix typos in the module dev docs

### PR DESCRIPTION
**Pull request by dmcinnes**
Found a few typos in the module dev docs -- great docs BTW!

### CODE REVIEW

**Comment by MichMich** [comment]
Somehow this PR fails the Travis checks. Any idea why?

**Comment by dmcinnes** [comment]
That is odd, not coming from my change:
```
/home/travis/build/MichMich/MagicMirror/js/class.js
  44:9  error  Expected indentation of 0 tabs but found 8 spaces  indent
```
Does it need a rebase?

**Comment by MichMich** [comment]
Yes its fixed. Please rebase.

**Comment by dmcinnes** [comment]
Rebased! All green now.

**Comment by MichMich** [comment]
Thanks!

**Pull request merged**
