### PR TITLE
Remove yarn-or-npm as it breaks production builds

### PR DESCRIPTION
**Pull request by bastilimbach**
> To be honest I don't know why this change did make it into the master branch in the first place.

Because we, too, are human! ;)

Anyway, I'm okay with changing it back, but I won't be merging it into the master branch yet. If you update the changelog to reflect the changes in 2.4.0, I'll merge the PR.

Thanks!

### CODE REVIEW

**Comment by bastilimbach** [comment]
@MichMich Sorry, this shouldn't sound cocky. I genuinely wasn't sure why this change was made because there was no conversation in the PR. I should have phrased that differently.

Was it intentional that you edited my PR description instead of commenting? This could be a little confusing to someone looking at this PR in the future.

I'll update the changelog accordingly.

**Comment by MichMich** [comment]
No worries! :)

Reson I changed your PR is to switch it to the `develop` branch in stead of the `master`. No other changes were made.

**Comment by bastilimbach** [comment]
Thank you! 👍

**Comment by MichMich** [comment]
Thanks for your contribution.

**Pull request merged**
