### PR TITLE
Replace HTML tables with Markdown tables

### PR DESCRIPTION
**Pull request by tosti007**
Replace the HTML tables with Markdown tables for all the README.md files in all the default modules

### CODE REVIEW

**Comment by MichMich** [comment]
Awesome. Could you add an updated changelog file?

**Comment by tosti007** [comment]
I didnt really change anything, only changed html into markdown, should i add that?

**Comment by tosti007** [comment]
A sidenote: For the weather modules it wasn't possible to put the whole default icon table into the list, so I added it underneath the table instead

**Comment by MichMich** [comment]
Yeah, than peace can see all the effort that is put in ... ;)

**Comment by tosti007** [comment]
Fair enough, but I just found out that I didn't use the developer branch as main branch. Any idea how I can get the new changelog file without messing up this whole pull request? (yes i am a github rookie)

**Comment by tosti007** [comment]
If I just edit a random line in the changelog of the master branch it won't go well with the edits of the developer branch

**Pull request closed without merging**
