### PR TITLE
Fixed typo in node_helper and added module to README

### PR DESCRIPTION
**Pull request by paviro**

### CODE REVIEW

**Comment by MichMich** [comment]
Very impressed by the speed in which you were able to update according to my changed! :)

Awesome example of using modules.

**Comment by paviro** [comment]
Thank you! Means a lot to me :)
I also started porting my face recognition module but that will still need a bit of work.

**Comment by MichMich** [comment]
Cool! Let me know how it goes. I still have a feature on my to do list where you can hide and show certain modules. This way your recognizer can show/hide agenda's depending on the person who is in front of the mirror.

**Comment by paviro** [comment]
Looking forward to implement it! It's a lot more fun now to write modules than it was before!

**Pull request merged**
