### PR TITLE
Use Log.debug where applicable

### PR DESCRIPTION
**Pull request by rejas**

### CODE REVIEW

**Comment by sdetweil** [comment]
we don't need to generate all that info all the time
I would not approve this change

**Comment by rejas** [comment]
So if we dont need the info then we can remove it from the code?

**Comment by sdetweil** [comment]
we don't need it generated ALL the time. but on demand if a user has a
problem. we don't need to waste the cpu cycles.

**Comment by rejas** [comment]
If on demand is what you want then why not use the Log.debug? It is easily turned on via the config.js and it doesnt take much more cpu then an if clause ...

**Comment by sdetweil** [comment]
ok, I have never seen any instruction on using config.js for setting log levels

**Comment by rejas** [comment]
Submitted that a while ago: https://github.com/MichMich/MagicMirror/pull/2017
Is there a place to document that better?

**Comment by sdetweil** [comment]
well I think it would have to go into the pages for the config.js doc

**Comment by MichMich** [comment]
I agree with sam that we should add information about this in the docs.

**Pull request merged**
