### PR TITLE
Update error handling in newsfeed and calendar modules

### PR DESCRIPTION
**Pull request by rejas**
Those modules didnt bubble all errors up to the MM so that for example the calendar only showed "No upcoming events" leaving the user clueless that for example the authentication failed or that the url were wrong.

Question is though: Should the MM show the error message like in the attached picture or something more like 
"An error occured, please check the logs" ? Whats your opinion @MichMich ?

Bildschirmfoto 2021-04-24 um 09 02 15
Bildschirmfoto 2021-04-24 um 08 51 44

### CODE REVIEW

**Comment by MichMich** [comment]
Uhohh... Node v16 fun begins. 🙈

**Comment by rejas** [comment]
Time to install v16 on my machine :-)
What are your thoughts on the PR @MichMich ? More error messages or less on the UI?

**Comment by MichMich** [comment]
Subtle warning in the UI. Details in the log. But most important: if the problem is resolved the error should go away and the mirror should show the desired content. Otherwise you and up with a mirror full of errors after a while.

**Comment by rejas** [comment]
Weird, on my mac with node 16 the tests pass just fine....

**Comment by khassel** [comment]
> Uhohh... Node v16 fun begins. 🙈

that was quick ...

> Weird, on my mac with node 16 the tests pass just fine....

looking into the MR I see no obvious relation between the changes and the e2e errors. But you did change some dependencies including an electron update.

Tests yesterday with electron 11.3.0 --> e2e tests succeeded
Tested with electron 11.4.3 --> all e2e tests fail
Tested with electron 11.4.4 (first run) --> 5 e2e tests failed
Tested with electron 11.4.4 (second run) --> e2e tests succeeded

Node v16 is very new, the first docker images were released a few days ago.

**Comment by rejas** [comment]
Great, tests run fine when undoing the dependency updates. 

Now back to cleaning up the UI...

**Comment by rejas** [comment]
> Subtle warning in the UI. Details in the log.

Something like "Error: Malformed URL" / "Error: No connection" / "Error: Wrong Auth" while printing more stuff in the console?

**Comment by MichMich** [comment]
### Unable to load news items. 
##### Malformed news feed url.

**Comment by MichMich** [comment]
It should be understandable for people that not maintain the mirror ("grandma must understand there is a reason why the fancy mirror in the hallway of her son doesn't show any news"). :)

**Comment by rejas** [comment]
Updated the logic to show a descriptive text if we know whats going on (currently only "no internet connection" and "failed authorization", otherwise we tell to look into the logs:
Bildschirmfoto 2021-05-02 um 15 12 52
Bildschirmfoto 2021-05-02 um 15 14 15

Also, if the internet conenction comes back, the data is displayed again with no restart necessary

**Pull request merged**
