### PR TITLE
Add basic typescript types for module

### PR DESCRIPTION
**Pull request by henrikra**
### What does the pull request accomplish?
This PR adds TypeScript support for making modules! For example this module https://github.com/dolanmiu/MMM-awesome-alexa has been developed only with TS! MagicMirror platform should have types for module functions etc. 

So now I am able to do this in my modules with TS in my module:
`import { Log, Module } from "../../../../module-types"; // path goes to MagicMirror root folder` 
And after my module functions are usable with TS intellisense!

Note that all functions are not typed yet! I just wanted to get out bare bones version and start using it! I can make new PR's to extend the types when needed :)

### CODE REVIEW

**Comment by MichMich** [comment]
Your Changelog seems to have a conflict which I seem to be unable to fix. If this is fixed, I can merge your PR.

Note that these changes go under the 2.3.0 version in the changelog (not the 2.2.3 as currently stated in your PR).

Thanks!

**Comment by henrikra** [comment]
Is it right now @MichMich ?

**Comment by MichMich** [comment]
Yes, thanks! Merged.

**Comment by henrikra** [comment]
Do you when these types would be available in master? :)

**Comment by MichMich** [comment]
A new 2.X.0 release will be released quarterly. The 2.3.0 branch is scheduled to be released 2018-04-01.

**Comment by henrikra** [comment]
Woooow. But should we just release types as seperate thing to master? Since they dont break anything, they are just types. This way we would get more feedback from people about types etc 😄

**Comment by MichMich** [comment]
No sorry, I understand where you are coming from, but most changes are as small and unobstructive as these changes. If we release updates more often, people will be bugged with the "update available" notification too often. Which gets annoying. If someone want's to run on the bleeding edge, they can use the develop branch.

**Comment by henrikra** [comment]
Oh yeah you are right.

**Comment by roramirez** [comment]
@henrikra did you think I should be add this into [MagicMirror-Module-Template](https://github.com/roramirez/MagicMirror-Module-Template) ?

**Comment by henrikra** [comment]
If you want

**Pull request merged**
