### PR TITLE
Add sendNotifications option to clock module

### LINKED ISSUE #3056: disabling CLOCK_SECOND notification
is there a way to NOT send NOTIFICATION CLOCK_SECOND every single second (flooding) with `displaySeconds = true` in CLOCK module?

### PR DESCRIPTION
**Pull request by rejas**
Fixes #3056 

One question here would be if the default for this new option should be true or false.

True: keeps the current behaviour, nobody needs to change his config if they rely on this option

False: keeps the clock notifications quiet, doesnt waste time/resources, keeps the noise low

Maybe the original author @cybex-dev can weigh in on this, and why he added this notification.

### CODE REVIEW

**Review by khassel — APPROVED** [review]

**Comment by khassel** [comment]
@rejas will you wait for the reaction of the original author or shall I merge?

**Comment by rejas** [comment]
> @rejas will you wait for the reaction of the original author or shall I merge?

I'd like to know your opnion on my question regarding the default value first

**Comment by khassel** [comment]
I'm fine with this, the other way round the majority of users would still have the unwanted noise.

May this should mentioned in the docs as a "breaking" change.

**Comment by KristjanESPERANTO** [comment]
I also think it makes sense to set the default to `false`.

**Comment by rejas** [comment]
> May this should mentioned in the docs as a "breaking" change.

In the CHANGELOG or where do you mean? The docs website doesnt have any version information.

**Comment by khassel** [comment]
> In the CHANGELOG or where do you mean? The docs website doesnt have any version information.

I meant the docs, the new property `sendNotifications` should be added there with a hint to the new default

**Comment by rejas** [comment]
> I meant the docs, the new property `sendNotifications` should be added there with a hint to the new default

Ok, will open a PR there "soonish". This PR is therefor ready to merge @khassel

**Pull request merged**
