### PR TITLE
Mm fixes

### PR DESCRIPTION
**Pull request by aschulz90**
The default config definition doesn't conform with the JSON specification (http://www.json.org/ , http://jsonlint.com/). 

The issues were:

- value names must be strings
- strings are enclosed in double quotes
- no trailing commas

I am currently developing a module, where i modify the config file and i need to be able to parse the config JSON-Object with JSON.parse(...). But that fails, because its not valid JSON (when config.js is based on the default config). I will probably add a workaround for this into my module, but it would be good, if the default config file uses the standard.

### CODE REVIEW

**Comment by roramirez** [comment]
Hi @aschulz90 
The config statement is a Javascript dictionary instead of a JSON file definition.

**Comment by Jopyth** [comment]
As @roramirez says, it is not a JSON file, or were you suggesting to switch to a JSON file configuration, instead of a javascript file?

In my opinion, one of the neat things, we can do in the `config.js`, is multiplying time (sometimes the unit is *ms*), such as 30 * 60 * 1000, which is easier to recognize as half an hour, instead of 1800000. This would not be possible in a JSON file, and there is probably some other things, too.

**Comment by MichMich** [comment]
More importantly: it allows us to add closures (anonymous function) to the config in the future. So I won't be switching to JSON. (Especially since son doesn't support commenting.)

**Comment by aschulz90** [comment]
No, it's not a functionality change but a formatting one. I want the config definition to be easily be parsable when externally being extracted from config.js.

My usecase is that i extract the config with a Regex and try to parse it, which fails, because of the issues stated above.

The change doesn't modify any functionality from MagicMirror.

**Comment by MichMich** [comment]
@aschulz90 I understand what you wan't. But forcing JSON rules upon a javascript dictionary doesn't make sense. Especially since in the future, the config might even contain even more exotic content.

Maybe you could load the config as a javascript file and generate the JSON yourself?

**Pull request closed without merging**
