### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by KirAsh4**
- Fixed the spelling of 'exist' in various locations.

- Add proper User-Agent header for Facebook calendar request. References forum thread
https://forum.magicmirror.builders/topic/136/calendar-module-unable-to-load-facebook-birthdays

**Description:**
Facebook changed the way they respond to requests to their API, requiring a proper browser header to be send along with the request. This has now been added to the Calendar module. It now sends the following string:

_'Mozilla/5.0 (Node.js 6.0.0) MagicMirror/v2 (https://github.com/MichMich/MagicMirror/)'_

### CODE REVIEW

**Comment by MichMich** [comment]
I'd love to merge this PR. But it seems you got a reference to a `calendar2` added to the gitignore (and gitmodules). Which isn't part of the main project. Could you remove these references?

**Comment by KirAsh4** [comment]
Holy crap, I didn't think it would pull all that stuff in. When I did the PR, none of that existed yet. Ok, let me re-fork, and resubmit the PR. Later today though, I'm helping a friend move today.

**Comment by MichMich** [comment]
Your friend can wait! ;)

**Comment by KirAsh4** [comment]
If with 'your friend' you're referring to you, then yes, my friend can wait. :) Otherwise this girl here will kill me...

**Comment by MichMich** [comment]
Explain her the importance of your pull request. Start by explaining her every little detail about http headers, http requests, node.js libraries, electron applications. The works! I'm sure she'll understand.

**Comment by KirAsh4** [comment]
LOL, I was already explaining git and GitHub to her last night. I got the deer in headlights look. 

I am curious why the PR would pick up stuff that was done AFTER it was created. Seems odd. I'll make a new one though.

**Comment by KirAsh4** [comment]
All fukkered up ...

**Pull request closed without merging**
