### PR TITLE
Fix for issue #950

### PR DESCRIPTION
**Pull request by QNimbus**
Changed 'server.js' to allow an empty ipwhitelist to allow any and all hosts instead of none as mentioned in the documentation

### CODE REVIEW

**Comment by nhubbard** [comment]
@QNimbus Could you fix the style issues in this PR?

**Comment by QNimbus** [comment]
@nhubbard I pushed a new commit - I'm curious as to how those lint errors snuck in there because I didn't touch the files in question.... at least not that I'm aware of.... 

However, It should be fixed now! Thanks for the tipoff!

**Comment by dillenburg** [comment]
Ich kümmere mich jetzt drum.

Von meiner Apple Watch gesendet

Am 18.07.2017 um 14:10 schrieb Bas <notifications@github.com>:

**Comment by nhubbard** [comment]
@dillenburg I don't understand? Was this comment made by mistake?

**Pull request merged**
