### PR TITLE
Add HTTPS-Support for ClientMode

### PR DESCRIPTION
**Pull request by AndreKoepke**
This adds the ability for clients to use a TLS-server. It's works perfect with Lets-Encrypt-Certificates.

### CODE REVIEW

**Comment by AndreKoepke** [comment]
I will create a new PR with nicer commits and changes to `CHANGELOG.md` in the next days. :)

**Comment by khassel** [comment]
I'm interested in your usecase. My first thoughts were: If I need https I put a reverse proxy in front of  magicmirror which handle the https stuff and certs. E.g. [traefik](https://docs.traefik.io/) has direct support for letsencrypt.

**Comment by AndreKoepke** [comment]
Your thoughts are very close to my usecase. Iam running magicmirror (serveronly) behind a reverse proxy (in a [Minicube](https://kubernetes.io/docs/setup/learning-environment/minikube/) cluster with an automatic [cert-manager](https://github.com/jetstack/cert-manager)) in the internet.

My raspberry at home running the magicmirror in clientonly-mode. But the clientonly-mode has a hardcoded `http://`-prefix (see the changes in PR), so it can't consume my magicmirror-server.

**Comment by khassel** [comment]
o.k., missed the clientonly-mode ...

One other thing to be aware of: The server config is public, so every secret of your config.js is available under `https://example.com/config` or `https://example.com/config/config.js`

**Comment by AndreKoepke** [comment]
Also with a ip-whitelist?

**Comment by khassel** [comment]
whitelist should work, or proxy with basic authentication and `user:password@example.com`

**Pull request closed without merging**
