### PR TITLE
Add Dark Sky Module

### PR DESCRIPTION
**Pull request by nhubbard**
> Please send your pull requests the develop branch.
> Don't forget to add the change to CHANGELOG.md.

**Note**: Sometimes the development moves very fast. It is highly
recommended that you update your branch of `develop` before creating a
pull request to send us your changes. This makes everyone's lives
easier (including yours) and helps us out on the development team.
Thanks!

* Does the pull request solve a **related** issue? No, talked about on Slack, though.
* If so, can you reference the issue?
* What does the pull request accomplish?
    * Insert a new provider for Dark Sky on the new weather system branch.
* If it includes major visual changes, please add screenshots.

### CODE REVIEW

**Comment by nhubbard** [comment]
@MichMich This is the Dark Sky module that I was talking about earlier. I didn't test if it worked yet, but since we are still developing the new weather module, it still may not work... :smile:

**Comment by MichMich** [comment]
Thanks. Is it possible that you only send the dark sky provider in this pr? All the other changes (indentation) should go to the develop branch.

Thanks!

**Comment by MichMich** [comment]
Also note that I won't be updating your provider during the development process. So keep an eye on all the changes eye make to make sure they are reflected in this provider.

**Comment by nhubbard** [comment]
@MichMich Sorry about the indentation thing. Travis was having a fit, so I decided to fix it to avoid issues in the future.

**Comment by MichMich** [comment]
As discussed, please send a new PR after the modifications are done. :)

**Pull request closed without merging**
