### PR TITLE
Update pt.json

### PR DESCRIPTION
**Pull request by EdgardosReis**
pt translation updated

### CODE REVIEW

**Comment by morozgrafix** [comment]
@EdgardosReis you may want to pull latest develop branch and make your changes based on that.

**Comment by MichMich** [comment]
@roramirez There is a function somewhere in MM that allows commenting in JSON files for translation purposes (to make clear what it's for). It's a bit inconvenient, that this is no longer possible. Is there a way to solve this?

**Comment by roramirez** [comment]
Yes there a function to remove the comments in js/translations.js is called stripComments. For standar JSON not should containt comments. The function preparse the file before load like json.

https://www.ietf.org/rfc/rfc4627.txt
https://www.ietf.org/rfc/rfc7159.txt

The problem is for validated the json translations by Grunt not can containt comments. Should be a valid JSON file.

This point is interesting and savory to discution about what we can do. Maybe @CFenner and @nhubbard can pushed about this topic.

**Comment by nhubbard** [comment]
@EdgardosReis @MichMich @roramirez See [here](https://github.com/jashkenas/docco/pull/260#issuecomment-32467210) for another point that JSON shouldn't contain comments.

**Pull request merged**
