### PR TITLE
Resubmitted ESLint Removal.

### PR DESCRIPTION
**Pull request by nhubbard**
ESLint was annoying me because it conflicted with JSCS and insisted that I use a different indentation. So I removed it. I also fixed what was wrong with my previous pull request. It should be better now. :+1:

### CODE REVIEW

**Comment by MichMich** [comment]
Sorry to be a pain in the ass, but why did you add `.clockbold` to main.css if you can just use the default class: `.bold`?

**Comment by nhubbard** [comment]
Oops, didn't notice that. Sorry!

**Comment by MichMich** [comment]
An now it has conflicts ... 😨

**Comment by MichMich** [comment]
also, I wouldn't add `require("dotenv").config();` to the config file. You should do this in js/defaults.js. This is the base config if there isn't any config available. 

One suggestion: split up pull requests to prevent pull requests getting denied on minor issues.

**Comment by nhubbard** [comment]
Okay, I will close this. But I have only one issue: the `dotenv` module needs to be in both the default configuration *and* the user configuration because it will not load if it isn't required.

**Pull request closed without merging**
