### PR TITLE
Feature/indoor humidity

### PR DESCRIPTION
**Pull request by ryck**
> Please send your pull requests the develop branch.
> Don't forget to add the change to CHANGELOG.md.

**Note**: Sometimes the development moves very fast. It is highly
recommended that you update your branch of `develop` before creating a
pull request to send us your changes. This makes everyone's lives
easier (including yours) and helps us out on the development team.
Thanks!

* Does the pull request solve a **related** issue?
* If so, can you reference the issue?
* What does the pull request accomplish? Use a list if needed.
* If it includes major visual changes please add screenshots.

### CODE REVIEW

**Comment by nhubbard** [comment]
@ryck Just curious, I'm having a little bit of trouble determining where the data for this comes from. Are you getting it from OpenWeatherMap? (we're having a bit of trouble with specific endpoints, so I'm trying to figure out some changes)

**Comment by ryck** [comment]
Hi @nhubbard 

It's coming from a DHT22 sensor, using this module: https://github.com/ryck/MMM-DHT-Sensor; it's the indoor humidity after all 😛

**Comment by nhubbard** [comment]
@ryck Sounds good to me, but this may need to be changed into a second-party (external contributors) module. Either that, or merge the DHT sensor technology into this module.
@MichMich What's your opinion on this?

**Comment by ryck** [comment]
@nhubbard Whatever you think is best, I just did the PR under the impression this was similar to the _INDOOR_TEMPERATURE_ (ie, have support for the notification, no matter where it comes). IMHO, there is no point in merge anything else: either we want the currentwheather to support it or not (which is also fine, maybe having the ext temperature, int temperature and int humidity is a little too much)

**Comment by MichMich** [comment]
I like this contribution, especially since the source can be determined by an external module.

**Pull request merged**
