### PR TITLE
currentweather, weatherforecast: sample URL for LocationID:

### PR DESCRIPTION
**Pull request by roramirez**
Changed from README the sample URLs for get the LocationID.
The http://bulk.openweather.org/sample/ doesn't work

### CODE REVIEW

**Comment by derbergbordesholm** [comment]
<a href="ihttp://openweathermap.org/help/city_list.txt">OpenWeatherMap</a> 

ihttp   ?

**Comment by roramirez** [comment]
Hi @derbergbordesholm, is a mistake, I'll fix right now.

**Comment by derbergbordesholm** [comment]
Thank you. 
Is there a global Problem withe the weater module? 
i coulndt get any weather info of any id or name.
Perhaps more links have to be fixed ?

**Comment by MichMich** [comment]
@derbergbordesholm No, it should be working. For support please visit http://forum.magicmirror.builders

**Comment by roramirez** [comment]
@derbergbordesholm 
The fix here is only for README examples. It's not related with module work.

Please check your API KEY it's working, try using the URL 
_http://api.openweathermap.org/data/2.5/weather?lang=es&q=Chillan,Chile&cnt=7&units=metric&APPID=CHANGEME_FOR_YOUR_APIKEY_

If a problem of working open a new issue or support http://forum.magicmirror.builders

**Comment by MichMich** [comment]
NB. Please **only** open an new issue on GitHub if it is a reproducible issue confirmed by other users on the forum.

**Comment by MichMich** [comment]
Thanks!

**Pull request merged**
