### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by CriticalPoint**
Scanned through and corrected some spelling, nothing that affects the core purpose of the document.

### CODE REVIEW

**Comment by MichMich** [comment]
I love PR's like these! Thanks!

**Comment by MichMich** [comment]
Great to hear! That's exactly why I started this project: https://github.com/MichMich/MagicMirror#manifesto :)

**Comment by showbizkid833** [comment]
Hello Gentlemen, Reaching out for some help with the PIR on the MagicMirror. Thank for your project. I am new to MagicMirror but have successfully created a Mirror for my son. I need some help with the PIR Sensor. The Mirror is not responding at all to the hooked up sensor don't know what I am missing. the PIR is hooked up to the Pi. This is the last module I'm putting on. Confused about line three. Add your user pi to the GPIO group. Which folder does this command go in? The Root directory or the MagicMirror folder. I have it in both. I need a few more details about this. Would appreciate what ever anybody can do to help me get this to work. The modules i currently have         modules: [
                {
                        module: "alert",
                },
                {
                        module: "updatenotification",
                        position: "top_bar"
                },
                {
                        module: "clock",
                        position: "top_left"
                },
                {
                     module: ' MMM-SingleStock',
                     position: 'upper_third',
                     config:  {
                     stockSymbol: 'BBy',
                     updateInterval: 3600000,
                     showChange: true,
                     label: 'symbol'
                              }
                },
                {
                        module: "MMM-CalendarExt",
                        position: "top_center",
                        config: {
                          system: {
                            show: ["month", "upcoming"],
                            locale: 'en',
                            showEmptyView: 1,
                            redrawInterval:60000,
                          },
                          views: {
                            daily: {
                              position:'bottom_bar',
                              counts:7,
                            },
                            upcoming: {
                              position:'top_left',
                              limit:5
                            },
                          },
                          defaultCalendar: {
                            maxEntries:50,
                            maxDays:180,
                            interval: 30000,
                          },
                          calendars :[
                            {
                              name: "PRESTON'S_CALENDAR",
                              symbol: "calendar-o",
                              styleName: "style1",
                              url: "webcal://p56-calendars.icloud.com/published/2/AAAAAAAAAAAAAAAAAAAAAPC0relXkXj-YMHQHSuMIP0zP8Y2vfXpqy3AzUKlZiclyaLu1AdEhW2JqRREQ-gfOlS3hyw9u_S8SWq1914D1Pc",
                            },
                            {
                              name:"Texas Rangers Baseball",
                              url:"webcal://api.calreply.net/webcal/096b22ef-0049-487a-a8cd-53f9c9aa996b",
                              views: ["month", "upcoming"],
                              styleName: "style1",
                              maxEntries: 30,
                              maxDays:365,
                              interval: 3600000,
                            }
                         ],
                     }
                },   
                {
                        module: "MMM-quote-of-the-day",
                        position: "lower_third",
                        config:{
                           language:"en",
                           updateInterval: "1d"
                               }
                }
               {
                        module: 'MMM-PIR-Sensor',
                        config: {
                          sensorPin: 22,
                          sensorState: 1,
                          powerSaving: true
                                }
                },
                {
                      module: "MMM-DarkSkyForecast",
                      header: "Weather",
                      position: "top_right",
                      classes: "default everyone",
                      disabled: false,
                      config: {
                              apikey: "de8a9773c59d40feb15332bc87b905fc",
                              latitude: "32.9481789",
                              longitude:" -96.7297206",      
                              iconset: "4c",
                              concise: false,
                              forecastLayout: "table",
                              units: "us"
                             }
                }
        ]

};

Thanks again for your help.

**Comment by CriticalPoint** [comment]
> {
> module: "MMM-quote-of-the-day",
> position: "lower_third",
> config:{
> language:"en",
> updateInterval: "1d"
> }
> },           **<---- This comma here is missing**
> {
> module: 'MMM-PIR-Sensor',
> config: {
> sensorPin: 22,
> sensorState: 1,
> powerSaving: true
> }
> },

Hey @showbizkid833 , bit of a strange place to post for support on this one, nevertheless I'm looking at your config and there are a number of things that stick out, some just best practices I think, either way, below is a modified config for you, minus the API key and webcal links, as you know those, and I recommend you remove them from public consumption (edit your comment) :)

Basically _MMM-quote-of-the-day_ & _MMM-PIR-Sensor_ modules weren't separated with a comma.

/ Crit




```
modules: [
		{
			module: 'alert',
		},
		{
			module: 'updatenotification',
			position: 'top_bar'
		},
		{
			module: 'clock',
			position: 'top_left'
		},
		{
			module: ' MMM-SingleStock',
			position: 'upper_third',
				config: {
				stockSymbol: 'BBy',
				updateInterval: 3600000,
				showChange: true,
				label: 'symbol'
				}
		},
		{
			module: 'MMM-CalendarExt',
			position: 'top_center',
				config: {
				system: {
				show: ['month', 'upcoming'],
				locale: 'en',
				showEmptyView: 1,
				redrawInterval:60000,
					},
				views: {
					daily: {
						position:'bottom_bar',
						counts:7,
						},
					upcoming: {
						position:'top_left',
						limit:5
						},
					},
				defaultCalendar: {
					maxEntries:50,
					maxDays:180,
					interval: 30000,
					},
				calendars :[
					{
					name: "PRESTON'S_CALENDAR",
					symbol: 'calendar-o',
					styleName: 'style1',
					url: 'REMOVED',
					},
					{
					name:'Texas Rangers Baseball',
					url:'webcal://api.calreply.net/webcal/096b22ef-0049-487a-a8cd-53f9c9aa996b',
					views: ['month', 'upcoming'],
					styleName: 'style1',
					maxEntries: 30,
					maxDays:365,
					interval: 3600000,
					}
				],
				}
		},
		{
			module: 'MMM-quote-of-the-day',
			position: 'lower_third',
				config:{
				language:'en',
				updateInterval: '1d'
				}
		},
		{
			module: 'MMM-PIR-Sensor',
				config: {
				sensorPin: 22,
				sensorState: 1,
				powerSaving: true
				}
		},
		{
			module: 'MMM-DarkSkyForecast',
			header: 'Weather',
			position: 'top_right',
			classes: 'default everyone',
			disabled: false,
				config: {
				apikey: 'REMOVED',
				latitude: '32.9481789',
				longitude:' -96.7297206',
				iconset: '4c',
				concise: false,
				forecastLayout: 'table',
				units: 'us'
				}
		},
	]

};
```

**Comment by showbizkid833** [comment]
As you can see I’m new at these post. This was not an easy task for me. The things as far as programming you guys know is amazing. After much study and reading and completing this Mirror I’ve learned a lot. Trying to keep the old mind sharp you know. Thanks for your project and all the people from all over the world that are willing to share their knowledge with me. Thanks again.

**Comment by CriticalPoint** [comment]
> As you can see I’m new at these post. This was not an easy task for me.

You're all good, I learned tonnes with this project, well done on taking the leap! Let me know how you get on with the new config :)

**Comment by showbizkid833** [comment]
Ok thanks!

**Comment by showbizkid833** [comment]
Dang comma’s

**Pull request merged**
