### PR TITLE
Issue 2221 Weather module - Always displays night icons because of fixed day start and end time

### PR DESCRIPTION
**Pull request by ashishtank**
Added support to get day start and end time from city sunrise and sunset time if available.
Also added unit test cases for data with and without sunset time.

Refer : #2221

### CODE REVIEW

**Comment by khassel** [comment]
@ashishtank  I think we have problems with the tests after merging this.
The tests are now depending from the timezone.

In my `TZ=Europe/Berlin` its now ~ 23:00 and starting `npm run test:unit` succeeds.

Set `TZ=Australia/Sydney` test results in:
````
  104 passing (3s)
  1 failing

  1) Functions module weatherforecast
       forecastIcons
         forecastIcons sunset specified
           returns correct icons with sunset time:

      AssertionError: expected 'wi-night-cloudy' to equal 'wi-rain'
      + expected - actual

      -wi-night-cloudy
      +wi-rain

      at Context.<anonymous> (tests/unit/functions/weatherforecast_spec.js:84:37)
      at processImmediate (internal/timers.js:461:21)
````

Set `TZ=America/New_York` test results in:
````
  104 passing (3s)
  1 failing

  1) Functions module weatherforecast
       forecastIcons
         forecastIcons sunset specified
           returns correct icons with sunset time:

      AssertionError: expected 'wi-night-rain' to equal 'wi-rain'
      + expected - actual

      -wi-night-rain
      +wi-rain

      at Context.<anonymous> (tests/unit/functions/weatherforecast_spec.js:84:37)
      at processImmediate (internal/timers.js:461:21)
````

**Comment by ashishtank** [comment]
@khassel : Thanks for the feedback, I looked at it but could not figure out how I can set default time zone for this tests so it always takes Europe Time zone while executing, as the test data is for Poland.

**Comment by ashishtank** [comment]
@khassel I have solved the issue by setting time zone in test case and changing the way we create dates in weather forecast module. Tomorrow after some more testing will create pull request.

**Comment by fewieden** [comment]
@ashishtank the keyword here is mocking. You need to mock the date so it will always be the same for the test case. This way you can simulate executing the logic at night and day at the same time to cover both. Even if you force the timezone to Europe you will have different results if you run the tests at day or night.

**Comment by rejas** [comment]
@ashishtank see https://github.com/MichMich/MagicMirror/search?q=mockDate for an example on how in the compliments module the date is mocked

**Comment by ashishtank** [comment]
Thanks for the tips Guys. 

Original issue was with locale that hour sign was being set to Unicode text ( ७ in Hindi) which was not being compared to offset (8). After solving that we found that for many countries day starts/ends different then our hard coded offset so in this PR we are using sunset and sunrise time if returned by weather provider. Now as this time is in EPOCH it was creating some issue with different time zones for testcase.
So I have corrected the way we are creating date objects in weather forecast module now for this and set the default time zone in test case.

I have tested this with multiple time zones with different times. Hope this will work as expected. Refer PR #2417

**Pull request merged**
