### PR TITLE
Making the word "commit" localizable in the UpdateNotification module message

### PR DESCRIPTION
**Pull request by balassy**
This PR changes the UPDATE_INFO message used by the UpdateNotification module: the COMMIT_COUNT placeholder does not contain the word "commit" or "commits" any more, so language files can independently localize them.

Instead of introducing a logic to use the singular or the plural form of the word ("commit" or "commits"), I added the word "commit(s)" to the language files.

Note that some language files already contained this word in some form, that's why not all language files are affected by this change. I can confirm that the Hungarian localization is perfect after this change.

This PR may fix Issue #1368 .

Thanks for reviewing!

### CODE REVIEW

**Comment by MichMich** [comment]
I appreciate your work, but I find the commit**(s)** not very elegant. Maybe it's better to add two keys to the translation files: `COMMIT` & `COMMITS`. Since the translation system uses fallbacks, these only need to be available in the English translations.

Languages that need localisation can overwrite these.

**Comment by balassy** [comment]
I don't understand how fallbacks could help here, since most languages already have this message localized, and if I understand correctly the translation system can only fallback between languages, but not between resource keys.
Anyways, I created two different resource keys in the language files. What do you think?

**Comment by MichMich** [comment]
Valid reason. I think the only thing left to do is to modify the changelog entry so it reflects a bit better what it does now ... Can you make that change so I can merge it?

**Comment by balassy** [comment]
I've updated the branch and changed the CHANGELOG entry. What do you think?
Thank you.

**Comment by MichMich** [comment]
Thanks! Merged!

**Comment by balassy** [comment]
Thanks for merging!

**Pull request merged**
