### PR TITLE
Use fetch instead of XMLHttpRequest in weatherprovider

### PR DESCRIPTION
**Pull request by rejas**
small update to the fetchData method to use the fetch helper instead of the old XCMLHttpRequest. 
Also fixes some typos :-)

### CODE REVIEW

**Comment by rejas** [comment]
Thanks for merging so quick @khassel. But could we agree that only the maintainer who created a PR merges it (of course only after one of the other maintainers approves it)? Or should we keep it strict to the "if its not really finished, do a draft PR" policy? What do you think?

**Comment by sdetweil** [comment]
what is a 'draft' pr?   never seen one til the other day. 

I don't think I should be the one merging MY submitted PR's..

**Comment by khassel** [comment]
> Or should we keep it strict to the "if its not really finished, do a draft PR" policy? 

yes, if not ready --> draft, if discussions are coming up --> draft

> But could we agree that only the maintainer who created a PR merges it (of course only after one of the other maintainers approves it)?

I was thinking of the opposite, never merge your own PR ...

**Comment by khassel** [comment]
> what is a 'draft' pr? never seen one til the other day.

this is a PR which is not ready for merge (we have 2 at the moment here). You can open it as `draft` for discussing stuff or change later to `draft` if someone has suggestions or code must be refactored before merging.

You can't merge `draft` PR's.

**Comment by rejas** [comment]
> what is a 'draft' pr? never seen one til the other day.

but now you have I assume? when creating a PR you can mark it as a draft (so basically WorkInProgress)

> I don't think I should be the one merging MY submitted PR's..

so new rule: 
- never merge your own PRs
- never merge without someone else having approved?

**Comment by khassel** [comment]
o.k. for me too

**Comment by sdetweil** [comment]
i just tried to create a PR, but don't see a mechanism for draft..

**Comment by khassel** [comment]
Existing PR see picture below:

grafik

AFAIK this property is also visible when creating a new one.

**Comment by sdetweil** [comment]
there it is . never noticed the dropdown!.. 

Screenshot at 2022-10-06 15-40-17

**Comment by rejas** [comment]
> there it is . never noticed the dropdown!..

yes, its not the best UI decision from github....

**Pull request merged**
