### PR TITLE
Update eslint config to use eslint:recommended

### PR DESCRIPTION
**Pull request by rejas**
Eslint offers an `eslint:recommended` package that provides sensible defaults. 

Switching to this found some warnings and more issues like duplicate properties. Fixed most of them while disabling three rules for now from the recommended package that triggered more warnings (454 to be exact) than I wanted to fix without getting your opinion on it :-)

So if this gets merged we could look at the other rules and their warnings:

		"no-prototype-builtins"
		"no-undef"
		"no-unused-vars"

and how and when to fix them.

### CODE REVIEW

**Comment by MichMich** [comment]
Yeah ... that sounds like a sensible idea. :)

**Comment by rejas** [comment]
Got to check first why the tests fail :-)

**Comment by sdetweil** [comment]
can we move the eslint  dependency out of the devdependencies?  as we need it now in prod. 
i do 
```
npm install --only-prod
```
 to eliminate problems on the armv6l devices.  but then eslint doesn't get installed..

**Comment by rejas** [comment]
why do we need it in prod?

**Comment by sdetweil** [comment]
because it is used by check:config now

**Comment by rejas** [comment]
ah, yes, you are correct. should i do the change here or open a new PR for this @MichMich ?

**Comment by MichMich** [comment]
You can use this PR. Thanks for your hard work!

**Comment by rejas** [comment]
Moved eslint to dependencies and added another useful eslint rule. If the tests are fine and you are ok with it, the PR would be ready for merging...

**Comment by rejas** [comment]
So @MichMich what is your opinion on this PR? Ready to merge? Fix other stuff too or rather in another PR?

**Comment by MichMich** [comment]
Merged! Thanks again!

**Pull request merged**
