### PR TITLE
Added start:dev command to npm scripts

### PR DESCRIPTION
**Pull request by rejas**
I noticed there was the option to start electron with the dev command line argument. So I figured it would make sense to add an entry for that in the package.json scripts section for this.

### CODE REVIEW

**Comment by MichMich** [comment]
Thanks! Would you mind sending a PR to the docs repo as well?

**Comment by rejas** [comment]
> Thanks! Would you mind sending a PR to the docs repo as well?

Will do. Which section do you think would it fit in @MichMich ?

**Comment by MichMich** [comment]
No idea. 😂

**Comment by rejas** [comment]
I just found out it's already there:
https://docs.magicmirror.builders/getting-started/installation.html#usage

**Pull request merged**
