### PR TITLE
Increment timeout e2e test to 20000 ms

### PR DESCRIPTION
**Pull request by roramirez**
Increment to 20000ms timeouts of e2e tests.

This recommendation is mentioned by @qistoph
https://forum.magicmirror.builders/post/14358

### CODE REVIEW

**Comment by roramirez** [comment]
@MichMich Can you re-run this build https://travis-ci.org/MichMich/MagicMirror/builds/200750793 ?

**Comment by qistoph** [comment]
Rerun it before adding the timeout. That was enough for me last time and will give us some insight

**Comment by MichMich** [comment]
Doesn't seem to be working: https://travis-ci.org/MichMich/MagicMirror/jobs/200750794

**Comment by qistoph** [comment]
It's not a timeout issue in the latest log. Something else is going wrong now... Weird

`The command "eval git fetch origin +refs/pull/715/merge: " failed. Retrying, 2 of 3.`

**Comment by fewieden** [comment]
this happened on some builds before

**Comment by roramirez** [comment]
This error is because the branch for Pull Request is not exits anymore. When Travis gets the origin for this Pull Request cannot find it.

I think we can should be increment the timeout like @qistoph say it before. We can checking what happening this week with the  tests running on Travis.

**Comment by MichMich** [comment]
I'm still getting A LOT of timeout issues with travis. There really should be a better solution than increasing the timeout ...

> Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

**Pull request merged**
