### PR TITLE
Start helper_scripts as childs

### PR DESCRIPTION
**Pull request by paviro**
Start helper_scripts as childs instead of just loading them into the main script.

### CODE REVIEW

**Comment by MichMich** [comment]
Maybe only te helper scripts of the "loaded" modules should be started? This can be done by walking thru the config to see which modules will be loaded.

**Comment by paviro** [comment]
Yes, I tried that but I could not figure out how to do it... I probably should start learning JavaScripts because I am missing a lot of basics, well after my final exams in school..
Problem is I was not able to load your config variable into the node.js "electron.js" script, if you happen to know how to do it I can implement it if you give me a hint!

**Comment by MichMich** [comment]
This solution is ok for now. Maybe we should put it on a todo list in the readme.

**Comment by paviro** [comment]
Sounds good I will add it and open a pull request.

**Pull request merged**
