### PR TITLE
Close #281: ESLint and using the force, Luke

### LINKED ISSUE #281: [Tracking Issue] ESLint, JSCS Deprecation, and Tests
If any of you follow the JSCS project that we use for coding style, they have deprecated the project in favor of merging with ESLint. I have been reading up on ESLint, and found that I have been doing it wrong all along! :fearful: 

So, this is a tracking issue. We make a checkmark list to show what progress is happening here.

- [x] Remove JSCS and replace it with ESLint.
- [x] Add Travis tests to enforce ESLint, StyleLint, and HTML Validator rules.

I expect this entire system to be done by the end of the beta.

### PR DESCRIPTION
**Pull request by nhubbard**
This PR closes issue #281.

### CODE REVIEW

**Comment by nhubbard** [comment]
Also, please don't mind the merge, I made a change online and offline and it got confused, so I used that to fix it.

**Comment by nhubbard** [comment]
@MichMich, we need to enable Travis, but you need to do it using your GitHub account.

**Comment by MichMich** [comment]
Will look into that asap.

**Comment by MichMich** [comment]
https://github.com/MichMich/MagicMirror/blob/master/.github/CONTRIBUTING.md is still talking about jslint. Could you add the right listing info?

**Pull request merged**
