### PR TITLE
Feature "bower": install external frontend dependencies via bower

### PR DESCRIPTION
**Pull request by Bruce17**
Install all frontend dependencies via bower, see issue https://github.com/MichMich/MagicMirror/issues/691.

Changes to support bower:
* Install external frontend dependencies into `public/components`.
* Removed folders `fonts` and `vendor`. Its content is installed via bower into the folder `public/components`.
* Changed `paths.vendor` file `js/defaults.js` to load vendor libraries from `public/components`.
* Update resource paths in `index.html`.

Changes to improve development:
* Add `.editorconfig` file to set some global code style settings in supported IDEs.
* Add [nodemon](https://github.com/remy/nodemon) to automatically reload Node.js in `serveronly` mode for development purposes.
* Test some more Node.js versions.

### CODE REVIEW

**Comment by MichMich** [comment]
Let's stick to NPM. ;)

**Comment by Bruce17** [comment]
No discussion at all? :disappointed:

**Comment by MichMich** [comment]
Sorry, I didn't notice the issue. My best guess this was yet an other PR with a lot of unnecessary changes. (I get them a lot ... ;))

Of course I'm willing to discuss this. Let's use the issue you opened to do this.

**Comment by fewieden** [comment]
I guess the content of this pr should be splitted into two anyways:
- change to bower or as requested in the issue npm
- improve development

as they are not related to each other

**Comment by MichMich** [comment]
For the future, to prevent your work from not being merged, keep the contribution guidelines in mind: https://github.com/MichMich/MagicMirror#contributing-guidelines

> Please discuss in a GitHub issue before you start to alter a big part of the code. Without discussion upfront, the pull request will not be accepted / merged.

**Comment by Bruce17** [comment]
Well it was discussed, see:
> Why not try a send a Pull Request about this?

So I thought I give it a try.

**Comment by MichMich** [comment]
@Bruce17 Yeah, sorry ... You got a valid point there. I'll talk to @roramirez about this. To prevent confusion in the future.

**Comment by roramirez** [comment]
Ups, sorry but that :(. The "try" was mean a suggest to @Bruce17. Not to ensure to him the change will pass the merge.

**Pull request closed without merging**
