### PR TITLE
Add missing CS translations

### PR DESCRIPTION
**Pull request by krekos**
Hello and thank you for wanting to contribute to the MagicMirror project

**Please make sure that you have followed these 4 rules before submitting your Pull Request:**

> 1. Base your pull requests against the `develop` branch.
>
> 2. Include these infos in the description:
>
> - Does the pull request solve a **related** issue?
> - If so, can you reference the issue like this `Fixes #<issue_number>`?
> - What does the pull request accomplish? Use a list if needed.
> - If it includes major visual changes please add screenshots.
>
> 3. Please run `npm run lint:prettier` before submitting so that
>    style issues are fixed.
>
> 4. Don't forget to add an entry about your changes to
>    the CHANGELOG.md file.

**Note**: Sometimes the development moves very fast. It is highly
recommended that you update your branch of `develop` before creating a
pull request to send us your changes. This makes everyone's lives
easier (including yours) and helps us out on the development team.

Thanks again and have a nice day!

### CODE REVIEW

**Comment by KristjanESPERANTO** [comment]
Great, thanks :slightly_smiling_face:  Can you also update the CHANGELOG.md?

**Comment by krekos** [comment]
@KristjanESPERANTO Hello, yes, but what Version number and release date i should use? 2.18.1 and for date 1st of next month?

**Comment by rejas** [comment]
> I probably forked Master insted of Develop and i cannot sync changes, so i didnt see the new Changlog. Will you merge the PR with changing the Changelog in another PR, or should i close this PR and make a new one?

@MichMich might be able to do that and update your PR before merging it

**Comment by MichMich** [comment]
I'll merge it! 👍🏻

**Comment by krekos** [comment]
Thnak you. And sorry for more work :)

**Pull request merged**
