### PR TITLE
Add includePastEvents global and calendar-specific settings

### PR DESCRIPTION
**Pull request by kolbyjack**
For my module MMM-MonthlyCalendar, I need access to events that have already past.  This change will allow users to broadcast those events, while still only displaying future events in the default calendar module.

### CODE REVIEW

**Comment by MichMich** [comment]
Thank!

Im afraid most users don't understand what "event broadcasts" are which will result in users expecting to show events from the past when setting `includePastEvents` to true. Maybe we should use an other config name?

**Comment by dxfan227** [comment]
is there any way to "broadcast only todays events"? I would really love this cause my other module ( google route) is trying to show me a route for an event in 20 days

**Comment by MichMich** [comment]
This PR seems to have merge conflicts. Please rebase the PR. Thanks for your contribution.

**Comment by MichMich** [comment]
Merged! Sorry for taking so long.

**Pull request merged**
