### PR TITLE
Catch errors when parsing calendar data with ical

### LINKED ISSUE #2022: Calendar fails to parse my iCal
With MagicMirror 2.11.0 (tag, from git), pointing the calendar module at my private iCal causes an error:

```
[2020-05-18 16:35:07.063] [ERROR]  Error: Unknown RRULE property 'RRULE'
    at /Users/ross/Programming/MagicMirror/node_modules/rrule/dist/es5/rrule.js:1191:23
    at Array.forEach (<anonymous>)
    at parseRrule (/Users/ross/Programming/MagicMirror/node_modules/rrule/dist/es5/rrule.js:1149:11)
    at parseLine (/Users/ross/Programming/MagicMirror/node_modules/rrule/dist/es5/rrule.js:1138:20)
    at Array.map (<anonymous>)
    at Function.parseString (/Users/ross/Programming/MagicMirror/node_modules/rrule/dist/es5/rrule.js:1110:41)
    at Function.RRule.fromString (/Users/ross/Programming/MagicMirror/node_modules/rrule/dist/es5/rrule.js:2135:32)
    at Object.ical.objectHandlers.END (/Users/ross/Programming/MagicMirror/modules/default/calendar/vendor/ical.js/node-ical.js:73:23)
    at Object.handleObject (/Users/ross/Programming/MagicMirror/modules/default/calendar/vendor/ical.js/ical.js:400:41)
    at Object.parseICS (/Users/ross/Programming/MagicMirror/modules/default/calendar/vendor/ical.js/ical.js:441:20)
```

### PR DESCRIPTION
**Pull request by rejas**
Fixes #2022

### CODE REVIEW

**Comment by sdetweil** [comment]
Does this still fail now that we are using node-ical?

**Comment by sdetweil** [comment]
Are we still getting this, now that we have moved to node-ical?

**Comment by rejas** [comment]
Not sure. But its a failsafe in case some calendar data in the future throws errors.

**Comment by sdetweil** [comment]
i just submitted a pr to node-ical to detect and fix this problem

**Pull request merged**
