### PR TITLE
Default modules set

### PR DESCRIPTION
**Pull request by roramirez**
Add test for modules/default/defaultmodules.js

### CODE REVIEW

**Comment by undergroundauth** [comment]
Thanks this works
You guys are amazing!!

**Comment by undergroundauth** [comment]
app is running fine but getting black screen please help

**Comment by batzyn** [comment]
Ok I install everything but only I sell the clock and the calendar of the messages and the news but install the modules of email and the weather but nothing comes out on the screen is black only with clock and calendar and news that I can do?

**Comment by justjim1220** [comment]
Need to see your code

**Comment by batzyn** [comment]
Code change config.js but nothing happens

**Comment by roramirez** [comment]
Sorry guys this is a Pull Request. You should to move the conversation another place. In case the comment is related on review of this change add here.

If need support for any troubles go to forum https://forum.magicmirror.builders/

**Pull request merged**
