### PR TITLE
Cleanup compliments module

### PR DESCRIPTION
**Pull request by rejas**
Lots of small fixes and cleanups:
- only render something when there is a compliment
- cleanup naming
- use es6 notations
- use fetch instead of XMLHttpRequest in compliments

### CODE REVIEW

**Comment by rejas** [comment]
@khassel asking you as the test-specialist ;-) : how can I fix the tests not finding "fetch" when I switch the module xmlhttprequest to fetch?

```
  ● Compliments module › remoteFile option › should show compliments from a remote file

    ReferenceError: fetch is not defined
```

**Comment by khassel** [comment]
will try to look at this but I have very limited time until end of this month ...

**Comment by BadAtheist** [comment]
not working with HTML compliments like:
```
	"day_sunny": [
		"<i class=\"gold wi wi-day-sunny\"></i> Sunny day",
	],
```

**Comment by rejas** [comment]
> This was one of the simplest modules that worked properly, now is not working with HTML compliments like:
> 
> ```
> 	"day_sunny": [
> 		"<i class=\"gold wi wi-day-sunny\"></i> Sunny day",
> 	],
> ```

when did it stop working? with this PR?

**Comment by BadAtheist** [comment]
> > This was one of the simplest modules that worked properly, now is not working with HTML compliments like:
> > ```
> > 	"day_sunny": [
> > 		"<i class=\"gold wi wi-day-sunny\"></i> Sunny day",
> > 	],
> > ```
> 
> when did it stop working? with this PR?

yes

**Comment by sdetweil** [comment]
not sure, but this moved the span inside the newline loop. so u will have a span per part.. instead of one.  

and if split didn't, then you would lose the span

**Comment by rejas** [comment]
> > > This was one of the simplest modules that worked properly, now is not working with HTML compliments like:
> > > ```
> > > 	"day_sunny": [
> > > 		"<i class=\"gold wi wi-day-sunny\"></i> Sunny day",
> > > 	],
> > > ```
> > 
> > 
> > when did it stop working? with this PR?
> 
> yes

This doesnt work for me neithe ron the develop branch nor on the master branch. What version of MM2 are you using and how does your config look like in total (minus your secrets)?

**Comment by khassel** [comment]
adding the line `dom.window.fetch = corefetch;` in the following function of `tests/e2e/helpers/global-setup.js` seems to work:

```js
exports.getDocument = () => {
        return new Promise((resolve) => {
                const url = "http://" + (config.address || "localhost") + ":" + (config.port || "8080");
                jsdom.JSDOM.fromURL(url, { resources: "usable", runScripts: "dangerously" }).then((dom) => {
                        dom.window.name = "jsdom";
                        dom.window.fetch = corefetch;
                        dom.window.onload = () => {
                                global.document = dom.window.document;
                                resolve();
                        };
                });
        });
};
```

**Comment by rejas** [comment]
> adding the line `dom.window.fetch = corefetch;` in the following function of `tests/e2e/helpers/global-setup.js` seems to work: ```

That did indeed help, thx!

**Review by khassel — COMMENTED** [review]
I'm fine with this but I don't know if the other commenters are ...

**Comment by rejas** [comment]
> I'm fine with this but I don't know if the other commenters are ...

Cleaned up after @sdetweil's comment so that only one span is now generated again.

As for @BadAtheist I cannot reproduce that. Doesnt work on develop nor on the last master release. Without more information I cannot do anything here.

**Comment by BadAtheist** [comment]
> As for @BadAtheist I cannot reproduce that. Doesnt work on develop nor on the last master release. Without more information I cannot do anything here.

What more information? It's very simple, before the compliments worked with HTML format, after the change they don't work anymore. I will stick to the old version which works perfectly for me. Not every update is good if it is not properly thought out and tested, it is valid for any software. For me it's a bug. Good luck and stay healthy!

**Comment by rejas** [comment]
@BadAtheist sorry to hear that, but like I wrote: I couldnt get your config entry to work, neither with my changes of course, but neither with the develop branch nor with the last release.

Without more information from your side (for example what version are you currently running, what is your whole config) I cannot help you out and get this bug fixed.

**Pull request merged**
