### PR TITLE
HideLoading configuration option for News Feed

### PR DESCRIPTION
**Pull request by BeatIdo**
Proposal to hide News Feed module when feed is empty instead of showing loading status.

> Please send your pull requests the develop branch.
> Don't forget to add the change to CHANGELOG.md.

* Does the pull request solve a **related** issue?
* If so, can you reference the issue?
* What does the pull request accomplish? Use a list if needed.
* If it includes major visual changes please add screenshots.

### CODE REVIEW

**Comment by fewieden** [comment]
You don't have to create a new pr for changes, until the pr is closed or merged you can add changes automatically by pushing them to your branch.

Hint: Travis tells you have trailing spaces in line 170, but on github it looks like they are in line 167

**Comment by BeatIdo** [comment]
Thanks for the hints, will do !

**Comment by MichMich** [comment]
Could you fix the conflicts? Thanks!

**Comment by BeatIdo** [comment]
I see now I missed a feature from develop branch .. my bad, will do !

**Comment by BeatIdo** [comment]
As an old school developer I have to admit my inability to understand what Git expects to solve this conflict :(

**Comment by fewieden** [comment]
Try updating the develop branch on your machine and then merge it into your branch

**Comment by BeatIdo** [comment]
Ok that may come from the fact that I only edited/commited from GitHub not from a clone on my machine.   I coul create another PR from the develop branch from the beginning this time.

**Comment by BeatIdo** [comment]
I'll try again directly from develop branch

**Pull request closed without merging**
