### PR TITLE
Fix Documentation in  roundValue function

### PR DESCRIPTION
**Pull request by roramirez**

### CODE REVIEW

**Comment by fewieden** [comment]
Did you test this? parseFloat should create a number and toFixed just changes the amount of decimals, but its still a number?! not a string

**Comment by roramirez** [comment]
Yep. I'll include some tests.

**Comment by roramirez** [comment]
@fewieden The tests are ready. 

Did you see this?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed

**Comment by fewieden** [comment]
Thanks for the link, I really thought it's returning a number.

**Pull request merged**
