### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by B1gG**
> 1) Base your pull requests against the `develop` branch.
yep

> 2) Include these infos in the description:
This proposal is to rise the format in `dateFormat` when using `timeFormat` relative.
I started using the module, but I couldn't find the way to change the format on the dates from American style MM/DD/YYYY to anything else unless you use `absolute` as `timeFormat`

> 3) Please run `npm run lint:prettier` before submitting so that
> style issues are fixed.
done this time ;)

> 4) Don't forget to add an entry about your changes to
done

### CODE REVIEW

**Comment by MichMich** [comment]
@sdetweil since you put a lot of work in the calendar module. What's your view on this PR?

**Comment by sdetweil** [comment]
I've seen quite a number of users struggling to get the dates displayed how they want. I havent done much with the UI, but never understood why this was not possible already. I agree with this change

**Comment by MichMich** [comment]
Thanks for your PR @B1gG 
Thanks for your feedback @sdetweil!

**Comment by B1gG** [comment]
Thanks @MichMich @sdetweil, will also. Update the docs later today

**Comment by rejas** [comment]
You seemed to have added the lock files that were generated with a newer version of npm / node. This might lead to confusion for usersif they see the warning on the console. Could we revert those files?

**Comment by MichMich** [comment]
@rejas I always generate e new lock file upon release. So I don't think this is an issue.

**Comment by B1gG** [comment]
I saw that but thought you have tweak the gitignore if you don't want those. Perhaps is another little thing to do. 🙂

**Comment by rejas** [comment]
No, I would leave them in the repository, they are valuable for making sure that the dependencies are the same everywhere.

**Pull request merged**
