### PR TITLE
remove old weather modules

### PR DESCRIPTION
**Pull request by khassel**
`currentweather` and `weatherforecast` were deprecated with `v2.15` so I think we should remove them with the next release which is one year later.

This is still a draft to get opinions on whether this is okay.

### CODE REVIEW

**Comment by rejas** [comment]
> It might be an idea to temporary (one year again?) replace them with dummy modules which show an error/explanation.

Would definitly help those users that still run the modules

**Comment by khassel** [comment]
The 2 modules are now replaced with fake modules, see screenshot:

grafik

**Comment by MichMich** [comment]
Could you please make the docs link white. I have an unreasonable hate for purple and blue links. 

Other than that. Awesome work! :)

**Comment by rejas** [comment]
> Could you please make the docs link white. I have an unreasonable hate for purple and blue links.
> 
> Other than that. Awesome work! :)

I agree with both statements! :-)

**Review by rejas — APPROVED** [review]

**Comment by khassel** [comment]
done:

grafik

**Comment by MichMich** [comment]
Thanks. Great work.

**Pull request merged**
