### PR TITLE
replace system output with MagicMirror splash screen on boot

### PR DESCRIPTION
**Pull request by fewieden**
* Does the pull request solve a **related** issue?
No

* What does the pull request accomplish? Use a list if needed.
The newest release (2016-09-23) of Raspbian exchanged the desktop environment to PIXEL (Pi Improved Xwindows Enviroment Lightweight), with this you can now set a splash screen on boot instead of system messages.
As splash screen the color inverted header from github is used.

* If it includes major visual changes please add screenshots.
Before: https://i.imgur.com/2B0bSS5.png
After: https://i.imgur.com/G9RnZDo.png

### CODE REVIEW

**Comment by MichMich** [comment]
Nice. Maybe we should add a "booting" message to the splash image?

**Comment by fewieden** [comment]
@paviro maybe can use his skills to create a beautiful image

**Comment by Jopyth** [comment]
Is it going to be possible to still show the boot log somewhere (maybe an option to add it at least)?

**Comment by MichMich** [comment]
Give me one second, I'll create a booting screen ...

**Comment by paviro** [comment]
Me? I am not a graphics designer 😅

**Comment by MichMich** [comment]
How about this? 
splash

**Comment by paviro** [comment]
Why do you use a white background? Wouldn't black look better?

**Comment by MichMich** [comment]
It's transparent. It will be loaded on a black background ;)

**Comment by paviro** [comment]
I see 😅 but isn't the nearly black font then a bit too dark?

**Comment by MichMich** [comment]
Seems perfectly readable here ... ?

**Comment by paviro** [comment]
Well the I haven't said anything 😅 just saw it in my mail application :)

**Comment by MichMich** [comment]
Merged!

**Comment by XoniBlue** [comment]
> Guys please, after updating raspberry OS this custom splash screen reverted to stock raspbian splash screen, I tried to update MM again but still have stock splash screen. is there way to change it to MM one ? thanks

do you still need help with this? your going to need to copy the splashscreen folder into /usr/sharl/plymouth/themes/
rename it what youd like then in terminal type plymouth-set-default-theme "your-folder-name" and that should effectively change it for you.

**Pull request merged**
