### PR TITLE
Clean Up the Contributing Documentation and Process: An Opera

### PR DESCRIPTION
**Pull request by nhubbard**
> Please send your PR's the develop branch. 
> Don't forget to add the change to changelog.md.

* Does the pull request solve a **related** issue? [yes | no] no
* If so, can you reference the issue? No.
* What does the pull request accomplish? (please list)
   * Update the .github templates and information with more modern information.
   * Update the Gruntfile with a more functional StyleLint implementation.
* If it includes major visual changes please add screenshots.

### CODE REVIEW

**Comment by nhubbard** [comment]
My ambitions messed up. I must have made a syntax error... the grunt config is stalling on travis.

**Comment by MichMich** [comment]
Still conflicts. :(

**Comment by MichMich** [comment]
Is it possible to send one PR after all the work is done? I don't want to accidentally merge a half finished modification and all the mails I get don't improve my workflow either ... 😂

**Comment by nhubbard** [comment]
Oops... I didn't anticipate that. Sorry. But I will fix this by closing this PR and resubmitting it.

**Comment by MichMich** [comment]
😁👍

**Pull request closed without merging**
