### PR TITLE
Issue #2228 - Default Alert Module does not hide black overlay when alert is dismissed manually (by clicking on it)

### PR DESCRIPTION
**Pull request by ashishtank**
Solved Issue #2228

### CODE REVIEW

**Comment by rejas** [comment]
Your branch seems to be behind the develo branch since there are non-issue related commits in here.

**Comment by ashishtank** [comment]
@rejas Thanks for the review, I did git pull and also verified that it is not behind the develop branch and can merge with out conflict. It might be showing you non-issue related commits because my previous PR is still not merged. This PR have two commits 7c886e1 and 9ca9ab2.

Let me know if I need to take any action. ( I am new with git :) )

**Comment by rejas** [comment]
Yeah, somehow your develop branch is not the same as MichMichs. Probalby because of your unmerged PR like you mentioned.  

Not sure though how to fix that elegantly. So I would propose you create a new bracnh from MichMichs develop branch and put your alert-commits there and resubmit your PR.

As a rule of thumb it is always good to have seperate branches for each PR and have those not build upon each other. But thanks for your work! We will get it in here :-)

**Comment by ashishtank** [comment]
@rejas Do I need to create new fork ? I am not sure if that is possible as I already have forked his repo.

**Comment by rejas** [comment]
A new fork is not necessary. But how to get your develop branch back in sync with MichMichs could be tricky to do via GithubComments :-) Are you using git on the console or a GUI interface for it?

**Comment by ashishtank** [comment]
@rejas I am using git console and also have git GUI. 

image

I checked the previous PR and it only shows commits for that PR. can you check if that one is okay ? and if it is and if you merge it with MichMich's dev then I think they will not display over here. 
Below in previous PR it only shows commits of that PR. Would be great if you can guide me about the issue and resolution.


image

**Comment by rejas** [comment]
Sorry for the silence, lots of work and kids stuff :-) Anyway, I can take your PR and prepare a new one from it in my fork, are you okay with that? All credits will of course go to you.

**Comment by rejas** [comment]
As for GUI I can recommend GitKraken (free with some restrictions if you want to work with private repos). There I have an overview like this which makes it IMO easy to see where the branches go off:
﻿
Bildschirmfoto 2020-12-17 um 08 18 29

**Comment by ashishtank** [comment]
@rejas No Problem, you can create pull request. I now know why this issue is occurring. it is because my previous PR is still not merged and changes are already in my develop branch and i have create Issue2228 branch from my develop branch where my previous changes are committed. Ideally I should not touch the develop branch and should always create new branch for each feature/issue. Will take care of it and I will close the PR of 2228.

**Pull request closed without merging**
