### PR TITLE
Cleanup test directory

### PR DESCRIPTION
**Pull request by rejas**
Moves files around and renames some so that the structure is cleaner and more consistent

### CODE REVIEW

**Review by khassel — APPROVED** [review]

**Comment by khassel** [comment]
> so new rule:
>
>  -  never merge your own PRs
>  -  never merge without someone else having approved?

so I'm not allowed to merge this, so may @sdetweil can press the button?

**Comment by rejas** [comment]
> so I'm not allowed to merge this, so may @sdetweil can press the button?

well, we can do it in this "threeway" round, but I'd be okay with "the one who approves it can also merge it".

**Comment by khassel** [comment]
> well, we can do it in this "threeway" round, but I'd be okay with "the one who approves it can also merge it".

o.k. for me, so new rules:
- never merge your own PRs
- never merge without at least one approval

**Comment by sdetweil** [comment]
sounds good

**Comment by rejas** [comment]
mh... is there any place in the project to write this down for future generations? :-)

**Comment by khassel** [comment]
and a place to discuss such things at a central point?

**Comment by khassel** [comment]
> mh... is there any place in the project to write this down for future generations? :-)

we could create a `Collaborator.md` in the main dir of the repo.

> and a place to discuss such things at a central point?

we could create an issue `collaborator talk` and close this directly so it is a little hidden.

Better ideas welcome ...

**Comment by rejas** [comment]
+1 for the `Collaborator.md`

Discussion: Maybe it spossible to have a closed / hidden topic in the MM forum?

**Comment by sdetweil** [comment]
we could certainly have a collaborator only channel on discord..

**Comment by sdetweil** [comment]
I opened a collaboration channel u der MagicMirror

give me your IDs and I will add you

**Comment by khassel** [comment]
my id `karsten13#4548`

**Comment by sdetweil** [comment]
done

under other channels

**Comment by rejas** [comment]
HansAlbern#4892

**Comment by sdetweil** [comment]
done

**Comment by rejas** [comment]
thx, deleted my id post for privacy reasons :-)

**Comment by sdetweil** [comment]
deleted Karsten's too

**Comment by sdetweil** [comment]
and from the github streamed activity on discord

**Pull request merged**
