### PR TITLE
Weather - forecast update day of week

### PR DESCRIPTION
**Pull request by flopp999**
change name of day to today and tomorrow
added text to changelog.md

### CODE REVIEW

**Comment by flopp999** [comment]
I may have done a mistake here
This PR is based on Develop but the PR are against Master

**Comment by rejas** [comment]
I assume this can be closed since the other one is the one you want to have merged?

**Comment by flopp999** [comment]
> I assume this can be closed since the other one is the one you want to have merged?

I don't know if the PR should be against Master or Develop. #2158 is against Develop

**Comment by rejas** [comment]
Always against develop :-)

**Comment by flopp999** [comment]
> Always against develop :-)

OK thank you, have now Close this PR

**Pull request closed without merging**
