### PR TITLE
Updated raspberry.sh installer script to save apt-get log output to a file 

### PR DESCRIPTION
**Pull request by cherifya**
- Updated raspberry.sh installer script to save apt-get log output to a file that can be tailed
- Fixed an issue where the raspberry.sh installer script can get stuck when there are packages that need to be upgraded

### CODE REVIEW

**Comment by MichMich** [comment]
Please add the changelog entries to the 2.11 release. The 2.10 release is already published. Thanks!

**Comment by sdetweil** [comment]
why the separate log entry?  the  update=$(sudo apt get ... 2>&1)  captures all the stdout and error content,
and then the echo $update >>$logfile should save it to the existing log

**Comment by sdetweil** [comment]
i added the --assume-yes to the upgrade.. thanks

**Comment by sdetweil** [comment]
this fix (--update=yes) is in the scripts repo

**Comment by MichMich** [comment]
Closed since we are moving this script.

**Pull request closed without merging**
