### PR TITLE
Add custom switches for electron mainWindow

### PR DESCRIPTION
**Pull request by eouia**
I need some custom electron switches for my purpose. (e.g., Desktop background playing)

This feature enables adding custom switches on Electron starts by a user.

You can add switches in `config.js` like;
```js
electronSwitches: ['enable-transparent-visuals'],
```

### CODE REVIEW

**Comment by MichMich** [comment]
What's the difference between this and the already implemented `electronOptions` config option?

**Comment by eouia** [comment]
@MichMich
This is not about `electronOption`. It is about `switch`.
With `electronOption` (https://www.electronjs.org/docs/latest/api/browser-window#new-browserwindowoptions), you can control the window created by electron, but not the electron app itself.
`switch (commandLine.switch)` is rather for App(and some node features) itself.  (https://www.electronjs.org/docs/latest/api/command-line-switches) These could not be achieved with `electronOption`

**Comment by MichMich** [comment]
Ok. If you can fix the conflict so I can merge it. Also, please create a PR in the docs repo (and if possible reference the PR in this PR). 

Thanks!

**Comment by eouia** [comment]
Thanks. I'll do it in a few hours.
Anyway, with this feature, your MM could be located as Desktop wallpaper on the Mac or Linux machine. (That's my purpose of this PR. :D )

**Comment by MichMich** [comment]
Cool! Thanks for your PR!

**Pull request merged**
