### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by yo-less**
Just a minor change on README.md, just noted the inconsistency.

Fixed inconsistencies in tag removal instructions.

### CODE REVIEW

**Comment by MichMich** [comment]
Thanks! Could you also update the changelog?

**Comment by yo-less** [comment]
Just to make sure I get your request, you mean the CHANGELOG.md in the main folder of the development branch?

**Comment by MichMich** [comment]
Yes! :) So that other know what you've added (when we release a new version ...)

**Comment by yo-less** [comment]
Will do. Thanks for the quick reply, I'm very new to all this :smile:

**Pull request merged**
