### PR TITLE
Use `html-to-text` instead of regex for transform description

### PR DESCRIPTION
**Pull request by bugsounet**
I try to use only `html-to-text` library

it's will solve issue #3235 

@rejas, @sdetweil, @khassel: Can you do tests with your own feeds?

Thanks for feedbacks

### CODE REVIEW

**Comment by khassel** [comment]
> Can you do tests with your own feeds?

tested, LGTM

**Comment by bugsounet** [comment]
(Test in develop branch I have the same problem with time zone)

**Review by rejas — APPROVED** [review]
Seems to work, so get it ready to merge :-)

**Comment by bugsounet** [comment]
waiting #3265 and I will clean this part of code

**Comment by bugsounet** [comment]
> Seems to work, so get it ready to merge :-)

it's green :-)

**Pull request merged**
