### PR TITLE
Fixes for Hebrew translation

### PR DESCRIPTION
**Pull request by adi-miller**
> Please send your pull requests the develop branch.
> Don't forget to add the change to CHANGELOG.md.

**Note**: Sometimes the development moves very fast. It is highly
recommended that you update your branch of `develop` before creating a
pull request to send us your changes. This makes everyone's lives
easier (including yours) and helps us out on the development team.
Thanks!

* Does the pull request solve a **related** issue?
* If so, can you reference the issue?
* What does the pull request accomplish? Use a list if needed.
* If it includes major visual changes please add screenshots.

### CODE REVIEW

**Comment by adi-miller** [comment]
Build failure doesn't seem related to this change.

**Comment by roramirez** [comment]
Hi @adi-miller !

This change include another files must not include for this Pull Request. Your contribution seams good for me but only should include in the commit for this PR the changes for file
 - translations/translations.js 
 - translations/he.json
 
And the entry for the  `CHANGELOG.md`

Should create a new branch from `develop` with the last changes. If you need more help about this let me know.

**Comment by adi-miller** [comment]
Sorry for the mess. I just submitted a new PR.

**Comment by roramirez** [comment]
Don't worries about it. You can try again. Thanks for your contribution in #1895

**Pull request closed without merging**
