### PR TITLE
Weather refactoring

### PR DESCRIPTION
**Pull request by fewieden**
- Fixed openweathermap
- Fixed darksky
- Implemented forecast for both
- added indoor values
- documentation
- ...

current
forecast

### CODE REVIEW

**Comment by fewieden** [comment]
Some things are still missing:
- feels like temperature
- openweathermap forecast for newer api keys (grouping 3h forecasts)
- darksky unit handling
- some more config options from the previous modules

But I would categorize those more as improvements.

**Comment by fewieden** [comment]
The build on travis only failed for 50%. Nodejs can't handle `class` and in the other one the before hooks timed out as seen previously

**Comment by MichMich** [comment]
SUPER AWESOME WORK! 🎉

If we can find a way to make travis happy, I can merge it, and then merge it into develop so we can shift the module as *EXPERIMENTAL*, which will hopefully increase traction in the development. 

I'll be releasing the next MM version January 1st, so lets try to get it included in this version! :)

**Comment by fewieden** [comment]
@MichMich I merged current develop branch (has an updated travis config) into the weather branch. It passed now.

**Comment by MichMich** [comment]
Great work! Ill make sure to merge it into dev before releasing a new version.

**Pull request merged**
