### PR TITLE
Added ToC

### PR DESCRIPTION
**Pull request by E3V3A**
Added ToC
Todo: Link ToC items to headers

### CODE REVIEW

**Comment by MichMich** [comment]
Your PR seems to have a conflict. Can you rebase your PR?

**Comment by E3V3A** [comment]
I was just looking. I have no idea what is the problem. 
Tell me what I need to do and I'll try to fix.

**Comment by MichMich** [comment]
Your update is based on an older version of the Readme. So it is missing a previously merged update. 
Pull the laatst develop branch and reapply your update. 🤘🏻

**Comment by E3V3A** [comment]
Aah ok.

**Comment by E3V3A** [comment]
Made a new one

**Pull request closed without merging**
