### PR TITLE
Remove ESLint

### PR DESCRIPTION
**Pull request by nhubbard**
ESLint wouldn't stop complaining about how my indentation was wrong even though I set it to tabs. So I removed it.

### CODE REVIEW

**Comment by nhubbard** [comment]
I am considering shrinkwrapping our own version of the ical module, because the creator has not got back to me on a vulnerability I reported to him with a fix.

**Comment by nhubbard** [comment]
Please disregard the previous comment. Any thoughts on the remainder of the pull request, @MichMich?

**Comment by MichMich** [comment]
Will look into it tomorrow. Was at an event all day today. I did notice you added a config.js in this PR. That should not be the case.

**Comment by MichMich** [comment]
@nhubbard, thanks for the pull request. I see you used the sample config as a default config. I prefer to let a user see the "no config" message first to guide them thru the process. Could you resubmit this pull request without the config changes (both the config file as well as the .gitignore change).

Thanks!

**Pull request closed without merging**
