### PR TITLE
Refactor calendar fetcher

### PR DESCRIPTION
**Pull request by rejas**
Inspired by @sdetweil comment here https://github.com/MichMich/MagicMirror/pull/2206#issuecomment-733695260
I refactored the calendar fetcher a little.

Most notably I moved all functions that were used into a util class so that I could see which ones use which parameters, especially the filter function

So now we can
- move filter function somewhere else (any recommendations?)
- add tests for the util functions s
- ???

Since this is a draft I am open to your comments on how we can imporve the calendar fetcher even more.

### CODE REVIEW

**Comment by sdetweil** [comment]
awesome  but i don't know that these should be moved out of the calendar module. I don't see another module using them.(haven't looked at the code yet)

I think we should hold this til next cycle w only 6 days to go.

**Comment by rejas** [comment]
> I think we should hold this til next cycle w only 6 days to go.

Definitly :-) This draft is just here to get some feedback before moving on.

**Comment by rejas** [comment]
> awesome but i don't know that these should be moved out of the calendar module. I don't see another module using them.(haven't looked at the code yet)

I dont intend to move any code out of the calendar module. Just wanted to clear it up a little so we can move around inside the calendar module. 

Plus we can write unit tests for those functions now, if somebody finds the time for that :-D

**Comment by sdetweil** [comment]
ok, sorry, util class to me meant available for all/any module. I got what u meant. have not reviewed yet

**Comment by MichMich** [comment]
Do you let me know when this is ready to be merged?

**Comment by rejas** [comment]
I will.
Though it is already mergable, I want to find some time this week to chip a little more in it, if you dont mind?

**Comment by MichMich** [comment]
Of course! Take your time. We have three months tell the next release. 😅

**Comment by sdetweil** [comment]
got a fun one if u want to look at it. user marked cal as 'busy' info only. , which generates an ics with no RRULE, just events, with recurranceID

but fetcher is looking for the rrule. 
[large-trouble1.txt](https://github.com/MichMich/MagicMirror/files/5771121/large-trouble1.txt)

u can repeat this on your cal by marking share and select only busy 
[parsed-results.txt](https://github.com/MichMich/MagicMirror/files/5771133/parsed-results.txt)

**Comment by rejas** [comment]
> got a fun one if u want to look at it. user marked cal as 'busy' info only. , which generates an ics with no RRULE, just events, with recurranceID
> 
> but fetcher is looking for the rrule.
> [large-trouble1.txt](https://github.com/MichMich/MagicMirror/files/5771121/large-trouble1.txt)
> 
> u can repeat this on your cal by marking share and select only busy
> [parsed-results.txt](https://github.com/MichMich/MagicMirror/files/5771133/parsed-results.txt)

not sure if I undrstand correctly. Is that a buggy calendar or what should I look for exactly?

**Comment by sdetweil** [comment]
[calendarfetcher.txt](https://github.com/MichMich/MagicMirror/files/5777275/calendarfetcher.txt)
this works..

the existing  code does   
if rrule, then get dates in range, 
   if recurrences, make sure to dedup any dates already discovered
else
   single date

but we have another case, 

if no rrule AND recurrences
   loop thru recurrences, save dates in start/stop time window
   process and add dates
95%  dup of the rrule path

new code starts on line 338..    i figured u were refactoring, and would like to see this

**Comment by rejas** [comment]
With little time I have I think this is in enough good shape to be merged. Mostly moved functions around, maybe after april I can add more tests in a new PR....

**Comment by MichMich** [comment]
Whoops... would love to merge. But there are some conflicts. Can you fix these?

**Comment by rejas** [comment]
Of course. Later tonight, currently the Family Skype Session Blocks my PC :-)

**Comment by MichMich** [comment]
Priorities, dude ... priorities. 😂

**Comment by rejas** [comment]
All cleaned up @MichMich

**Comment by MichMich** [comment]
Thanks for your hard work!

**Pull request merged**
