### PR TITLE
Update italian translation

### PR DESCRIPTION
**Pull request by secuflag**

### CODE REVIEW

**Comment by rejas** [comment]
hi @secuflag could you fix the merge conflicts in your PR so it can get merged? Maybe also change the entry to an "- Update italian translation" since we dont need all the details in there ;-) Thx in advance

**Comment by rejas** [comment]
Looks good to me, why did you close the PR @secuflag ?

**Comment by secuflag** [comment]
Sorry, I made a mess.
I'll send a new PR again later.

**Comment by rejas** [comment]
Well, I cant tell if the translation themselves are a mess but the PR looked fine. But do as you think is best.

**Pull request closed without merging**
