### PR TITLE
Hack fix issue #1017

### PR DESCRIPTION
**Pull request by roramirez**

### CODE REVIEW

**Comment by nhubbard** [comment]
@roramirez I wonder what is causing the tests to fail on three out of four platforms... none of them are related to the weather module. Maybe there are errors in the console that we can't see.

**Comment by roramirez** [comment]
Yes, this is something we need to fix. Its random cases

**Comment by kmcrawford** [comment]
I'm not sure this is a fix. That API returns data in 3 hour increments vs a daily.  So you would have to calculate the low and high across all 3 hour increments for a day to see the daily high & low.

**Comment by nhubbard** [comment]
@kmcrawford Send me an email at nhubbard@users.noreply.github.com with your email. I will send you an API key that was grandfathered into daily endpoint access.

**Comment by MichMich** [comment]
What does this fix do? I don't understand it's purpose.

**Comment by MichMich** [comment]
Hopefully I have time tomorrow to start working on a new weather integration to overcome the API issue. Before I do: did anyone already started working on this?
My plan is to make one new module that replaces both the current weather as well as the forecast module. It will have multiple sources (user can choose).

**Comment by kmcrawford** [comment]
I haven't yet started on it.  But your approach would be the same approach I would do.  These apis are pretty simple and straightforward.

**Comment by nhubbard** [comment]
@MichMich Which service would you plan on using? Dark Sky is free unless you make 1,000 calls in a day. I've never used Apixu, but it sounds just as promising. In a perfect world, we would make it pluggable (i.e. bring your own weather provider) but that adds lots of complexity.

**Comment by MichMich** [comment]
@nhubbard. Thats sort of the plan: multiple providers. More can be added in the future. 

If you like to contribute to the discussion, Please join Slack.

**Comment by kmcrawford** [comment]
What is the Slack channel?

I was bored in a meeting to made the changes in a new branch.

https://github.com/kmcrawford/MagicMirror/tree/new-api

**Comment by MichMich** [comment]
https://forum.magicmirror.builders/topic/4759/magicmirror-in-slack-we-ll-see-you-there

**Comment by roramirez** [comment]
@MichMich The purpose if the openweather api return an  401 code when you use a  new account for forecast daily will to  change the other endpoint where is work.

**Comment by MichMich** [comment]
FYI: https://github.com/MichMich/MagicMirror/commit/ef172592b8b1657a92ceea5a56b6b0629abf6046

**Comment by roramirez** [comment]
Look good!. But If we'll use forecast I would maintain the behavior included in this change.

**Comment by MichMich** [comment]
@kmcrawford I just pushed a fix that should solve the three hour increment. Could you give it a try?

**Pull request merged**
