### PR TITLE
Fix problems with non latin fonds caused by updating to fontsource

### LINKED ISSUE #2835: Bad font for non latin users
## Fonts bug in MagicMirror

**Platform**: MagicMirrorOS on Raspberry Pi 2 .
**MagicMirror² Version**: 2.19.0

**Description**:

In this update fonts package was changed from `roboto-fontface-bower` to `fontsource` (2dcf55ea89f752390554d655ee819148c07e4fbc).
CSS file `roboto.css` uses only `latin` subset for loading woff files. It is not fair = fonts must consist all world chars.

**Way to fix**:

Change `roboto-latin-100-normal.woff2` to `roboto-all-100-normal.woff2` and etc.

**Expected Results**: Fonts are still great with non US characters.
**Actual Results**: Fonts are ugly. Need to add custom `@font-face` from Google.

### PR DESCRIPTION
**Pull request by khassel**
fixes #2835

### CODE REVIEW

**Comment by khassel** [comment]
Need feedback to this one. I had to substitue `-latin-` with `-all-` for fixing the non latin fonds.

But there are no `woff2` files for `-all-` so I removed the links to `woff2`. Reading about this `woff2` seems to be the preferred format. Any better ideas?

**Comment by MichMich** [comment]
As long as it's supported by electron it seems fine by me.

**Comment by khassel** [comment]
tested this with electron, but must be tested anyway by non-latin users ...

**Comment by rejas** [comment]
During standard web-developmet, woff2 would indeed be preferred due to size improvements. But I guess here we can ignore that :-)

**Review by rejas — APPROVED** [review]

**Review by nikow13 — APPROVED** [review]

**Comment by MichMich** [comment]
I merged this to see if this will cause issues. We can always revert if someone runs into issues.

**Pull request merged**
