### PR TITLE
V2 beta IT translation

### PR DESCRIPTION
**Pull request by iosonopersia**
Italian translation added to Alert and Calendar default modules in V2 Beta branch

### CODE REVIEW

**Comment by MichMich** [comment]
Thanks for your hard work. Did you pull the latest version before you did this translation? There is now a General translation file for the default module.

**Comment by iosonopersia** [comment]
Oh, I'm sorry, I've noticed it only now. I'm a new user on GitHub, I'm trying to learn as fast as possible. Give me some minutes

**Comment by MichMich** [comment]
No worries! Take your time!

**Comment by iosonopersia** [comment]
I'm making a new pull request, hoping it'll work

**Pull request closed without merging**
