### PR TITLE
update fetcher for full day events east of UTC start time and duration

### LINKED ISSUE #2200: Full Day calendar Events east of UTC start time incorrect with latest node-ical (12.3)
the start time  should be 00:00:00 (local time) , but for east of UTC they are incorrect (by the TZ offset),

### PR DESCRIPTION
**Pull request by sdetweil**
fixes #2200 

change variable names in getCorrection() to make more understandable

### CODE REVIEW

**Comment by sdetweil** [comment]
i don't understand why I have all these changes.. I pulled from develop to my local, added my two file changes, and then committed, and pushed..   CHANGELOG.md and calendarfetcher.js

**Comment by rejas** [comment]
You created the PR on GitHub when you were finished?

**Comment by sdetweil** [comment]
Yes, like always. New branch to develop

**Comment by rejas** [comment]
But the sub-headline here on github says: 

"sdetweil wants to merge 90 commits into MichMich:master from sdetweil:cal-again"

So maybe you misclicked when creating it here.

**Comment by sdetweil** [comment]
yes, that was the question I asked... I will redo..

**Pull request closed without merging**
