### PR TITLE
ADD fixme wanted where the day if sunday for test number of week

### PR DESCRIPTION
**Pull request by roramirez**
The test  "shows week with correct number of week of year" to match does not work on sunday. This Pull Request comment this test and add comment there labeled FIXME

### CODE REVIEW

**Comment by roramirez** [comment]
Hi @johanhammar If you are interesting... this test does not work in Sunday.

**Comment by johanhammar** [comment]
Hi @roramirez 

I think it would be better if the week could be mocked. That would minimize errors like "does not work on sundays". Any ideas on how to mock the week?

**Comment by roramirez** [comment]
The problem I can see is  the current-week-number start Week at monday and moment in Sunday.

**Comment by fewieden** [comment]
Should we use moment for week number in production then? I think most users rely on monday as week start.

**Pull request merged**
