### PR TITLE
Add date compliments

### PR DESCRIPTION
**Pull request by rejas**
This adds another type of compliment to the module: date specifics.

So know you can add a compliment on a special day, like for a anniversary or birthday.

Default compliment for this are:

```
			date: [
				["03-14", "Happy birthday, Albert Einstein!"],
				["12-10", "Happy birthday, Ada Lovelace!"]
			],
```

As you can see the format is ["month-day", "text"]. A little too late for using it on my girlfriends birthday, but that day will come again :-D

### CODE REVIEW

**Comment by hangorazvan** [comment]
another simple solution that working:

```
	compliments: {
			2512 : [
				"Happy Christmas!",
			],
	}
.....
	complimentArray: function() {
		var date = moment().format('DDMM');

....  // rest of the code

		if (date in this.config.compliments) {
			compliments.push.apply(compliments, this.config.compliments[date]);
		}

		return compliments;
},
```

**Comment by rejas** [comment]
I like your code @hangorazvan cleaner and simpler, will refactor the PR into it.

**Comment by rejas** [comment]
Tried to add some test for the feature @hangorazvan but I cant get it to pass. Any idea why that might be?

**Comment by hangorazvan** [comment]
I do not know the reason for these tests or reason of this failure.
For me this code works like charm and I am happy with that. :)

**Comment by rejas** [comment]
Maybe @MichMich has an idea on why the test fails?
I could live without a test for this feature (but maybe add an TODO to the code) but the last word has @MichMich  :-)

**Comment by hangorazvan** [comment]
Why you complicate things? Like you said, the code is clean and simple...

**Comment by rejas** [comment]
Where are things complicated? Do you mean the tests?

**Comment by hangorazvan** [comment]
> Where are things complicated? Do you mean the tests?

Yes. What are test for? If it's working is not the best test?

**Comment by rejas** [comment]
Tests shouldnt be called "complications" :-)  Tests are there for finding out automatically when other stuff breaks your stuff... Just because it works now doesnt mean it runs after the next merge too.

**Comment by rejas** [comment]
Still hoping for @MichMich on writing his opinion in on this PR....

**Comment by hangorazvan** [comment]
> Still hoping for @MichMich on writing his opinion in on this PR....

OK, I understand. I use three instances of MM2 develop version with diferent 3rd party modules and works smothly

**Comment by MichMich** [comment]
I like the idea!

It might be an idea to change the date format to allow wildcards:
```
compliments: {
    ‘XXXX-01-01’: ‘Happy new year’,
    ‘2020-03-27’: ‘Happy 37th Birthday, Michael’,
    ‘XXXX-XX-14’: ‘Have a great 14th day of the month!’
}
```

**Comment by rejas** [comment]
Good idea, @MichMich 
Updated my PR accordingly, using . as the wildcard since that is easier to use directly in a RegExp

Still, no idea why my test fails although I mock the date. Do you have an idea?

**Comment by MichMich** [comment]
Maybe use a regex to replace all non-digits to the wildcard? 

I’ll look into the test one of the coming evenings.

**Comment by rejas** [comment]
I have to say I find the dots best visually to signal that its an "empty" field that can be filled with whatever the ... you want :-) But I'll change it if you want...
Thanks for looking into the test, hope all is well at your place!

**Pull request merged**
