### PR TITLE
Translations issue

### PR DESCRIPTION
**Pull request by MrHarcombe**
Regarding issue #388, I think this code handles the various permutations of translations/fallback translations and duplicate files.

If the `else if` isn't used then when the translationFile  and translationsFallbackFile are the same, then MM actually loads only the translationsFallbackFile which can cause issues later on in modules that rely on having a translation entry present, and not a tranlsationFallback entry.

### CODE REVIEW

**Comment by MrHarcombe** [comment]
Hm, this isn't how I'd hoped it would all go - being a bit of a git novice is a pain. I just wanted to fork your "develop" branch and then submit my one change...

**Comment by MichMich** [comment]
Your Git work is ok. I received just the desired change. But the change itself does not do what needs to be done. More info here: https://github.com/MichMich/MagicMirror/commit/18ae08de8f90f84dc168c9e71c3fbdf877a8a644#commitcomment-18511041

**Comment by MichMich** [comment]
No, that's all be taken care of by the translator. Are you still experiencing issues? If so, please describe the issue in the original issue-post: https://github.com/MichMich/MagicMirror/issues/388

Thanks!

**Comment by MrHarcombe** [comment]
It's all good - I think the author of the MMM-Voice-Control module wasn't using the singleton Translator correctly, as he was directly accessing Translator.translations instead of going through Translator.translate. This, of course, meant that in our case where the module loaded only the fallback translation then their code failed to retrieve the necessary values.

I'm going to put a PR against their module, once I'm sure I've got it working properly :)

**Comment by MichMich** [comment]
Awesome! Thanks for your contribution!

**Pull request closed without merging**
