### PR TITLE
Very minor README spelling error fix

### PR DESCRIPTION
**Pull request by dgpshiva**
> Please send your pull requests the develop branch.
> Don't forget to add the change to CHANGELOG.md.

**Note**: Sometimes the development moves very fast. It is highly
recommended that you update your branch of `develop` before creating a
pull request to send us your changes. This makes everyone's lives
easier (including yours) and helps us out on the development team.
Thanks!

* Does the pull request solve a **related** issue?
* If so, can you reference the issue?
* What does the pull request accomplish? Use a list if needed.
* If it includes major visual changes please add screenshots.

### CODE REVIEW

**Comment by sdetweil** [comment]
looks like this failed because the spectron version used in testing is downlevel

from https://www.npmjs.com/package/spectron   
electron v3 needs spectron v5.x.x
the master branch uses spectron 3.8.0

**Comment by MichMich** [comment]
@sdetweil All tests currently fail. @roramirez will take a look at it as soon as ge got time.

**Comment by MichMich** [comment]
@dgpshiva Thanks for your contribution!

**Comment by roramirez** [comment]
> @sdetweil All tests currently fail. @roramirez will take a look at it as soon as ge got time.

#1849

**Pull request merged**
