### PR TITLE
Russian translations2

### PR DESCRIPTION
**Pull request by morozgrafix**
Redo of the PR #598

**Added:**
- Russian Translations

**Fixed:**
- corrected .gitignore rules for default modules

(Reasoning behind change: when I added translation for `alert` module `git add` was telling me that `.gitignore` rule excludes files and folders under `modules/default`)

I also noticed that `.gitignore:56` has following declaration:

```
# Don't ignore the node_helper nore module.
!/modules/node_helper
!/modules/node_helper/**
```
but I don't think this directory structure exists today (also there is a small typo)

### CODE REVIEW

**Comment by morozgrafix** [comment]
@nhubbard & @roramirez I think this one is cleaner. I had to resolve CHANGELOG.md conflict resulting in extra commit. Does this look ok to you? I will be closing #598 now. 🙇

**Comment by MichMich** [comment]
Don't think the git gone part is completely correct. Ill fix this using a seperate PR. Could you please remove this from the PR so I can merge the translation? Thanks! :)

**Comment by morozgrafix** [comment]
@MichMich I removed everything related to `.gitignore` changes that I possibly screwed up, leaving only Russian translations. Thanks.

**Comment by MichMich** [comment]
Thanks!

**Pull request merged**
