### PR TITLE
Added optional "dev" parameter to start with dev tools

### PR DESCRIPTION
**Pull request by alexyak**
> Please send your PR's the develop branch. 
> Don't forget to add the change to changelog.md.

* Does the pull request solve a **related** issue? [yes | no]
* If so, can you reference the issue?
* What does the pull request accomplish? (please list)
* If it includes major visual changes please add screenshots.

### CODE REVIEW

**Comment by MichMich** [comment]
Thanks. Could you please also add it to the changelog?

**Comment by alexyak** [comment]
Done

**Comment by MichMich** [comment]
Could you add that chagelog to this commit?

**Comment by MichMich** [comment]
Aslo, You might want to add some info about this feature to the readme file.

**Comment by alexyak** [comment]
Sorry I am doing this over the github's web site and can't figure out how to one commit to another :)

**Pull request closed without merging**
