### PR TITLE
Add possibility to fetch calendars through socket notifications

### PR DESCRIPTION
**Pull request by krukle**
Hello and thank you for wanting to contribute to the MagicMirror² project

**Please make sure that you have followed these 4 rules before submitting your Pull Request:**

> 1. Base your pull requests against the `develop` branch.
>
> 2. Include these infos in the description:
>
> - Does the pull request solve a **related** issue?
> - If so, can you reference the issue like this `Fixes #<issue_number>`?
> - What does the pull request accomplish? Use a list if needed.
> - If it includes major visual changes please add screenshots.
>
> 3. Please run `npm run lint:prettier` before submitting so that
>    style issues are fixed.
>
> 4. Don't forget to add an entry about your changes to
>    the CHANGELOG.md file.

**Note**: Sometimes the development moves very fast. It is highly
recommended that you update your branch of `develop` before creating a
pull request to send us your changes. This makes everyone's lives
easier (including yours) and helps us out on the development team.

Thanks again and have a nice day!

This pull request adds the possibility to fetch calendars through socket notifications.
This enables development on projects like for example [mycroft](https://mycroft.ai/). 

[An example](https://github.com/krukle/calendar-event-skill/blob/74d4864a84fd2d626aa49039aa932e7ae36cb3ee/__init__.py#L235) being where one would create a calendar event through the voice assistant, for the voice assistant to then call on the calendars to fetch through socket notifications:

```
self.calendar.add_component(event)
with self.file_system.open(self.CAL_PATH, "wb") as f:
    f.write(self.calendar.to_ical())
      
self.speak_dialog('event.created', dialog_data)
      
# Alert MM calendar that there's been an update.
self.bus.emit(Message("RELAY:calendar:FETCH_CALENDAR", {"url": "http://localhost:8080/" + str(self.CAL_MM_REL_PATH)}))
```

This can all be easily implemented with the MM module [MMM-mycroft-bridge](https://github.com/oenstrom/MMM-mycroft-bridge) created by @oenstrom.

The changes made in this pull request do not affect users that are not interested in using socket notifications to communicate with MagicMirror.

### CODE REVIEW

**Comment by sdetweil** [comment]
I don't understand the value.  I create cal events thru voice all the time, and they show when the cal refreshes, same as when I do it thru my phone, or PC. 

it's unlikely you created a cal event that will occur in the next 10 minutes(default refresh time), except to test.

**Comment by MichMich** [comment]
Thanks! Sorry response. Was enjoying a sunny holiday. :)

Would you mind fixing the merge conflicts?

**Comment by MichMich** [comment]
In addition to this PR, would you mind creating a PR on https://github.com/MichMich/MagicMirror-Documentation as well? Thanks!

**Comment by MichMich** [comment]
Unfortunately the automated tests are failing. Any idea if this is caused by your changes?

**Comment by krukle** [comment]
Sorry that's my bad. Python habits came into play. Fixed what it complained about!

**Pull request merged**
