### PR TITLE
Npm for vendors

### PR DESCRIPTION
**Pull request by roramirez**
This Pull Request change to use npm to install vendor and get out from the code base for these external libraries. 

For first work is include in this Pull Request only font-awesome.  The old process keep clean and work the same way.  Only is added a trigger when is use the command "npm install" to install too in the directory called vendor.

### CODE REVIEW

**Comment by roramirez** [comment]
Thanks @fewieden Is already added here.

**Comment by MichMich** [comment]
Nice! One issue: we have a modified momentjs version in the vendor folder due to a bug (12h formatting screwed up). So we might need to use a fork for this.

**Comment by MichMich** [comment]
See https://github.com/MichMich/MagicMirror/issues/181
Not sure if this issue is still present in the most recent moment.js version.

**Comment by fewieden** [comment]
I'm currently using it with a rpi3 timeFormat 12, the clock and currentweather looking normal. Can you remember the edge cases when this error occured exactly?

**Comment by MichMich** [comment]
Are you using roramirez pull request? 

More info can be found in the mentioned issue.

**Comment by fewieden** [comment]
yes im using his fork and branch.

the only info i could find was rpi and timeformat set to 12. Still looking good so far.

**Comment by fewieden** [comment]
So I ran it for couple of hours and didn't come up with this issue so far. Would be great if others would test it as well, as it seemed to not appear for everyone in the past as well.

**Comment by MichMich** [comment]
It might be fixed in new Raspbian version. I'll just approve this commit, and hope no-one starts to cry ... ;)

**Pull request merged**
