### PR TITLE
Hide News Feed loading option

### PR DESCRIPTION
**Pull request by BeatIdo**
Configuration option to hide News Feed module if feed is empty instead of showing LOADING status

> Please send your pull requests the develop branch.
> Don't forget to add the change to CHANGELOG.md.

* Does the pull request solve a **related** issue?
* If so, can you reference the issue?
* What does the pull request accomplish? Use a list if needed.
* If it includes major visual changes please add screenshots.

### CODE REVIEW

**Comment by MichMich** [comment]
Could you please add an updated README (for the module) and updated CHANGELOG to your PR? Thanks!

**Comment by BeatIdo** [comment]
Done :)

**Comment by MichMich** [comment]
Merged!

**Comment by BeatIdo** [comment]
Nice :)

**Pull request merged**
