### PR TITLE
Avoid fade out/in on updateDom when many calendars are used

### PR DESCRIPTION
**Pull request by bugsounet**
related to #3185 

* I have limited updated dom to one update
-> `updateDom()` is activated by a timer which resets when a new event arrives (`CALENDAR_EVENTS`)

* I have set no speed to self update. I think it's not necessary
-> update it directly

If somebody can test and tell me result
In all case, I will patch my prod mirror for testing

### CODE REVIEW

**Comment by bugsounet** [comment]
Unfortunately, I see this morning that it doesn't work.
The problem remains the same.
I think it's because of the time taken to fetch  the data.
I'll see how to do it differently

**Comment by bugsounet** [comment]
Really if node 18 is strong too...

```bash
$ npx jest tests/e2e/modules_empty_spec.js 
 PASS   e2e  tests/e2e/modules_empty_spec.js
  Check configuration without modules
    ✓ shows the message MagicMirror² title (203 ms)
    ✓ shows the url of michael's website (202 ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        1.682 s

$ node -v
v18.18.0
```

**Comment by bugsounet** [comment]
# v2: I clear all and start again.

* added `updateOnFetch`  feature:
  * `true`: (default) like actually update DOM on each calendar data received
  * `false`: delayed update DOM and automaticaly updated every minutes

* basicaly, I see an internal timer every minutes for update DOM.
   * this internal timer is called on `start()`
   * I move it to a function called : `selfUpdate()`
   * I have added this rule: if `updateOnFetch` is not activated, So updatedDom with animationSpeed

---> +/- no change: just add animation speed or not when DOM Updated

* When `CALENDAR_EVENTS` received (socketNotificationReceived)
  * if `updateOnFetch` is activated (default): no change, it's updateDom() on ach notification received
  * if `updateOnFetch` is NOT activated:
    * updateDom() on first data received for each calendars
    * When others data received (next cycle): don't update DOM and use `selfUpdate()` rules for update DOM

---> Final result must be, when `updateOnFetch` disabled: ONLY one update DOM every minute

I will patch my prod mirror with this new file for testing (with `updateOnFetch` disabled)
I will see tomorrow morning

**Comment by bugsounet** [comment]
Good news; It works as requested!

**Comment by rejas** [comment]
so, its ready for review @bugsounet ?

**Comment by bugsounet** [comment]
yes, it's ready but something is really not clear for me

I have done some test

1) On my pi4 (without  animate and customCSS )
  * Tested with my prod version: I have the main issue (#3185)  
  * Tested with only clock / calendar: I have the issue too
  * Tested with `export ELECTRON_DISABLE_GPU=1`: I have the same issue

2) On my dev desktop (without animate, customCSS, ....)
 OS Ubuntu: 23.10
 Same prod config or only clock / calendar
 **I have not this main issue !**

maybe pi take many time for change CSS ?
So, I really don't understand

@rejas: what do you think about this ?

**Pull request merged**
