### PR TITLE
Add missing function call in module.js

### PR DESCRIPTION
**Pull request by rejas**
I noticed the show method is missing a `()` in the show method when calling the callback. The hide method has it for example. 

Also cleaned up the jsdoc and adjusted some log levels

### CODE REVIEW

**Comment by sdetweil** [comment]
I don't think the log level needs to be warning on the open whitelist.
its not bad

**Comment by rejas** [comment]
>  its not bad

It isnt bad per se but the log is in the warning color already. And why not show the user if he opens his ip list a lot? A more experienced user will know how to change his log level IF it really annoys him ;-)

**Comment by fewieden** [comment]
@rejas nice. Stumbled over the issue today as well.

**Comment by rejas** [comment]
@fewieden so someone is using that call actually ;-) ?

**Comment by fewieden** [comment]
@rejas yes, in order to only blur other modules when I actually can show the modal here https://github.com/fewieden/MMM-Modal/pull/7/files#diff-62b05431c54d3d6bceb46bb4e84772f44070a474852a5272e9e468bc0692299bR329-R333

Ideally, we also trigger the callback with an error here if the lock strings prevent from showing and not only on success.
I would like to send another module a notification in that case.

**Pull request merged**
