### PR TITLE
Wait till all node_helper are started before finishing startup

### PR DESCRIPTION
**Pull request by rejas**
In response to #2487 this implements a Promise.all for the node_helper start calls. Just a draft becuase I want to get feedback first....

### CODE REVIEW

**Review by MikeBishop — COMMENTED** [review]
Two pieces of feedback:

- It might make sense to move the log line into the completion block, so that the message indicates when all modules _have_ started rather than when all modules have been told to start. Or log in both places, to give some visibility into the time it takes for that to happen.
- Contrary to my original suggestion, `Promise.allSettled()` (Node 12.9+) might be more appropriate so that an error doesn't cause it to complete prematurely.

**Comment by rejas** [comment]
Thanks for the feedback @MikeBishop Now ready for real review ;-)

**Review by sdetweil — COMMENTED** [review]
what about those that fail?   are we expecting the module to alert the user somehow, and we say nothing?  just thinking of debug

**Comment by rejas** [comment]
not sure how many module developers use async here at all ....

**Comment by sdetweil** [comment]
well, none in the start function.. cause it doesn't exist..  i use both promises and async where appropriate

**Review by sdetweil — APPROVED** [review]

**Comment by rejas** [comment]
a module developer could use async anyway, even if it is not used in the prototype method (just like the OP does). might be interesting to mention it in the docs for developers...

**Review by khassel — APPROVED** [review]

**Review by MikeBishop — APPROVED** [review]

**Comment by MikeBishop** [comment]
FWIW, I wound up shipping mine using async anyway, and just putting the things that might take longer last.  I haven't encountered any ill effects from my start-up routine completing a bit after the parent process thinks it did.

But @sdetweil makes an interesting point.  In the current design, if a module throws an exception during start-up, does the server start-up fail entirely?  If that's the desired behavior, then `Promises.all()` was the correct method to start with, and having it throw the first exception encountered and kill the program would provide a similar result.

**Comment by rejas** [comment]
Im currently on a trip, so no real way for me to check the current behaviour. 
I would hope though that in case of an error the other modules start too and a meaningful error is shown somewhere (console or notification)...

**Comment by rejas** [comment]
> In the current design, if a module throws an exception during start-up, does the server start-up fail entirely? If that's the desired behavior, then `Promises.all()` was the correct method to start with, and having it throw the first exception encountered and kill the program would provide a similar result.

Currently if a node_helper of a module throws an exception in the start method, all other node_helper after that dont get started due to:

"
[12.10.2022 22:49.47.556] [ERROR] Error: listen EADDRINUSE: address already in use 127.0.0.1:8080
"

As an example, use the default config and throw an exception in the newsfeed helper module. Calendar module wont start and show nothing...

With the changes here that will still happen. Why? Because the start method doesnt return a promise, and we have no try/catch anywhere in the startup sequence.

Do I like this behvior? No, since it confuses a user. If a module errors, only that module should error and not any other module that has nothing to do with it. 

Two ways to fix it:
1) Add a try catch somewhere around where the server starts and handle it gracefully
2) Make the start method async (since it will then return a promise that can be handled with Promise.all...) and hope module developers change their method signature to use async too

Obviously 2) is a wishful thinking and would probably result in old modules that still work not being resilient. So I think 1) is the way to go. But since that doesnt have to happen here in this PR it can be done seperatly after this gets merged.

Comments?

**Comment by sdetweil** [comment]
yes, 2 is wonderful idea, but we have so many modules that are no longer maintained, this will never happen

so it must be option 1. 

I personally hate that we have a fatal config error but continue to run with something else

**Comment by khassel** [comment]
from my side this can be merged as it doesn't change the current state.

For a future PR: option 1 ...

**Comment by rejas** [comment]
Created a ticket for the error handling improvement: https://github.com/MichMich/MagicMirror/issues/2944

**Pull request merged**
