### PR TITLE
Enforce PRs to be based against develop branch

### PR DESCRIPTION
**Pull request by rejas**
"Inspired" by my mistake in https://github.com/MichMich/MagicMirror/pull/3028 this PR will add a worfklow check for the branch a PR is based against.

Open question is if this prevents @MichMich from preparing a release?

### CODE REVIEW

**Comment by khassel** [comment]
> Open question is if this prevents @MichMich from preparing a release?

looking into how he does releases, yes, he uses a PR.

May we could use something like "skipLabels" as provided in the changelog action - or look for a special string in the commit message (which would be not so safe)

**Comment by khassel** [comment]
may we could use e.g. https://github.com/marketplace/actions/pr-labels to get the PR labels and not exit if a specific label exists.

We need this not only for releases but also for some edge cases as updating README (which is possible after next release without update notifications).

**Comment by rejas** [comment]
> may we could use e.g. https://github.com/marketplace/actions/pr-labels to get the PR labels and not exit if a specific label exists.

I assume we maintainers are the only ones who can add labels to issues @MichMich ? Then adding a label like you say (maybe "hotfix") would be enough I think to prevent future master merges and allow stuff to be merged for such cases

**Comment by sdetweil** [comment]
I think there should never be a direct fix to master.  always promote from some other branch. 
pr to hotfix-x to master, 
pr to develop to master

**Comment by rejas** [comment]
So this PR is ready I think. It will complain if the PR is based upon master and does not have the new "mastermerge" label. Maintainers can test it on this PR, just add / remove the label and trigger the tests: https://github.com/MichMich/MagicMirror/pull/3036

Only thing that doesnt get caught is IF the PR is developed against Develop, but then submitted against Master (thats why this PR here wont fail if I change the base to master). Any ideas on how to fix that or is that a usecase we can ignore?

**Comment by khassel** [comment]
> Any ideas on how to fix that or is that a usecase we can ignore?

I think we can ignore it. If someone has an idea for a fix we can add it later ...

**Review by khassel — APPROVED** [review]

**Pull request merged**
