### PR TITLE
korea locale error fix and dev mode option function add

### PR DESCRIPTION
**Pull request by zelkun**
I can not speak English well. Please understand using a translator.
The dev mode function was corrected and the korea locale error was corrected.

> Please send your pull requests the develop branch.
> Don't forget to add the change to CHANGELOG.md.

**Note**: Sometimes the development moves very fast. It is highly
recommended that you update your branch of `develop` before creating a
pull request to send us your changes. This makes everyone's lives
easier (including yours) and helps us out on the development team.
Thanks!

- Does the pull request solve a **related** issue?
- If so, can you reference the issue?
- What does the pull request accomplish? Use a list if needed.
- If it includes major visual changes please add screenshots.

### CODE REVIEW

**Comment by rejas** [comment]
Hi @zelkun 
- what is this "dev" mode you want to fix?
- please work on the develop branch and point your pull request against the develop branch too
- isnt kr the correct country code for korea?

**Comment by zelkun** [comment]
image

Please consider using a translator,
1) To be precise, ko_kr and locale kr do not work.
2) npm run server dev <add option
3) Change to not hide the mouse cursor in dev mode

**Comment by rejas** [comment]
a) Please submit one PullRequest per feature, that makes it a lot easier to review it and get it merged. So one PR for the locale, one for the dev mode and one for the mouse cursor
b) Please work on the develop branch, NOT on the master branch.

**Comment by MichMich** [comment]
Closing. Please read the 

> a) Please submit one PullRequest per feature, that makes it a lot easier to review it and get it merged. So one PR for the locale, one for the dev mode and one for the mouse cursor
> b) Please work on the develop branch, NOT on the master branch.

Close. Please see above suggestions.

**Pull request closed without merging**
