### PR TITLE
Added 'the day after tomorrow' to calendar.js

### PR DESCRIPTION
**Pull request by yo-less**
Based on our forum discussion here:
https://forum.magicmirror.builders/topic/563/changing-moment-js-behavior/7#

I have added support for 'the day after tomorrow' in calendar.js, so instead of "in a day" (in einem Tag) it will show "the day after tomorrow" (Übermorgen) **only if** your config file has specified German ('de') as the mirror language.

This could, of course, be used as a starting point for adding "the day after tomorrow" support for more languages.

### CODE REVIEW

**Comment by MichMich** [comment]
Thanks for your contribution. One modification I want to suggest is to do an other check if the translation is supported. So in stead of: 
```javascript
if (config.language == 'de') {
    timeWrapper.innerHTML = this.translate("DAYAFTERTOMORROW");
} else {
    timeWrapper.innerHTML = moment(event.startDate, "x").fromNow();
}
```
Do the following:
```javascript
if (this.translate('DAYAFTERTOMORROW') !== 'DAYAFTERTOMORROW') {
    timeWrapper.innerHTML = this.translate("DAYAFTERTOMORROW");
} else {
    timeWrapper.innerHTML = moment(event.startDate, "x").fromNow();
}
```

This way only the translation files need to be modified in order to support this feature.

Additionally you might want to add the key to the translation files (commented) so people know they can translate it.

**Comment by MichMich** [comment]
Also, don't forget to add a modified CHANGELING.md to your PR.

**Comment by yo-less** [comment]
That's a much better way of doing it. I wasn't this was possible, but it does make sense. Whenever there is no translation entry, the mirror simply prints the tag instead of a translation. Thanks for improving the code!

**Comment by MichMich** [comment]
Thanks. It seems like your PR has conflicts. Were you working on the lastest develop branch?

**Comment by MichMich** [comment]
PR conflict is solved. Your PR is merged and I've added the translation for Dutch. Thanks for your contribution! 👍

**Pull request merged**
