### PR TITLE
Use metric units internally in all weatherproviders

### PR DESCRIPTION
**Pull request by rejas**
So finally I think this refactorin is ready to be reviewed :-)

DONE:
- [x] Removed all conversion functions for wind and temperature from specific weatherproviders
- [x] Use internally only metric units: celsius for temperature, meters per seconds for wind
- [x] Convert temp and wind into the configured units when displaying data on the UI
- [x] look how beaufort calculation uses metrics, added knots as new windunit
- [x] add more e2e tests 

Checked providers:
- [x] Darksky
- [x] EnvCanada
- [x] OpenWeatherMap
- [x] SMHI provider 
- [x] UK Met Office
- [x] UK Met Office DataHub
- [x] WeatherBit
- [x] WeatherFlow
- [x] WeatherGov

TODO in different tickets:
- check weatherproviders for usage of weatherEndpoint (as seen in https://github.com/MichMich/MagicMirror-Documentation/issues/131) -> see #2926 
- cleanup precipations -> #2953

### CODE REVIEW

**Comment by MichMich** [comment]
I love this PR. This is so much cleaner. Thanks! Let me know when it's ready to be merged.

**Comment by rejas** [comment]
I think this will not be ready for the next release, mainly due to not being sure if there arent any bugs in it. Would be nice to have people test this PR with their repsective providers...
Of course more tests would also be nice, which I might be ablke to do but probably not before August....

**Comment by MichMich** [comment]
No worries. It can easily wait till next release. 👍🏻

**Comment by buxxi** [comment]
Verified that the SMHI provider works as expected using the branch from this pull request. Great job.

**Comment by berlincount** [comment]
This is awesome, and truly so much cleaner! 👍 

Might I suggest to change the `useBeaufort` etc to `windUnits`along the lines of `tempUnits`?

As a pilot, I'd love support for `knots` there ...

P.S: found this PR while researching the integration of UV Index, but I'll hold off on that until this is merged. Great work!

**Comment by rejas** [comment]
Since darksky is bought by apple and will stop in 2023 they dont allow new signups for their webapi anymore. Can anyone of the original developers check out the code (and maybe check out https://github.com/MichMich/MagicMirror/issues/2899 too if that is a proble there too?)

Also, probably have to deprecate the provider sooner or later :-) Not sure if the Apple WeatherKit is something to follow up since there isnt a real free plan as far as I can see (https://developer.apple.com/weatherkit/get-started/)

So, regarding checking darksky out, I look at @nhubbard @fewieden and @buxxi since they might have api access still :-)

**Comment by buxxi** [comment]
I have never tried the darksky provider, so I can't help with that.

**Comment by rejas** [comment]
so I hopefully fixed all providers with respect to temperature and wind.

only with weatherflow I had to blindly "fix" it since I dont have a station for that api. maybe the original author @10bias can test this?

next I will take a look at the other open points. still, any testing is welcome :-)

**Comment by rejas** [comment]
> Might I suggest to change the `useBeaufort` etc to `windUnits`along the lines of `tempUnits`?

I am not an expert in wind stuff, so how would the windunits look like at the end?

**Comment by berlincount** [comment]
> > Might I suggest to change the `useBeaufort` etc to `windUnits`along the lines of `tempUnits`?
> 
> I am not an expert in wind stuff, so how would the windunits look like at the end?

if you've got m/s, it's comparatively simple.

https://www.convert-measurement-units.com/convert+Meters+per+second+to+Beaufort.php 

is a great reference :) I guess we'd love km/h, Beaufort, and knots.

**Comment by rejas** [comment]
> > > Might I suggest to change the `useBeaufort` etc to `windUnits`along the lines of `tempUnits`?
> > 
> > 
> > I am not an expert in wind stuff, so how would the windunits look like at the end?
> 
> if you've got m/s, it's comparatively simple.
> 
> https://www.convert-measurement-units.com/convert+Meters+per+second+to+Beaufort.php
> 
> is a great reference :) I guess we'd love km/h, Beaufort, and knots.
> 
> (if I get to it, I can write that code, but not today)

So I worked a little tonight at the windunits on my branch:

- useKmh and useBeafort is deprecated, internally the config windUnits is used instead
- windUnits allows "metric" (m/s), "imperial" (mph), "kmh", "beaufort" for now, plus also "knots"

Slowly getting to the finish line with this PR ;-)

**Review by khassel — APPROVED** [review]

**Review by buxxi — APPROVED** [review]
Looking good!

**Pull request merged**
