### PR TITLE
Added Spanish translations

### PR DESCRIPTION
**Pull request by jordi2830**

### CODE REVIEW

**Comment by MichMich** [comment]
Please check your double quotes starting from line 13. They seem incorrect.

**Comment by jordi2830** [comment]
Sorry my bad, reinstalled my OS shortly ago and it was set by default to automatically replace the regular quotes with those 'fancy' ones.

**Comment by jordi2830** [comment]
My latest commit should be fine, if I missed any more please let me know.
Sorry for the inconvenience.

**Comment by MichMich** [comment]
No problem! Thank you very much for your contribution! :)

**Pull request merged**
