### PR TITLE
Remote force check update

### PR DESCRIPTION
**Pull request by bugsounet**
updatenotification: 

allow force scanning with `SCAN_UPDATES` notification from other modules

### CODE REVIEW

**Review by rejas — APPROVED** [review]

**Comment by rejas** [comment]
looks innocent enough for a quick merge :-) sorry for not going through the animate stuff yet, this takes more concentration :-(

**Comment by rejas** [comment]
Could you also create a PR for adding these notifications to the docs?

**Comment by bugsounet** [comment]
Ok, i will take a look for prepare docs for all my stuff (commited or not)

**Comment by bugsounet** [comment]
@rejas : have you already had the case locally that the e2e test suite failed (`npm run test:e2e`) and without touching anything, by relaunching `npm run test:e2e` it works?
I got it twice (even with the branch master, naturally without any 3rd party modules)

**Comment by rejas** [comment]
> @rejas : have you already had the case locally that the e2e test suite failed (`npm run test:e2e`) and without touching anything, by relaunching `npm run test:e2e` it works?

yes, the tests fail sometimes without any good reason. maybe some timing issues or whatever, we couldnt find it out yet. any help there would be greatly appreciated

**Pull request merged**
