### PR TITLE
left electron left in dependencies section vs pr 1788

### PR DESCRIPTION
**Pull request by sdetweil**

### CODE REVIEW

**Comment by MichMich** [comment]
Isn't electron required anymore?

**Comment by sdetweil** [comment]
its in the optionalDependencies section..   
```
  "optionalDependencies": {
    "electron": "^3.0.13"
  },
````

that way if there is no version for armv6 (or whatever) , install won't fail, and serveronly mode will still work.

right now, install fails. leaving a mess

don't want it in the mandatory dependencies too

**Comment by sdetweil** [comment]
and run-start.sh has been changed to support non-electron systems by using chromium-browser
and intentional serveronly mode (config option)  and also on non-gui systems

**Comment by MichMich** [comment]
Ah, missed that. Thanks.

**Pull request merged**
