### PR TITLE
Add no-user-gesture-required flag to MagicMirror

### PR DESCRIPTION
**Pull request by dolanmiu**
Some modules play sound without user interaction. Adding a flag allows sound and video to be played

Read more here:

https://github.com/electron/electron/issues/13525
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

> Please send your pull requests the develop branch.
> Don't forget to add the change to CHANGELOG.md.

**Note**: Sometimes the development moves very fast. It is highly
recommended that you update your branch of `develop` before creating a
pull request to send us your changes. This makes everyone's lives
easier (including yours) and helps us out on the development team.
Thanks!

* Does the pull request solve a **related** issue?
* If so, can you reference the issue?
* What does the pull request accomplish? Use a list if needed.
* If it includes major visual changes please add screenshots.

### CODE REVIEW

**Comment by MichMich** [comment]
This is already solved in the dev branch. See: https://github.com/MichMich/MagicMirror/pull/1674/files

**Comment by dolanmiu** [comment]
When is dev released to master?

**Comment by MichMich** [comment]
> This release is scheduled to be released on 2019-07-01.

See CHANGELOG.

**Comment by NeelChandra001** [comment]
What a Mess !

**Comment by MichMich** [comment]
> What a Mess !

What do you mean?

**Pull request closed without merging**
