### PR TITLE
Add Weather provider UK Met Office

### PR DESCRIPTION
**Pull request by maloakes**
> Please send your pull requests the develop branch.
> Don't forget to add the change to CHANGELOG.md.

**Note**: Sometimes the development moves very fast. It is highly
recommended that you update your branch of `develop` before creating a
pull request to send us your changes. This makes everyone's lives
easier (including yours) and helps us out on the development team.
Thanks!

* Does the pull request solve a **related** issue?
* If so, can you reference the issue?
* What does the pull request accomplish? Use a list if needed.
* If it includes major visual changes please add screenshots.

Added UK Met Office Datapoint feed as a provider in the default weather module.
- added new provider class
- added suncalc.js dependency to calculate sun times (not provided in datapoint feed)
- added "ukunits": temp in degrees C, wind speed in MPH, precipitation in %
- use Feels Like temp from feed if present
- optionally display precipitation in current weather

### CODE REVIEW

**Comment by MichMich** [comment]
Thanks for this PR. I'm not sure if `ukunits` is a very clean solution. Maybe we should allow a configuration for different items. Then we can just use the real units.

**Comment by maloakes** [comment]
Thank you.
  
I couldn’t think of an elegant way of doing it.
  

  
Maybe I’ll introduce separate config items for temperatures, wind and rain. These would default to config.units but allow specification of imperial/metric for each item. Rainfall forecast would be set to ‘%’ for data from UKMO.
  

  

  
  

  
  
>

**Comment by MichMich** [comment]
That sounds like a good aproach! Thanks for your effort!

**Comment by maloakes** [comment]
Proposed changes made.
Sorry for the delay.

**Comment by MichMich** [comment]
Thanks!

**Pull request merged**
