### PR TITLE
Fix wrong treatment of `appendLocationNameToHeader` when using `ukmetofficedatahub`

### LINKED ISSUE #2524: cc
### Fix wrong treatment of appendLocationNameToHeader when using ukmetofficedatahub
in the ukmetofficedatahub module you have 
```
		if (this.config.appendLocationNameToHeader) {
			queryStrings += "&includeLocationName=" + true;
		}
```
you should remove the if ... and leave just:
```
queryStrings += "&includeLocationName=" + true;
```
this will allow `appendLocationNameToHeader` parameter at weather.js to resolve if include or not in the header (title).

### PR DESCRIPTION
**Pull request by rejas**
Fixes #2524 supersedes #2521 all credits to @B1gG

### CODE REVIEW

**Comment by MichMich** [comment]
What do you want me to do with this one? 😅

**Comment by rejas** [comment]
@B1gG seemed to have trouble getting his PR ready for merging so I took his PR and whipped it into prettier shape.

**Comment by rejas** [comment]
So you can merge it, credits due to @B1gG of course

**Comment by rejas** [comment]
Will look into the merge conflict first of course

**Comment by rejas** [comment]
All fine now :-)

**Pull request merged**
