### PR TITLE
Fix calendar.js missing default symbol prefix

### PR DESCRIPTION
**Pull request by DaveChild**
Symbols provided in customEvents don't get the "fas fa-fw fa-" prefix, which according to the docs they should. This fixes that.

Hello and thank you for wanting to contribute to the MagicMirror² project

**Please make sure that you have followed these 4 rules before submitting your Pull Request:**

> 1. Base your pull requests against the `develop` branch.
>
> 2. Include these infos in the description:
>
> - Does the pull request solve a **related** issue?
> - If so, can you reference the issue like this `Fixes #<issue_number>`?
> - What does the pull request accomplish? Use a list if needed.
> - If it includes major visual changes please add screenshots.
>
> 3. Please run `npm run lint:prettier` before submitting so that
>    style issues are fixed.
>
> 4. Don't forget to add an entry about your changes to
>    the CHANGELOG.md file.

**Note**: Sometimes the development moves very fast. It is highly
recommended that you update your branch of `develop` before creating a
pull request to send us your changes. This makes everyone's lives
easier (including yours) and helps us out on the development team.

Thanks again and have a nice day!

### CODE REVIEW

**Comment by khassel** [comment]
Thanks!

Related to this [forum thread](https://docs.magicmirror.builders/modules/weather.html#yr-options).

Can you please add an entry into CHANGELOG.md under "Fixed" (we collect all PR's there for next release info), otherwise the tests will fail ...

**Comment by DaveChild** [comment]
I think that's done it. Sorry, I'm a bit rushed today or I'd have read the docs before committing etc :)

**Review by khassel — APPROVED** [review]

**Comment by rejas** [comment]
Thx for the PR. Do you feel adventerous enough to write test for this too?

**Comment by DaveChild** [comment]
Bah humbug. Ok, I'll give it a try :)

**Comment by DaveChild** [comment]
Ok, I've had a crack at a test. Sorry, code's a bit of a mess, not used jest etc before, so took a while to get to grips with. I've added a new test to make sure the customEvent symbol is set, and it passes on my dev system.

**Review by rejas — APPROVED** [review]

**Comment by rejas** [comment]
Thx for the PR and the tests! Good job!

**Pull request merged**
