### PR TITLE
update One Call API results for openweathermap

### PR DESCRIPTION
**Pull request by njwilliams**
The results from the /onecall endpoint were not
being parsed correctly in current and forecast mode - it was
assuming the current/forecast endpoint API, and the return
datasets are different. The effect was that the module
would simply display "Loading..." when in /onecall mode, since
it has no way of displaying error status (ideally, it should,
but leave that for another day)

Hello and thank you for wanting to contribute to the MagicMirror project

**Please make sure that you have followed these 4 rules before submitting your Pull Request:**

> 1) Base your pull requests against the `develop` branch.
>
>
> 2) Include these infos in the description:
>  * Does the pull request solve a **related** issue?
>  * If so, can you reference the issue like this `Fixes #<issue_number>`?
>  * What does the pull request accomplish? Use a list if needed.
>  * If it includes major visual changes please add screenshots.
>
>
> 3) Please run `npm run lint:prettier` before submitting so that
> style issues are fixed.
>
>
> 4) Don't forget to add an entry about your changes to
> the CHANGELOG.md file.

**Note**: Sometimes the development moves very fast. It is highly
recommended that you update your branch of `develop` before creating a
pull request to send us your changes. This makes everyone's lives
easier (including yours) and helps us out on the development team.

Thanks again and have a nice day!

### CODE REVIEW

**Comment by njwilliams** [comment]
Is there someone who could look at this pull request? (I re-submitted the pull request because I had a bug in the last version)

**Comment by rejas** [comment]
I would try it out if you could help me with my config for this case:

```

		{
			module: "weather",
			//disabled: true,
			position: "top_left",
			config: {
				type: "hourly",
				location: "Berlin",
				locationID: "7290255",  //ID from http://www.openweathermap.org/help/city_list.txt
				apiKey: "<apikey>",
				weatherEndpoint: "onecall"
			}
		},
```

Is that correct or what do I need to add?

**Comment by njwilliams** [comment]
The onecall API does not accept anything other than latitude and longitude to describe the location

**Review by rejas — APPROVED** [review]
Got hourly forecast and current weather with lat/long in my config. Famous last words: Works on my machine too :-)

**Comment by khassel** [comment]
your changes are breaking the weather forecast tests (see `tests/e2e/modules/weather_spec.js`):

````
FAIL e2e tests/e2e/modules/weather_spec.js (547.714 s)
  Weather module
    Current weather
      Default configuration
        ✓ should render wind speed and wind direction (5468 ms)
        ✓ should render sunrise (5275 ms)
        ✓ should render sunset (5342 ms)
        ✓ should render temperature with icon (5215 ms)
        ✓ should render feels like temperature (5229 ms)
      Compliments Integration
        ✓ should render a compliment based on the current weather (8328 ms)
      Configuration Options
        ✓ should render useBeaufort = false (5240 ms)
        ✓ should render showWindDirectionAsArrow = true (5214 ms)
        ✓ should render showHumidity = true (5236 ms)
        ✓ should render degreeLabel = true (5286 ms)
      Current weather units
        ✓ should render imperial units (5213 ms)
        ✓ should render custom decimalSymbol = ',' (5269 ms)
    Weather Forecast
      Default configuration
        ✕ should render days (60002 ms)
        ✕ should render icons (60000 ms)
        ✕ should render max temperatures (60002 ms)
        ✕ should render min temperatures (60001 ms)
        ✕ should render fading of rows (60002 ms)
      Configuration Options
        ✕ should render custom table class (60003 ms)
        ✕ should render colored rows (60002 ms)
      Forecast weather units
        ✕ should render custom decimalSymbol = '_' (60001 ms)
````

You can run this single test suite with `npx jest -i --testMatch **/tests/e2e/modules/weather_spec.js` from the mm folder.
E.g. the first failing test is awaiting the object `.weather table.small tr:nth-child(${index + 1}) td:nth-child(1)` which doesn't exist so it is waiting until timeout.

**Comment by njwilliams** [comment]
Thanks for the very helpful debug there! 

The problem highlighted here is using forecast mode via /forecast endpoint instead of via /onecall endpoint ended up with the wrong attribute, definite typo of mine. Fixed that and pushed an update. I can see it working on a dev mirror when i create the config you supplied, and a few other varieties.

However, I still can't get the test suite to say anything useful (in fact, it now says that all tests fail for me), but I can't get to the errors. The attempts I've made to replicate the test configuration all work for me on a live mirror. The test suite fails me... The fact that the longer the test suite runs, the more it overloads the system (on a pi, i see a loadavg of > 100 if the test suite runs for more than a minute). And versions or something of it seem to be weird. I'm now just lost down a twisty maze of git and npm hell. Actually, a plain "npm test" showed it working. It's the jest usage that's messed up for me now and I feel I cannot reliably use the test suite.

**Comment by rejas** [comment]
I merged the latest develop branch locally into your PR, the tests run fine now.

**Comment by MichMich** [comment]
Thanks for everybody's time! Great work. 🎉

**Pull request merged**
