### PR TITLE
change readme to point to community repo for install/update scripts

### PR DESCRIPTION
**Pull request by sdetweil**
* Does the pull request solve a **related** issue?
#1856 #1866

### CODE REVIEW

**Comment by sdetweil** [comment]
@MichMich   travis broken again

**Comment by MichMich** [comment]
I've just stared working on a docs site to separate the docs from the repo:
https://docs.magicmirror.builders

This way we can update the docs without releasing a new version. In this site, I've already used your new links.

When the new docs site is a bit more polished, I'll remove the docs from the MagicMirror repo, and point to the docs site. If you want to add something to the docs, please send a PR to https://github.com/MichMich/MagicMirror-Documentation

Thanks for all your contributions, Sam! I really, really appreciate it!

**Comment by sdetweil** [comment]
@MichMich   how long til u think the new site will be ready?

just thinking about users who will use the bad scripts..

**Comment by MichMich** [comment]
Doing the best I can. (But busy with work, in the middle of a house renovation, wife’s away for work and one of my two kids is currently ill ... so can’t make promises. 🤪)

**Comment by sdetweil** [comment]
no problem.. it was just for my planning..  we all have things going on

**Comment by MichMich** [comment]
I've updated README.md in master to reflect the link to the Docs site. Feel free to send PR's to the Docs repo if it needs updates.

**Pull request closed without merging**
