### PR TITLE
up spectron version to 4.0.0(fix arm64 install)

### PR DESCRIPTION
**Pull request by vvzvlad**
Fix error in #1462 issue, not install MM on arm64 platform(orangepi, etc). 

According to the advice in the issue, I raised the spectron version to 4.0.0 (previously it was 3.8.0) which fixed the installation problems. However, I do not know how it will affect other platforms. On Raspberry PI, it runs and works correctly, but that's all I can check.

### CODE REVIEW

**Comment by MichMich** [comment]
Hi, Unfortunately Travis can't run the checks using these changes. Not sure what's the issue since I'm not using spectrum myself. Any Idea how to solve this? (Can't merge without this issue being fixed.)

**Comment by vvzvlad** [comment]
I ran npm install and included the updated package-lock.json in the PR. It turns out that package-lock.json can not be fixed manually.

**Comment by MichMich** [comment]
Unfortunately it's still not passing. Any idea?

**Comment by MichMich** [comment]
Closed due to inactivity. Feel free to reopen.

**Pull request closed without merging**
