### PR TITLE
Fixed weather.gov api issue where precipitation probability was not being shown in hourly or daily forcast

### LINKED ISSUE #3182: Issue with weather forecast module when using weather.org
When I turn on precipitationProbablility it never displays anything. Just says loading

### PR DESCRIPTION
**Pull request by dgoth**
Fixes #3182
-adds precipitation probability to the hourly forecast
-removed and replaced precipitation probability calculation in the daily forecast

### CODE REVIEW

**Comment by rejas** [comment]
Thx for the PR, please rebase it against the `develop` branch so that we can review it.

**Comment by dgoth** [comment]
Done

**Comment by rejas** [comment]
`Files changed` still looks weird. Maybe you have to do the PR again (and cherry pick your commits)?

**Comment by khassel** [comment]
PR is still based against `master`, we cannot merge it before it is rebased against `develop` ...

**Pull request closed without merging**
