### PR TITLE
Make the app start using async/await instead of callbacks

### PR DESCRIPTION
**Pull request by buxxi**
- Modernizing the startup using async/await instead of callbacks.
- Since it's not blocking now at startup I had to move the creation of the app/server into the `ready`-event for electron, otherwise the screen was black at startup.
- Moved the repeated code for timeouts when calling `app.close()` as an argument to that method instead.

### CODE REVIEW

**Comment by buxxi** [comment]
Hmm, works on my machine with node `16.17.1` and `14.20.1` which these checks run...

**Comment by rejas** [comment]
Yeah, the tests are still somehow fragile.... Sometimes re-running helps, sometimes not...

**Comment by buxxi** [comment]
And now 2 other fails instead, great...

`global.page` seems to be null sometimes here: https://github.com/MichMich/MagicMirror/blob/4d47c0837ff5bb853664fac599dd182ef1628c37/tests/electron/helpers/global-setup.js#L39

I could see that happen if this if-statement fails: https://github.com/MichMich/MagicMirror/blob/4d47c0837ff5bb853664fac599dd182ef1628c37/tests/electron/helpers/global-setup.js#L15

According to https://playwright.dev/docs/api/class-electronapplication#electron-application-windows `windows()` doesn't return a promise, so awaiting for it doesn't do anything. I wonder if this if-statement is even needed?

**Comment by khassel** [comment]
yeah, tests are really fun, you make changes and they all run locally and then they began to fail on github, but not always ...

> I wonder if this if-statement is even needed?

try it without, the next statement is trying to get first window so we will see whats happens ...

**Comment by rejas** [comment]
Trying your branch out, I also got (only once!) some errors in the electron tests where the date is used (like compliments or weather sunset)... But now two runs without errors... SOme weird race conditions?

**Comment by buxxi** [comment]
Most likely since the whole startup was blocking the thread before and NodeJS is single threaded. So the server startup probably blocked electron from receiving any events before that was done.

**Comment by rejas** [comment]
> According to https://playwright.dev/docs/api/class-electronapplication#electron-application-windows `windows()` doesn't return a promise, so awaiting for it doesn't do anything. I wonder if this if-statement is even needed?

There are two more "await window()" calls in the tests, one in electron/env_spec the other in electron/helpers/global-setup could you get rid of them too?

**Comment by buxxi** [comment]
Think I understand what it was trying to check, when I removed this if-statement it failed once because the test that opens the dev console had the dev console as the first window and not the magicmirror. So probably would need to wait for each window until the correct one appears.

That doesn't explain the error on github actions. will have to look into it more tomorrow.

**Comment by buxxi** [comment]
Finally...

Please retry the checks a few times in case this was a fluke :)

**Comment by rejas** [comment]
Bad news, the tests/electron/modules/calendar_spec.js tests dont fail if change the date (the weather and compliments seem to be fine and fail if I change the dates) :-( Could you look into it?

**Comment by buxxi** [comment]
It's the same in `develop`-branch, so it's nothing that I broke :)

**Comment by buxxi** [comment]
The tests will now wait until timeout if the css-classes are missing, not optimal...

**Comment by buxxi** [comment]
Been running the electron-tests in a loop for over an hour now without any of them failing locally... This is a bit annoying

**Comment by khassel** [comment]
I spent hours with the tests, running locally means nothing ... every time I thought now they are o.k. I did a run on Github and they failed there ... The timing seems totally different, the stuff on Github is slower and sometimes tests there fails because of the 20 sec. timeout which never happens locally. You can use your `develop` branch in your fork and push it to your fork on Github to run the tests (codecov will fail but the rest runs) so you can check Github without using this repo (and showing everyone the fails). From the `actions` tab you can rerun tests without pushing again, thats whats I'm doing after changing tests ...

**Comment by buxxi** [comment]
Well, I'm totally out of ideas so I guess it's time to give up on this PR...

**Comment by buxxi** [comment]
I wont have any time in in the nearby months to continue this so closing the PR.

**Pull request closed without merging**
