### PR TITLE
Latest version of ical.js and fix for EXDATE formats

### PR DESCRIPTION
**Pull request by DutchDynamics**
The format of EXDATE is different between google and exchange. This is causing the exclusion on recurring appointments not to work correctly and in some cases the mirror is unable to load the calendar

### CODE REVIEW

**Comment by MichMich** [comment]
@roramirez It this ok with the work you're currently doing?

**Comment by roramirez** [comment]
Well ... I think we need approve  only if include some tests. In the past we change something and affect the calendars, maybe was rrule or other related. 

I tested the change proposed (https://github.com/MichMich/MagicMirror/issues/839#issuecomment-297214548)  for set the ORDINAL_BASE lower date and the tests of this library they broke. I think not this way to fix this.

**Comment by MichMich** [comment]
@DutchDynamics Are you able to add tests?

**Comment by MichMich** [comment]
Closed due to inactivity. Feel free to reopen with tests.

**Pull request closed without merging**
