### PR TITLE
fix updatenotification module to not crash

### PR DESCRIPTION
**Pull request by sdetweil**
- properly handle race conditions, stop crash
- display for a short time, not forever

### CODE REVIEW

**Comment by MichMich** [comment]
It seems this PR has a conflict. It might be already updated?

**Comment by sdetweil** [comment]
I only see my changes compared to previous

**Comment by MichMich** [comment]
https://github.com/MichMich/MagicMirror/pull/1716/conflicts

**Comment by MichMich** [comment]
Thanks! I'm about to release 2.8.0, and will merge your PR to Dev after the release. It's to big of a change to release to master untested.

**Comment by sdetweil** [comment]
understood

**Comment by MichMich** [comment]
Merged into develop! Thanks again!

**Pull request merged**
