### PR TITLE
Module Updates

### PR DESCRIPTION
**Pull request by qistoph**
* Check if updates are available for non-default modules

The UI will only show one of the available updates currently. If that's an issue for you, please let me know your wishes regarding displaying multiple available updates.

Translations are only included for NL and EN.

### CODE REVIEW

**Comment by paviro** [comment]
Nice 👍🏼

**Comment by MichMich** [comment]
Awesome work. Thanks!

**Comment by MichMich** [comment]
I'm currently getting this message:
screen shot 2016-11-17 at 11 48 19

Of course we can exclude the .AppleDouble, but it might be a better idea to only check registered (in config) modules. This way unused modules won't give a message.

Is that something you can look into?

**Comment by qistoph** [comment]
Yeah sure, good idea. I'll give it a shot

**Pull request merged**
