### PR TITLE
Develop branch. Added Galician translation

### PR DESCRIPTION
**Pull request by qu1que**
Hi,

I've just made a Galician translation json file.

### CODE REVIEW

**Review by rejas — APPROVED** [review]

**Comment by MichMich** [comment]
It seems the translation isn't added to the list of translations. Could you add that? Thanks a lot!

**Comment by rejas** [comment]
Also @qu1que could you add a translation for the newly added "MODULE_CONFIG_ERROR" string?

**Comment by MichMich** [comment]
See: `translations/translations.js`

**Comment by qu1que** [comment]
I think it's done now.

**Comment by qu1que** [comment]
I have errors on test  10.x and test 12.x but I don't know why

**Comment by rejas** [comment]
Just run "npm run lint:prettier" to fix some styling issues

**Comment by qu1que** [comment]
I will close this PR and start again changing all files at once.

**Pull request closed without merging**
