### PR TITLE
Set version spectron for 3.6.x

### PR DESCRIPTION
**Pull request by roramirez**

### CODE REVIEW

**Comment by roramirez** [comment]
Hey @QNimbus 

Sometimes vendors test still failing
https://travis-ci.org/MichMich/MagicMirror/jobs/258781699#L990

Some idea?

**Comment by QNimbus** [comment]
@roramirez I noticed this too; it seems random, and I haven't been able to pinpoint the problem yet. I will try to investigate as well, let me know if you come up with something!

**Comment by roramirez** [comment]
Hey, I've thinking is not necessary for this  test the use of `beforeAll` and `afterAll`.

What do you think? https://github.com/roramirez/MagicMirror/commit/9d7b0487d569673afb475af0859fa4a68f5b33d2

**Comment by QNimbus** [comment]
Seems that this could work - can you try this fix and have it go through a Travis CI check?

**Comment by roramirez** [comment]
its already in these builds
https://travis-ci.org/roramirez/MagicMirror/builds/259200820

I pushed the PR  #977

**Pull request merged**
