### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by khassel**
- update dependencies in package.json
- require node >= v12 in package.json
- remove rrule-alt in package.json (no require found)
- update next release date in changelog

Tested this with node v16, we will see ...

### CODE REVIEW

**Comment by rejas** [comment]
Nice, the tests run through...

Regarding rrule-alt, I found this in the v2.1.1 changelog entry

- Switched out `rrule` package for `rrule-alt` and fixes in `ical.js` in order to fix calendar issues. ([#565](https://github.com/MichMich/MagicMirror/issues/565))

Not sure if that is still relevant?

**Comment by rejas** [comment]
Do we need rrule at all? Cant find a require for that neither...

**Comment by khassel** [comment]
> Switched out rrule package for rrule-alt and fixes in ical.js in order to fix calendar issues. (#565)

thats what i found, but nothing in the code.

> Do we need rrule at all?

Didn't search for `rrule` but there is no require in the code. It is used by `node-ical` so may it was used a long time ago.
So should I update this PR and remove `rrule`?

Or may @sdetweil can tell us more?

**Comment by rejas** [comment]
Looking at the code I think it is a left over entry from the time when ical was in the code, not as a library but commited directly into the code. Back then the dependency to rrule was needed (and later replaced with rrule-alt)
So I say, remove it, I dont think anything will break :-D famous last words: What could possibly go wrong? ;-)

**Pull request merged**
