### PR TITLE
Greek Translation

### PR DESCRIPTION
**Pull request by kapsolas**
Pull request adds the Greek Translation

### CODE REVIEW

**Comment by MichMich** [comment]
You did it. Great work. :)

**Comment by kapsolas** [comment]
Thanks! Trying to learn how to use github :)

**Comment by MichMich** [comment]
It took me a while as well ... but once you get the hang of it, it feels very rewarding to contribute to open source projects! :)

**Comment by kapsolas** [comment]
:)  Yeah it does! I got my MMM-Flickr done and on github already. MMM-Instagram is done too.. Need to push it to github this weekend as well.

**Comment by MichMich** [comment]
Nice! Don't forget to add them to the Wiki and tell about them on the forum.

**Pull request merged**
