### PR TITLE
Added Swedish translation

### PR DESCRIPTION
**Pull request by OskarKlintrot**
I have just added Swedish translation, no bugs fixed and no features added.

### CODE REVIEW

**Comment by MichMich** [comment]
Thanks!

**Comment by OskarKlintrot** [comment]
Thank you, this is my first contribution to an open source-project! :smile:

**Comment by OskarKlintrot** [comment]
Oh, I noticed that the cardinal direction for NE is missing in the language-files. Should I open an issue for that or is it on purpose?

**Comment by MichMich** [comment]
in all translations or your file?  (on my phone so cant check)

**Comment by OskarKlintrot** [comment]
In all translations in both the master and develop branches.

**Comment by MichMich** [comment]
Could you open a Issue for this? Will look into it when I get back from holiday. Thanks.

**Comment by OskarKlintrot** [comment]
Sure thing, see issue #344! Have a great holiday!

**Pull request merged**
