### PR TITLE
Respect parameter ColoredSymbolOnly also for custom events

### PR DESCRIPTION
**Pull request by TheDuffman85**
Respect parameter ColoredSymbolOnly also for custom events

grafik

### CODE REVIEW

**Comment by TheDuffman85** [comment]
I can't see what is wrong with the coding style.

**Comment by MichMich** [comment]
Did you run `npm run lint:prettier`?

**Comment by TheDuffman85** [comment]
Sorry, now I did. There were some tabulators it didn't like. How do I correct this? Should I create a new pull request?

**Comment by MichMich** [comment]
No worries. If you push your remote branche, the PR should automatically update and the tests will restart.

**Pull request merged**
