### PR TITLE
Proposal to hide the recurring count title in the calendar module

### PR DESCRIPTION
**Pull request by jupadin**
This PR is a first idea to implement the feature in #2700.

> 1. Base your pull requests against the `develop` branch.

Done.

> 2. Include these infos in the description:
>
> - Does the pull request solve a **related** issue?
> - If so, can you reference the issue like this `Fixes #<issue_number>`?
> - What does the pull request accomplish? Use a list if needed.
> - If it includes major visual changes please add screenshots.

Done (In the issue #2700).

> 3. Please run `npm run lint:prettier` before submitting so that
>    style issues are fixed.

Done.

> 4. Don't forget to add an entry about your changes to
>    the CHANGELOG.md file.

Done.

### CODE REVIEW

**Comment by MichMich** [comment]
I think this PR still needs some thought. It is such an edgecase that we might want to rethink wether or not we want to bloat the current module. Maybe it makes more sense to built a nice (third party) birthday calendar module?

**Comment by jupadin** [comment]
The definition of edgecase depends on the point of view I would say.
Regarding bloating the module I would say that adding this small adaption, wouldn't be that much change - since "developing" a 3rd party module would be 99,9% similar to the calendar module, since it brings everything with it already.
This modification can also be used as an anniversary calendar for yearly recurring wedding days, name days, jour fixes and sprints.

In the course of this, I also noticed that there is a bug in the calculation of times regarding all-day events, as the time from 2007 is used here to calculate the summer and winter time changeover (DST), instead of the time of the current year - these times change from year to year.
That would probably be worth another PR, though.

I would be happy in any case about this functionality in the Calendar module, because I use this currently already very much - If the PR would be merged, I would be happy but otherwise it's absolutely understandable - I would add it then just locally and if there is still someone who faces the same problem I'm happy to share the modifications.

**Comment by MichMich** [comment]
Maybe a bit cleaner solution is the option to set a maximum for the reoccurring count. So let's say you set it to 100, everything higher then 100 will be hidden. That way we don't need to specify an arbitrary year.

**Comment by MichMich** [comment]
If you are okay with that, please send a new pr. Closing this one for now.

**Comment by jupadin** [comment]
> Maybe a bit cleaner solution is the option to set a maximum for the reoccurring count. So let's say you set it to 100, everything higher then 100 will be hidden. That way we don't need to specify an arbitrary year.

What do you mean by "higher than 100 will be hidden" ?
I want to hide the recurring count title when I don't know the exact starting year such that I can specify a year (e.g., birthday or wedding dates - whiteout knowing the exact year) such that there will no recurring title will be displayed for exactly those events - all other (even if higher or lower a magic number like 100) will be displayed..

**Comment by jupadin** [comment]
Would be happy to provide a new PR but currently the requirements aren't that clear for me, sorry!! ...

**Comment by MichMich** [comment]
Let say you set 100 as max, in case the year for that event is 1900, the reoccurring count would be 121 and therefor be hidden.

**Comment by jupadin** [comment]
Ah, now I got it - thanks!
Gonna prepare another PR next week.

**Pull request closed without merging**
