### PR TITLE
Set configuration file by enviroment variable

### PR DESCRIPTION
**Pull request by roramirez**
Related proposal  by @qistoph in test suite
https://forum.magicmirror.builders/topic/1456/test-suite-for-magicmirror/7

### CODE REVIEW

**Comment by roramirez** [comment]
Yes, I did  test before ;) and is working. I just remove console.log introduced.

**Comment by qistoph** [comment]
Ah of course, the good old function-scope... Keeps tricking my mind, probably because of coding all kinds of languages and most having block-scope ([more details](http://www.adequatelygood.com/JavaScript-Scoping-and-Hoisting.html)) 

To prevent this kind of misinterpretation, I would suggest to use this form:
````javascript
var x;
if(something) {
  x = 1;
} else {
  x = 2;
}
````

**Comment by roramirez** [comment]
Hi @qistoph 

This way seems more sense to me
```javascript
var configFilename = path.resolve(global.root_path + "/config/config.js");
if (typeof(global.configuration_file) === 'undefined' ) {
	var configFilename = path.resolve(global.configuration_file);
}
```
Let me know what you think

**Comment by qistoph** [comment]
Yup, agreed

**Pull request merged**
