### PR TITLE
Add Prettier for an even cleaner code-experience 

### PR DESCRIPTION
**Pull request by rejas**
After updating the code linters I smelled blood. This PR adds prettier to the mix to enforce a code style on all js/css/yml/markdown. This also reduces the number of used linters in the project down to prettier, eslint and stylelint. It also adds an editorconfig file to give the IDEs hints on how to autoformat stuff accordingly.

When run (with `npm run lint:prettier`) it would pretty much change every file in the project since nearly all of them have their own style (like spaces, function brackets etc) which wasnt yet covered by eslint or styleleint. Therefor this PR is just a DRAFT so that you can take a look at it and see for yourself the basic changes this PR does. 

Thats also why the tests will fail since prettier is also part of the travis pipeline now.

Once I have your ok @MichMich, I would run prettier on the codebase and update this PR with it so that the tests will run through again without errors.

### CODE REVIEW

**Comment by MichMich** [comment]
I like the idea, but I feel this might scare people from contributing. If all of their PR's fail because they do not follow the prettier rules, the fun of contributing soon begins to fade. I't important to keep in mind that a LOT of contributions were made by first time contributors (people who just started contributing to open source).

What's your thought on this?

**Comment by rejas** [comment]
The good thing about prettier is that AFAIK it reports no errors that itself cannot fix. So even if your tests would fail, you only need to do a "npm run prettier" and commit your changes to be good again.

Also, one thing we could do is add something like "lint-staged" to the project which automatically runts prettier when a git hook like "commit" is triggered. That would take care of that too.

**Comment by sdetweil** [comment]
but now we have polluted the repo history with 'tab and spaces ' fixes.. 

i have a couple other projects that use this, and I hate it.. can never remember to run the formatter first.. and I use different editors on different systems, so sometimes I get tabs, and sometimes spaces and sometimes mixed..

**Comment by rejas** [comment]
> 
> but now we have polluted the repo history with 'tab and spaces ' fixes..

It would be only the initial commit here that changes alot of the files. All other PRs would already adhere to that formatting. Lint-staged helps to autoamtically run the linter on staged files so that you already commit only formatted code. See https://github.com/okonet/lint-staged

> 
> i have a couple other projects that use this, and I hate it.. can never remember to run the formatter first.. and I use different editors on different systems, so sometimes I get tabs, and sometimes spaces and sometimes mixed..

Here editorconfig comes into play. It basically tells your editor (most of them support it, webstorm, vs etc): hey, this project here wants this formatting for its files. See https://editorconfig.org/

**Comment by rejas** [comment]
I added an commit with https://github.com/azz/pretty-quick as the pre-commit tool. As you can see it automatically formats the only changed file (package.json) according to prettiers formatting rules. 

Now in this commit all of the file is changed. This is because the intendation is different then all other json files have but in the future commits the changes would be a lot smaller.

Like I said in the final commit I would have all files linted according to prettier rules. After that the linting happens automatically when commiting your files (and only on those files changed). The tests would only fail if more serious stuff from eslint or stylelint would get triggered.

**Comment by MichMich** [comment]
That will add another dependency. I'm not sure if the benefits of Prettier are worth that. I try to keep this repo as simple as possible. May it's better to just send a nice cleanup PR every once in a while.

**Comment by rejas** [comment]
> That will add another dependency

On the contrary, it will in the end remove two linters (yamllint and markdownlint) and only add one more overall (prettier).

**Comment by MichMich** [comment]
Hmmm... that makes sense.

Now for the discussion, tabs vs spaces. What did you choose spaces? :D

**Comment by rejas** [comment]
> Now for the discussion, tabs vs spaces. What did you choose spaces? :D

I dont have a personal preference for that, it's what most files already used so that there would be less noise. It can be adjusted though in the .editorconfig (even on a per-file-extension-basis, thats why the js and json files still use tabs)

**Comment by MichMich** [comment]
Ok, lets go for this PR and see where it leads....

**Comment by sdetweil** [comment]
are we gonna provide any  info on this .editconfig setting somehwere?  I frankly don't know anything about it and use different editors on different platforms..

I find the tabs/spaces stuff THE most frustrating..   and who cares about trailing spaces? 
i write my code, I test it, and then submit a pr only to have it fail test cause I don't share the same indentation or indentation tool with you all.. 

fix it yourself if u care.  I DON'T

this leads to constant commits with 'fix tabs or spaces'... yeesh what a pollutant. 

and across multiple projects with the same file extensions with different rules its impossible..

**Comment by MichMich** [comment]
AFAIK you don't have to do anything @sdetweil, Prettier will do that for you.

**Comment by sdetweil** [comment]
where??  what do I have to do to invoke prettier?

**Comment by MichMich** [comment]
Nothing. It will automatically run on commit. :)

**Comment by sdetweil** [comment]
how does that happen?  its in the project, not in my git setup

**Comment by rejas** [comment]
> Nothing. It will automatically run on commit. :)

Exactly. As for editorconfig: Most editors automatically recognize that file and use it as a preset for when you edit in the project.

**Comment by sdetweil** [comment]
and how do I find/modify .editorconfig?  never heard of it before.. too much technical debt to find all these settings everywhere.
nano doesn't use it
notepad++  over ssh? 
sublime text?
gedit?

too many editors to name...

**Comment by rejas** [comment]
the .editorconfig file is in the root of the project after this PR.  dont worry if you havent heard of it before. 

most editor have plugins for it to download: https://editorconfig.org/#download and even if your editor doesnt support it, the pre-commit-hook takes care of adjusting the codestyle automatically like I said before. 

this editorconfig isnt something mandatory, it just helps you without asking you to do configure it yourself if you dont want to. 

So if you want to use nano or vi for coding, do so. If you use it and never heard of editorconfig or prettier or modern UI editors, nothign stops you from contributing anyway even afetr this PR.

**Comment by sdetweil** [comment]
ok, there was the key set of words ' the pre-commit-hook'

**Comment by dragonteamart** [comment]
Could be a problem for that automatically correct editor

**Comment by rejas** [comment]
> 
> 
> Ok, lets go for this PR and see where it leads....

so, ready to merge @MichMich ? ;-)

**Comment by MichMich** [comment]
Sorry, thought I already did that. Done now.

**Comment by MichMich** [comment]
Whoops ... it seems Travis has issues now: https://travis-ci.com/github/MichMich/MagicMirror/jobs/339733999

**Comment by rejas** [comment]
Whoops indeed. See https://github.com/MichMich/MagicMirror/pull/2027 for a fix and explanation...

**Comment by easyas314** [comment]
I'm an 'old school' tinkerer and work in mostly back end unix which makes me effectively fluent at bash and vi(m), so this project has been a fun place to stretch new coding understanding and skills. I've been learning about git, repositories, js, node, and (allegedly) better code editors. Related to this merge, I think @sdetweil 's comments were very apropos. I had never heard of "linters" outside the scope of my laundry; until I starting looking at the "modern" javascript world.

On one hand, not caring about coding style is great, especially if I use the perfect text editor -- vi  :-)  -- which I have configured for _my_ preferences of spaces/tabs. This project's objective to keep "accessible to new users" is **terrific**, so a few edits to a text file gets me started. And anything can be created or modified with a simple text editor.

On the other hand, I've been trying to use/learn VS Code as an editor (and I do have the vim extension installed). This merge has shown me VSC is trying to be too smart -- in fact, doing things a beginner to MM probably doesn't even begin to understand -- and it's providing "suggestions" about style that seem to mostly appear as red shaded "squiggles". All this from a refresh of this repository before opening VSC! I actually think the eslint "intelligence" sees all this local repo code (formatted by prettier?) as not conforming to the eslint (?) style.

I don't know how many novice users of MM would use an editor that understands linting, but I thought the perspective would be worth mentioning. The final code in the repository reflects any "pre-commit" stylizing and the end user sees that difference when they next look at the code. (Hopefully, it's not common to change styles' rules.) The shared user community modules have different styles and they appear differently when using a linter aware editor. Though it does look nicer when the shared user community modules seem to follow the same coding style. For a beginner coder, all these nested )}] characters can be difficult to assess and the different styles' placement of these characters with carriage returns conflates the problem. Slightly off topic; maybe a recommended 'linter' for users' public modules?

This merge: I see no .editorconfig file in the root. Should there be one?

@rejas -- VSC doesn't automatically see that file. But, Oh, look, there is a EditorConfig plugin for VSC. (Thanks for the link ... and something else to "config" in my own environment.)

All my comments aside, I love this intentionally open project and very much appreciate the detail and dedication that you've put into it. 🥇

**Pull request merged**
