### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by B1gG**
PR for Fix wrong treatment of `appendLocationNameToHeader` when using `ukmetofficedatahub`

Hello and thank you for wanting to contribute to the MagicMirror project

**Please make sure that you have followed these 4 rules before submitting your Pull Request:**

> 1) Base your pull requests against the `develop` branch.
>
>
> 2) Include these infos in the description:
>  * Does the pull request solve a **related** issue?
>  * If so, can you reference the issue like this `Fixes #<issue_number>`?
>  * What does the pull request accomplish? Use a list if needed.
>  * If it includes major visual changes please add screenshots.
>
>
> 3) Please run `npm run lint:prettier` before submitting so that
> style issues are fixed.
>
>
> 4) Don't forget to add an entry about your changes to
> the CHANGELOG.md file.

**Note**: Sometimes the development moves very fast. It is highly
recommended that you update your branch of `develop` before creating a
pull request to send us your changes. This makes everyone's lives
easier (including yours) and helps us out on the development team.

Thanks again and have a nice day!

### CODE REVIEW

**Comment by rejas** [comment]
Thanks for the PR. Please run `npm run lint:prettier` and resubmit to make the tests turn green.

**Comment by MichMich** [comment]
86
Checking formatting...
87
[warn] CHANGELOG.md
88
[warn] modules/default/weather/providers/ukmetofficedatahub.js
89
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
90

**Comment by B1gG** [comment]
sorry no familiar with node, just found that thing ... will cancel this and open an issue.

**Comment by MichMich** [comment]
You can leave it open if you want. You're very close to the final PR. I'll just do the linting. 👍🏻

**Comment by B1gG** [comment]
lets leave the honors to the experts :)

**Comment by B1gG** [comment]
also, I will suggest including in the docs `ukmetofficedatahub` as a provider, it's not mentioned just `ukmetoffice`

**Comment by rejas** [comment]
Could you reopen it @B1gG that way it is easier to merge it for a third-party ;-)

**Comment by B1gG** [comment]
Yep, not a problem.
BTW, if there is a way for me to help to update the doc, please let me know.

**Comment by MichMich** [comment]
> BTW, if there is a way for me to help to update the doc, please let me know.

You can't send PR's for that as well. There is a link on the bottom of every docs page. 👍🏻

**Comment by B1gG** [comment]
> > BTW, if there is a way for me to help to update the doc, please let me know.
> 
> You can't send PR's for that as well. There is a link on the bottom of every docs page. 👍🏻

Thank you, just submitted the PR. :)

**Pull request merged**
