### PR TITLE
Added more documentation to weather modules

### PR DESCRIPTION
**Pull request by alberttwong**
Added more documentation (specifically examples for common changes) to change weather a different unit like Fahrenheit.

### CODE REVIEW

**Comment by rejas** [comment]
Aren't those units taken from the general section of the config file? So that the docs should be clear to change them there and not in the config of the module?

**Comment by MichMich** [comment]
What @rejas says is correct. By default, the general config will be used. You can overwrite this if you want. It might be good to explain that in this readme. You current change gives the idea that this is the only way to set the unit type.

**Comment by alberttwong** [comment]
I would vote for more explanation in the readme because it's confusing and most variables are localized to the module.

**Comment by MichMich** [comment]
Is this something you will change? Otherwise I'll close this PR for now. Cheers!

**Comment by roramirez** [comment]
Should be add more explain into documentation sections not into the sample configuration.

**Comment by MichMich** [comment]
I close this PR due to inactivity. Please feel free to reopen.

**Pull request closed without merging**
