### PR TITLE
Fix simple-git version for unhandle promise rejection

### LINKED ISSUE #2383: updatenotification exception not handled, 2.14-dev
installed on pi0 today

started with sample config

saw this exception 
```
[28.12.2020 13:19.37.412] [ERROR] (node:18416) UnhandledPromiseRejectionWarning: TypeError: Object.fromEntries is not a function
    at userOptions (/home/pi/MagicMirror.2.14-dev/node_modules/simple-git/src/lib/tasks/log.js:32:19)
    at parseLogOptions (/home/pi/MagicMirror.2.14-dev/node_modules/simple-git/src/lib/tasks/log.js:62:31)
    at Git.log (/home/pi/MagicMirror.2.14-dev/node_modules/simple-git/src/git.js:871:26)
    at sg.git.fetch.status (/home/pi/MagicMirror.2.14-dev/modules/default/updatenotification/node_helper.js:78:13)
    at onSuccess (/home/pi/MagicMirror.2.14-dev/node_modules/simple-git/src/lib/task-callback.js:8:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[28.12.2020 13:19.37.542] [ERROR] (node:18416) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

does simple-git depend on a particular git version?

### PR DESCRIPTION
**Pull request by sdetweil**
fixes #2383

### CODE REVIEW

**Review by rejas — APPROVED** [review]
Looks like your node-ical update is in here too...

**Comment by sdetweil** [comment]
oops.. didn't make a new branch til too late..

**Comment by MichMich** [comment]
You want me to merge including the node-iCal change?

**Comment by sdetweil** [comment]
yes, then u can just close pr #2390

**Comment by MichMich** [comment]
Ah. It seems it has a merge conflict now which I can't fix in my phone.

**Comment by sdetweil** [comment]
fixed

**Pull request merged**
