### PR TITLE
Getting Black Screen

### PR DESCRIPTION
**Pull request by undergroundauth**
App is running perfectly fine 

│ Name │ mode │ status │ ↺ │ cpu │ memory   │
├──────┼──────┼────────┼───┼─────┼──────────┤
│ mm   │ fork │ online │ 0 │ 0%  │ 2.2 MB   │

But it gives a black screen

disabled the screensaver using the mentioned code

but still running the black screen
i am on my TV using HDMI
Please help

#!/bin/bash

NOBLANK="
@xset s noblank
@xset s off
@xset -dpms
"

  # Pretty ANSI text colors
  OFF="\033[0m"
  BOLD="\033[1m"
  DIM="\033[2m"
  RED="\033[1;31m"
  GREEN="\033[1;32m"
  YELLOW="\033[1;33m"
  BLUE="\033[1;34m"

  clear
  printf "\n\n\t $YELLOW           "; date ; printf "$OFF"
  printf "\n $GREEN"
  printf "\t +------------------------------------------------+\n"
  printf "\t |                  no_blank.sh                   |\n"
  printf "\t |                rev Oct 1, 2013                 |\n"
  printf "\t |                                                |\n"
  printf "\t |  by: Jan Zumwalt - net-wrench.com              |\n"
  printf "\t |                                                |\n"
  printf "\t |  This script permanently disables the xsession |\n"
  printf "\t |  screen saver for RASPBIAN PI OS. It allows    |\n"
  printf "\t |  the user to abort before any change is made.  |\n"
  printf "\t +------------------------------------------------+$OFF\n\n"

  printf "\t This program will disable your xsession\n"
  printf "\t screen saver permanently, is this what \n"
  printf "\t you really want to do? $YELLOW<y/n>$OFF"; read -n 1 KEYIN

  if [[ $KEYIN == "N"  ||  $KEYIN == "n" ]]; then
    printf "\n\n\t OK, I quit and did not do anything.\n\n"
    exit 0
  fi

  printf "\n\n\t I intend to modify your current \n"
  printf "\t /etc/xdg/lxsession/LXDE/autostart \n"
  printf "\t I will add the$GREEN GREEN$OFF lines to the file...\n\n"

  printf "$DIM\n"
  pr -t -o 9 /etc/xdg/lxsession/LXDE/autostart
  printf "$OFF$GREEN$NOBLANK" | pr -t -o 9
  printf "$OFF\n\n" 

  printf "\t Is this really what you want to do? $YELLOW<y/n>$OFF"; read -n 1 KEYIN

  if [[ $KEYIN == "N"  ||  $KEYIN == "n" ]]; then
    printf "\n\n\t OK, I quit and did not do anything.\n\n"
    exit 0
  fi

  cat /etc/xdg/lxsession/LXDE/autostart > /etc/xdg/lxsession/LXDE/autostart.`date +%m-%d-%Y_%I:%M:%S`
  printf "\n\t Created backup copy of the autostart file...\n"
  printf "$NOBLANK" >> /etc/xdg/lxsession/LXDE/autostart

  printf "\t Your new file looks like this\n"
  printf "$DIM\n"
  pr -t -o 9 /etc/xdg/lxsession/LXDE/autostart
  printf "$OFF\n\n"

  printf "\t$RED Modified file. Screensaver is now disabled.$OFF\n"

  # required so xterm will not close
  printf "\n\t press any key to exit: "; read -n 1 KEYIN
  printf "\t$GREEN Program ended normaly $OFF\n\n"

> Please send your pull requests the develop branch.
> Don't forget to add the change to CHANGELOG.md.

**Note**: Sometimes the development moves very fast. It is highly
recommended that you update your branch of `develop` before creating a
pull request to send us your changes. This makes everyone's lives
easier (including yours) and helps us out on the development team.
Thanks!

* Does the pull request solve a **related** issue?
* If so, can you reference the issue?
* What does the pull request accomplish? Use a list if needed.
* If it includes major visual changes please add screenshots.

### CODE REVIEW

**Comment by undergroundauth** [comment]
not bale to solve black screen ...please help

**Comment by blackc2004** [comment]
did you run "npm install"?

**Comment by undergroundauth** [comment]
Yes i did

Use `pm2 show <id|name>` to get more details about an app
root@raspberrypi:~# npm install
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.
root@raspberrypi:~#

**Comment by undergroundauth** [comment]
root@raspberrypi:~# pm2 restart mm
Use --update-env to update environment variables
[PM2] Applying action restartProcessId on app [mm](ids: 0)
[PM2] [mm](0) ✓
┌──────┬──────┬────────┬───┬─────┬──────────┐
│ Name │ mode │ status │ ↺ │ cpu │ memory   │
├──────┼──────┼────────┼───┼─────┼──────────┤
│ mm   │ fork │ online │ 1 │ 0%  │ 2.3 MB   │
└──────┴──────┴────────┴───┴─────┴──────────┘

**Comment by blackc2004** [comment]
are you in "~/MagicMirror" when you run it?

**Comment by undergroundauth** [comment]
Yes running in MagicMirror

pi@raspberrypi:~/MagicMirror $ npm install
npm ERR! Linux 4.4.50-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! path /home/pi/MagicMirror/node_modules/electron
npm ERR! code EISGIT

npm ERR! git /home/pi/MagicMirror/node_modules/electron: Appears to be a git repo or submodule.
npm ERR! git     /home/pi/MagicMirror/node_modules/electron
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/MagicMirror/npm-debug.log
pi@raspberrypi:~/MagicMirror $

**Comment by undergroundauth** [comment]
not able to solve the black screen please help

**Comment by undergroundauth** [comment]
i have reached to a point where the services are online and logs are generated fine 
the moment i give 'pm2 start mm'

services start and i get a black screen and nothing happens, i dont know how to solve this problem, many answers are there but nothing seems to work..

Please help



root@raspberrypi:~# pm2 restart mm
Use --update-env to update environment variables
[PM2] Applying action restartProcessId on app [mm](ids: 0)
[PM2] [mm](0) ✓
┌──────┬──────┬────────┬───┬─────┬──────────┐
│ Name │ mode │ status │ ↺ │ cpu │ memory   │
├──────┼──────┼────────┼───┼─────┼──────────┤
│ mm   │ fork │ online │ 0 │ 0%  │ 2.3 MB   │
└──────┴──────┴────────┴───┴─────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
root@raspberrypi:~#

**Comment by MichMich** [comment]
Please refer to http://forum.magicmirror.builders for support and troubleshooting.

I'm closing this issue for now. If you feel this issue should remain open, please let me know.

**Pull request closed without merging**
