### PR TITLE
multiple icon support for calendars

### PR DESCRIPTION
**Pull request by fewieden**
* Does the pull request solve a **related** issue? Yes
* If so, can you reference the issue? https://forum.magicmirror.builders/topic/2078/calendar-module-multiple-icons

### CODE REVIEW

**Comment by fewieden** [comment]
somehow i messed up the commit message

**Comment by MichMich** [comment]
Could you show a screenshot of what this would look like? I'm not sure I really understand the purpose of this PR.

**Comment by fewieden** [comment]
```
config: {
  calendars: [
    {
      symbol: ["calendar-check-o", "car"],
      url: "webcal://www.calendarlabs.com/templates/ical/US-Holidays.ics"
    },
    {
      symbol: "truck",
      url: "webcal://www.calendarlabs.com/templates/ical/Germany-Holidays.ics"
    }
  ]
}
```

**Comment by MichMich** [comment]
Merged!

**Pull request merged**
