### PR TITLE
Add french translation for "feels"

### PR DESCRIPTION
**Pull request by Ybbet**
> Please send your pull requests the develop branch.
> Don't forget to add the change to CHANGELOG.md.

**Note**: Sometimes the development moves very fast. It is highly
recommended that you update your branch of `develop` before creating a
pull request to send us your changes. This makes everyone's lives
easier (including yours) and helps us out on the development team.
Thanks!

* Does the pull request solve a **related** issue?
* If so, can you reference the issue?
* What does the pull request accomplish? Use a list if needed.
* If it includes major visual changes please add screenshots.

### CODE REVIEW

**Comment by fewieden** [comment]
It seems like something went wrong here. ~230 changed files for french translations?

**Comment by Ybbet** [comment]
It was from the merge with your develop branch. It seems that the files were not in UTF8 on my develop branch.

**Comment by Ybbet** [comment]
Revert done.

**Comment by MichMich** [comment]
Please send a new PR with only the updated translation file. Thanks!

**Pull request closed without merging**
