### PR TITLE
added test for calendar recurring event with checks the correct date displayed

### PR DESCRIPTION
**Pull request by khassel**
related to #2752

This additional test checks if the event date is correctly displayed.

The new test will fail at the moment because the current `develop` branch is broken with https://github.com/MichMich/MagicMirror/pull/2748.

So may merging should be delayed until #2752 is fixed with a new PR.

### CODE REVIEW

**Comment by khassel** [comment]
converted this back to `draft` because running the tests seems dependent on timezone, so this has to be improved.

**Comment by khassel** [comment]
now ready for review, it is correct that the tests are failing so as already said above merging should be delayed until #2752 is fixed with a new PR.

**Comment by sdetweil** [comment]
fix for 2752 submitted, #2755

**Comment by khassel** [comment]
thanks, new tests are working with https://github.com/MichMich/MagicMirror/pull/2755, so this can be merged **after** https://github.com/MichMich/MagicMirror/pull/2755

**Review by rejas — APPROVED** [review]

**Comment by MichMich** [comment]
@rejas @khassel The automated tests are super flaky. Can get this PR to run without issues. Any idea where to look?

**Comment by khassel** [comment]
these are new tests introduced after `develop` was broken. So it is correct that these 12 tests fails. I will merge current `develop` into this so tests should run afterwards.

**Comment by MichMich** [comment]
Thanks @khassel. Appreciated!

**Pull request merged**
