### PR TITLE
Add forecast and forecast/daily support to new weather module

### LINKED ISSUE #1513: New weather module: forecast and forecast/daily support
Hi everybody,
I implemented the support for forecast and forecast/daily using openweathermap in PR #1514. As I did not have a apiKey to test the forecast/daily part, I downloaded a sample file from their website and included it in my testing. I am not sure if all cases are handled well, please do check, if you find any other issues.

Thank you very much @fewieden and @vincep5 for you hints and support!

Also before merging my code, we should discuss, if my code is looking as it should:

This part appears twice in the hourly forecast part and a third time (similarly) in the daily forecast part.
```
minTemp.push(forecast.main.temp_min);
maxTemp.push(forecast.main.temp_max);

if (forecast.hasOwnProperty("rain")) {
	if (this.config.units === "imperial" && !isNaN(forecast.rain["3h"])) {
		rain += forecast.rain["3h"] / 25.4;
	} else if (!isNaN(forecast.rain["3h"])){
		rain += forecast.rain["3h"];
	} else {
		rain += 0;
	}
} else {
	rain += 0;
}
```
Have a nice weekend!

### PR DESCRIPTION
**Pull request by fwitte**
Resolve #1513.

### CODE REVIEW

**Comment by fewieden** [comment]
I will have a look this week or weekend and test it.

**Comment by MichMich** [comment]
@fewieden Please tag me when it's tested and ready to merge. Thanks!

**Comment by fewieden** [comment]
@MichMich @fwitte I had a look and it works with the old key for the daily and hourly endpoint. I tested the default configs and also compared it to the old weatherforecast module (see screenshots).

However what I found is that the icons for the hourly forecast do not match the old module, the missing logic should be https://github.com/MichMich/MagicMirror/blob/master/modules/default/weatherforecast/weatherforecast.js#L371-L373:
```js
// Since we don't want an icon from the start of the day (in the middle of the night)
// we update the icon as long as it's somewhere during the day.
if (hour >= 8 && hour <= 17) {
  forecastData.icon = this.config.iconTable[forecast.weather[0].icon];
}
```
Hourly forecast icon mismatch
new
Daily forecast
old key

**Comment by fwitte** [comment]
Yes, that's what I was concerned about. What if the first value of forecast is after 17:00? The 3h-forecast Endpoint does not start on the next day, but always on the next full hour. I suggest using the time-window 09:00-17:00 for all days and if the time-window for today has passed already, using the icon of the next hour. What are your suggestions?

**Comment by MichMich** [comment]
Hi @fwitte, I think best I idea is to implement something that makes sense in your opinion. We can always do a pull request in the future to improve.

**Comment by fwitte** [comment]
Okay, I will look into that next week.

**Comment by MichMich** [comment]
@fwitte Any progress on this? (no rush, just curious)

**Comment by fwitte** [comment]
Unfortunately not, too much stuff at work. I will have some time tomorrow and try to post my solution as soon as possible.

**Comment by MichMich** [comment]
No worries! Looking forward to your solution.

**Comment by fwitte** [comment]
Well guys, I am very sorry for my delay! Hopefully before this weekend, I am done with a milestone at work. Then there should be time for MagicMirror again! :)

**Comment by vincep5** [comment]
Can we get this merged soon?  I plan on testing it out myself again

**Comment by MichMich** [comment]
@vincep5 I'm waiting for @fwitte's final contributions on this commit before I can merge.

**Comment by fwitte** [comment]
Well, I am very sorry for any inconvenience, I did not have my pi around the last days and weeks and was occupied with too much other stuff. I just uploaded a solution for the issue brought up by @fewieden. Thanks for your support!

**Comment by MichMich** [comment]
Awesome @fwitte! Is this now ready to merge?

**Comment by fwitte** [comment]
Looks like this now: 
grafik

Notice: For the first day, the weather icon will not be the "day-icon", if it is already past 17:00.

**Comment by MichMich** [comment]
Thank you very much, @fwitte! Merged.

**Pull request merged**
