### PR TITLE
fix full day recurring events not showing

### PR DESCRIPTION
**Pull request by sdetweil**
- Does the pull request solve a **related** issue?
- If so, can you reference the issue?
#2110 #2111 #2118 

- What does the pull request accomplish? Use a list if needed.
check for full day event and NOT adjust timezone time (as it should be midnight local), before calling rrule to get the events from the rule. adjusting the time causes today to be skipped as its past midnight.

### CODE REVIEW

**Comment by sdetweil** [comment]
@MichMich what is wrong here, travis builds failed no env set..  that is not a code problem

**Comment by sdetweil** [comment]
@MichMich   this build failed cause prettier failed in travis

The command "npm run test:prettier" exited with 1.

**Comment by MichMich** [comment]
I fixed the issue. For future reference:
`npm run test:prettier` shows the issues, `npm run lint:prettier` fixes the issues. :)

**Comment by sdetweil** [comment]
I thought the whole point of the husky hook was to not have to run anything?

I don't see where the problem was

**Comment by rejas** [comment]
Yeah that should happen automatically when you git commit (see https://git-scm.com/docs/githooks#_pre_commit) Do you invoke git with --no-verify ?

**Comment by sdetweil** [comment]
@rejas  no.

it did get invoked on my desktop, not on my Chromebook. it looked like a normal precommit hook for prettier. ( on my last commit/push)

trying to figure out what didn't work now. this is 1st commit / push since the prettier stuff was added in 2.12

I added it via precommit hook to all my repos

**Comment by sdetweil** [comment]
ok, this is my fault.. when i added the changelog on my chromebook, the hook did not work. and i pushed the bad file.
when I went to my desktop, i forgot the changelog, so when the hook fired it only processed the js file..

sorry.. still didn't see the error in the job log..

**Pull request merged**
