### PR TITLE
Calendar: repeating event rrule & exdate fixes

### PR DESCRIPTION
**Pull request by mattdb**
Previously, if a repeating event had specific recurrences deleted (exdate) or modified (rrule), the calendar would not display those changes, instead still showing canceled events, or events with their originally scheduled times or titles. This PR makes handling these types of exceptions to calendars much more robust.

In order to do this, I:
* updated calendar's vendored ical.js
* made extensive changes to the calendar fetcher within the logic branch where an event has an rrule attached
* extracted title-parsing logic into a function (`getTitleFromEvent`) since modified events may need to re-parse their title.

I believe this will solve and/or make progress on a slew of calendar-related issues, including:
* #1105 (Which seems to have become the omnibus issue for the ical parser)
* #1070 
* #1228 
* #565 
* #576

The updated ical.js should also help with comma-separated EXDATEs, as noted in peterbraden/ical.js#84 and peterbraden/ical.js#76

### CODE REVIEW

**Comment by mattdb** [comment]
Doh! That conflict just got pulled in as I was writing up the PR. I'll work on resolving.

**Comment by mattdb** [comment]
Investigated the conflict-- #1699 made manual changes to the vendored ical.js/node-ical.js file, but similar improvements were already included in the upstream file that I am updating here. In my opinion, best to stay with the "official" upstream version as long as it resolves the issue the "unofficial" modification was addressing.

**Comment by mattdb** [comment]
Updating to the up-to-date ical.js does offer one complication: it uses rrule, rather than rrule-alt, which MagicMirror manually switched to a while back. Since that switch, rrule-alt has not been updated, but rrule has seen quite a bit of updating. 

I propose we hop back on the rrule train to handle bug fixes like all of the myriad ical formatting quirks, etc.

However, we can't remove rrule-alt from the package's dependencies because some 3rd party modules have come to expect it (MMM-CalendarExt is the one I ran into, at least).

**Comment by MichMich** [comment]
> I propose we hop back on the rrule train to handle bug fixes like all of the myriad ical formatting quirks, etc.
Agree. 

>However, we can't remove rrule-alt from the package's dependencies because some 3rd party modules have come to expect it (MMM-CalendarExt is the one I ran into, at least).
What's you suggested solution for this?

**Comment by MichMich** [comment]
I've merged your PR for now. We can always add extra PR's to solve open or created issues.

**Pull request merged**
