### PR TITLE
Fix travis error

### PR DESCRIPTION
**Pull request by rejas**
Happened because I ran the initial prettier call and afterwards a new feature was merged into develop. Therefor the compliments PR wasnt initally "prettified". This fixes the js/css and makes travis happy again

### CODE REVIEW

**Comment by hangorazvan** [comment]
Same error as in #2026 

`Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'currentweather' in Remember that spiders are more afraid of you, than you are of them.`

**Comment by rejas** [comment]
No, in #2021 we have a runtime error whos fix hopefully gets soon merged via https://github.com/MichMich/MagicMirror/pull/2026
Here we had a travis error due to prettier warnings...

**Comment by hangorazvan** [comment]
For me are the same:

First:
`Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'currentweather' in Some of life's best lessons are learnt at the worst times.`

Second:
`Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'currentweather' in Remember that spiders are more afraid of you, than you are of them.`

#2026 also not working

**Comment by rejas** [comment]
Isee. But still: this here isnt the PR for fixing those TypeErrors. This PR here fixed https://github.com/MichMich/MagicMirror/pull/2013#issuecomment-633661959
So why are you commenting here?

**Comment by hangorazvan** [comment]
Because MichMich merged commit 8a3a4d6 which is related to this issue

**Comment by rejas** [comment]
And that commit https://github.com/MichMich/MagicMirror/commit/8a3a4d6fae1cd936363e5f9cba5d98d36a5f3b2e has nothing to do with those TypeErrors you keep posting in this PR. Please stop putting noise in here.

**Comment by hangorazvan** [comment]
sorry if I bothered you
stay calm, stay safe!

**Comment by rejas** [comment]
no worries. stay healthy :-)

**Pull request merged**
