### PR TITLE
Merge pull request #394 from MichMich/develop / Install MM2 on Rasbian Jessie Lite

### PR DESCRIPTION
**Pull request by pcp47**
Updated
[Install.Magic.Mirror.2.Jessie.Lite.txt](https://github.com/MichMich/MagicMirror/files/421220/Install.Magic.Mirror.2.Jessie.Lite.txt)

> Please send your PR's the develop branch. 
> Don't forget to add the change to changelog.md.

Install MM2 on Rasbian Jessie Lite

Release 2.0.4

### CODE REVIEW

**Comment by CatoAntonsen** [comment]
I tried this on a fresh install of Jessie Lite on a RPI2, but get a problem finding this package:

sudo apt-get install libnss

Is it "libnss3"?

**Comment by lanian2219** [comment]
Yes, my mistake. I change it in the file. Thanks.

sudo apt-get install libnss3
is the right command

**Comment by CatoAntonsen** [comment]
I also had to change:

sudo nano /etc/xdg/lxsession/LXDE-pi/autostart

to

sudo nano /etc/xdg/lxsession/LXDE/autostart
(removing the "-pi" in the last folder name)

**Comment by pcp47** [comment]
Yes, my mistake. I change it in the file. Thanks.

sudo apt-get install libnss3
is the right command

**Comment by pcp47** [comment]
Thanks @CatoAntonsen i forgot

**Comment by pcp47** [comment]
I changed it. Works?

**Comment by CatoAntonsen** [comment]
Another missing step is to run "sudo raspi-config" and change boot to desktop without logging in...?

**Comment by CatoAntonsen** [comment]
Yes, it works with the three changes I've mentioned. :)

**Comment by pcp47** [comment]
Okay, thanks. I changed the Mistake´s in the file.

**Comment by MichMich** [comment]
Thanks for your guide. Awesome work! I think it's better suited to be placed in the [wiki](https://github.com/MichMich/MagicMirror/wiki) in stead of the main repository.

**Comment by pcp47** [comment]
@MichMich Thanks. ld you add it pure or should I do that?

**Comment by MichMich** [comment]
You can put it here: https://github.com/MichMich/MagicMirror/wiki/Jessie-Lite-Installation-Guide

**Comment by pcp47** [comment]
Finish: https://github.com/MichMich/MagicMirror/wiki/Jessie-Lite-Installation-Guide

**Comment by MichMich** [comment]
Awesome work! Thank you very much! :)

**Pull request closed without merging**
