### PR TITLE
Add Regexp possibility to titleReplace

### PR DESCRIPTION
**Pull request by tosti007**
Check if the given needle is a regexp, if so create one and use it instead.

### CODE REVIEW

**Comment by roramirez** [comment]
This change isn't pass the Travis CI. Please use grunt to check the errors.

**Comment by tosti007** [comment]
Yea i did, was a trailing space in a comment :I

**Comment by MichMich** [comment]
Awesome. Please add an updated changelog. Thanks!

**Comment by MichMich** [comment]
Thanks!

**Comment by tosti007** [comment]
You're welcome!

**Pull request merged**
