### PR TITLE
added the ability to display enclosure images of newsfeed items

### PR DESCRIPTION
**Pull request by StephanSST**
With configuration option 'showEnclosureImage' now the enclosure image of a newsfeed items will be displayed. To force the max width of the news item there is a config option 'enclosureImageWidth' which sets the width of the html image tag.

### CODE REVIEW

**Comment by MichMich** [comment]
Since this is a visual change: could you please make a screenshot for me so I can check what it looks like?

**Comment by StephanSST** [comment]
Here is the screenshot. The new newsfeed module is in the top_right spot.

newsfeedwithimage

**Comment by StephanSST** [comment]
I just found a bug a fixed it. I missmatched height and with in the newsfeed.js file. I already fixed it in my branch, do I have to pull request again? Or can I somehow push it to your dev branch? I can see it here, it was commit e239e26, is it already included?

**Comment by MichMich** [comment]
Hm... to be honest, that could use some styling. It's currently a bit unpolished. If styling isn't your cup of tea, I suggest to collaborate with someone on the forum.

**Comment by MichMich** [comment]
I close this PR for now. Please feel free to resubmit a PR when the styling has changed. Your contribution is more than welcome!

**Pull request closed without merging**
