### PR TITLE
Added different compliments for different times of the day

### PR DESCRIPTION
**Pull request by paviro**
Hey :)
I added the possibility to define different compliments based on the current time. Maybe you find this as useful as I do.

Regards,
Paul

### CODE REVIEW

**Comment by MichMich** [comment]
Awesome update! Thanks for your work! :)

**Comment by paviro** [comment]
Glad you like it! I started building my own mirror today, thank you for the inspiration! :)

**Comment by MichMich** [comment]
Keep me posted on your work! :+1:

**Comment by paviro** [comment]
I will! :) Definitely going to add a motion sensor to save some energy :D
img_20150108_230834

**Pull request merged**
