### PR TITLE
Newsfeed cleanup

### PR DESCRIPTION
**Pull request by rejas**
Cleaned up the newsfeed module:
- Added a UI warning if the newsfeed URL is invalid
- Added general translatable string for module errors while doing that
- Use es6 notation in the module
- Added some tests

### CODE REVIEW

**Comment by khassel** [comment]
hm, you really forgot the changelog? ;)

**Comment by rejas** [comment]
> hm, you really forgot the changelog? ;)

nope, still working on it :-)

**Comment by rejas** [comment]
Ready for merging @MichMich if you or anyone got no objections?

**Comment by sdetweil** [comment]
did u see the latest commentary about multiple sources not producing output from all?  under MMM-NewsFeedTicker topic. both broken

**Comment by rejas** [comment]
No, was that in the forums?

**Comment by sdetweil** [comment]
yes
https://forum.magicmirror.builders/topic/14784/mmm-newsfeed-ticker-hangs/32?page=4

**Comment by sdetweil** [comment]
looks like this might have been user error..

**Comment by rejas** [comment]
Yes, looks like that he really forgot to set the brackets correctly :-)

**Comment by khassel** [comment]
PR LGTM

**Comment by hangorazvan** [comment]
[2021-03-23 11:25:38.560] [ERROR] Whoops! There was an uncaught exception...
[2021-03-23 11:25:38.730] [ERROR] TypeError: self.broadcastItems is not a functi
on
    at FeedMe.<anonymous> (E:\OneDrive\MagicMirror\modules\default\newsfeed\news
feedfetcher.js:71:9)
    at FeedMe.emit (events.js:198:13)
    at SAXStream._parser.parser.emit.args [as emit] (E:\OneDrive\MagicMirror\nod
e_modules\feedme\dist\feedme.js:26:29)
    at SAXParser.SAXStream._parser.onend (E:\OneDrive\MagicMirror\node_modules\s
ax\lib\sax.js:190:10)
    at emit (E:\OneDrive\MagicMirror\node_modules\sax\lib\sax.js:624:35)
    at end (E:\OneDrive\MagicMirror\node_modules\sax\lib\sax.js:667:5)
    at SAXParser.end (E:\OneDrive\MagicMirror\node_modules\sax\lib\sax.js:154:24
)
    at SAXStream.end (E:\OneDrive\MagicMirror\node_modules\sax\lib\sax.js:248:18
)
    at XMLFeedParser._final (E:\OneDrive\MagicMirror\node_modules\feedme\dist\xm
lfeedparser.js:163:21)
    at callFinal (_stream_writable.js:617:10)
[2021-03-23 11:25:38.821] [ERROR] MagicMirror will not quit, but it might be a g
ood idea to check why this happened. Maybe no internet connection?
[2021-03-23 11:25:38.969] [ERROR] If you think this really is an issue, please o
pen an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

[2021-03-23 11:29:48.657] [ERROR] (node:7100) UnhandledPromiseRejectionWarning:
TypeError: fetcher.url is not a function
    at E:\OneDrive\MagicMirror\modules\default\newsfeed\node_helper.js:57:19
    at E:\OneDrive\MagicMirror\modules\default\newsfeed\newsfeedfetcher.js:89:5
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2021-03-23 11:29:48.674] [ERROR] (node:7100) UnhandledPromiseRejectionWarning:
Unhandled promise rejection. This error originated either by throwing inside of
an async function without a catch block, or by rejecting a promise which was not
 handled with .catch(). (rejection id: 7)

**Comment by rejas** [comment]
This doenst look like the current develop branch, where did you get it from?

**Comment by hangorazvan** [comment]
why? what you think is wrong?

**Comment by hangorazvan** [comment]
maybe when I change to ES5 for iOS 9 compatibility

**Comment by rejas** [comment]
what branch  are you running? what does "git status" say?

**Comment by hangorazvan** [comment]
[2021-03-23 11:53:26.837] [LOG]   Starting MagicMirror: v2.15.0-develop

**Comment by hangorazvan** [comment]
Solved, there is an error on ES5 transform, thank you and sorry

**Comment by hangorazvan** [comment]
But, also I see that at least two of configs: lengthDescription and hideLoading are ignored

**Comment by rejas** [comment]
Hideloading is there: https://github.com/MichMich/MagicMirror/blob/10dc315f3b96ebb5e980e47a21011d44bb9da979/modules/default/newsfeed/newsfeed.js#L189
lengthDescription is there: https://github.com/MichMich/MagicMirror/blob/10dc315f3b96ebb5e980e47a21011d44bb9da979/modules/default/newsfeed/newsfeed.js#L170

**Pull request merged**
