### PR TITLE
Testing default modules

### PR DESCRIPTION
**Pull request by roramirez**

### CODE REVIEW

**Comment by MichMich** [comment]
Not sure if it's a good idea to hardcode all the tets in the tests. This way the text breaks whenever we change the text. What's the common practice for things like this?

**Comment by roramirez** [comment]
No, its not a common practice. I want only demonstrated if not set modules into config.js file  the defaults messages are displayed.

I can't find other way to check this. Perhaps just one test about these can be good.

**Comment by MichMich** [comment]
In that case I don't think I should merge this PR. What do you think?

**Comment by nhubbard** [comment]
@MichMich @roramirez You could pull in the English translations, or do it like we do it with the translation tests.

**Comment by roramirez** [comment]
Sorry @nhubbard I don't know what do you mean. Can you explain more?

@MichMich I think should be have only one test  of all these tests
 * The message MagicMirror title
 * The message create file config
 * The message See more information in README
 * The message recomended to use a linter for Javascript to check configuration
 * The text Michael's website

or if some guy on the testing club want to say something. cc @qistoph @morozgrafix

**Comment by fewieden** [comment]
I guess he means reading the file with fs module and compare the texts which are displayed on the mirror dinamically

**Comment by nhubbard** [comment]
@fewieden Spot on.

**Comment by nhubbard** [comment]
@roramirez Are you still working on this?

**Comment by roramirez** [comment]
Yes, I'm awaiting for define what kind of test we want for this case.

Do you want take this Pull Request to add some else?

**Comment by nhubbard** [comment]
@roramirez You should refactor the tests to use the values from the English translations, or, if you're feeling ambitious, all of our supported languages.

**Comment by roramirez** [comment]
The use of translations here dont have any sense.

The tests case is for proof when is not set `modules` in config.js is show the follow screen. 

The idea is to choice one test case the mentioned before or all them. No place to me change the essential sense of proof.

screen shot 2017-02-27 at 11 31 15

**Comment by nhubbard** [comment]
@roramirez We should use the English translations for the `helloworld` module when testing it.

**Comment by nhubbard** [comment]
cc @MichMich

**Comment by roramirez** [comment]
@nhubbard Yes but still a problem with use a translation there. If fail the load config on startup we use helloworld for show this message. If fail config cannot established the configs variables therefore we need get locale language from the system (app electron) or webbrowser (node serveronly)

If you have the more clear the idea, why  you take from this Pull Request and posts some code here?.

PS: I insist, is too much load for a simple test. After we'll can add add more ideas, topics, areas, bla bla about what kind tests are need it add.   Also, you are invited to improve the test suite in forum topic and Trello board https://forum.magicmirror.builders/topic/1456/test-suite-for-magicmirror

**Comment by MichMich** [comment]
Guys, what shall we do with this PR?

**Comment by roramirez** [comment]
I remove the tests with much hard code. I keep:

- The message MagicMirror title
- The text Michael's website

The main goal this test is OK.

There are proposes include other things BUT all these is another matter. Anybody can send a Pull Request  with new test for include on testsuite or improve the testsuite.

**Comment by fewieden** [comment]
In my oppinion this doesn't solve the concerns expressed by @nhubbard and me

**Comment by nhubbard** [comment]
@fewieden @roramirez I'll look into this when I have free time. FIRST Districts are coming up and I will be very busy then.

**Comment by MichMich** [comment]
What are we gonna do with this PR?

**Comment by roramirez** [comment]
Hey guys,  For me this PR is too much talk, "Talk is cheap. Show me the code"

if I could aproved I'll would. Is just simple test.  If somebody have a propose additional for this especific test case is free to add a new Pull Request in the future

**Comment by MichMich** [comment]
I'll just merge this for now. We can always improve on this later.

**Pull request merged**
