### PR TITLE
 updates for libc6++ on pi 0, node 10

### PR DESCRIPTION
**Pull request by sdetweil**
updating to handle downlevel libc6++ on jessie

### CODE REVIEW

**Comment by MichMich** [comment]
Hi Sam, it seems this branch has conflicts.

**Comment by sdetweil** [comment]
we need this

**Comment by sdetweil** [comment]
This does not fail when run locally

**Comment by MichMich** [comment]
Will look into all the failing Travis builds tomorrow. Need to be fixed before I can release the next master (Jan 1st).

**Comment by sdetweil** [comment]
Cool. I pulled latest develop, did npm install, and ran the two test suites. Both worked 

The failure is some timeout problem with weather test cases.

**Comment by MichMich** [comment]
See: https://github.com/MichMich/MagicMirror/issues/1840

**Pull request merged**
