### PR TITLE
Andogit7 mm

### PR DESCRIPTION
**Pull request by andogit7**
> Please send your pull requests the develop branch.
> Don't forget to add the change to CHANGELOG.md.

**Note**: Sometimes the development moves very fast. It is highly
recommended that you update your branch of `develop` before creating a
pull request to send us your changes. This makes everyone's lives
easier (including yours) and helps us out on the development team.
Thanks!

* Does the pull request solve a **related** issue?
* If so, can you reference the issue?
* What does the pull request accomplish? Use a list if needed.
* If it includes major visual changes please add screenshots.

### CODE REVIEW

**Comment by MichMich** [comment]
Can you explain this change? Why did the color change?

**Comment by MichMich** [comment]
Can you share a screenshot of the before and after?

**Comment by andogit7** [comment]
Here's the before screenshot - note the black clock perimeter.

image

Updated screenshot with white perimeter. The bug fix for issue 611 specifies a black perimeter but I'm not sure why black was chosen and not white?

image

**Comment by MichMich** [comment]
Ah, that explains it. It has a border because without it there were some HTML rendering quirks. Since 99% of the magic mirrors have a black background, this border isn't visible (as it should be). 

We might want to use `rgba(0,0,0,0.01)` as an alternative color.

**Comment by andogit7** [comment]
OK, I've made the change, but I can now see some numbers appearing in the border (when set to 2px). Increasing this to 50px, I can see this is "3,6,9,12". How do I remove this? 

image

thanks Rob

**Comment by MichMich** [comment]
Hmm.. no idea where these come from.

**Comment by andogit7** [comment]
Closed. Will re-open new pull request

**Pull request closed without merging**
