### PR TITLE
Develop hidden module update restriction

### PR DESCRIPTION
**Pull request by Alvinger**
> Please send your pull requests the develop branch.
> Don't forget to add the change to CHANGELOG.md.

**Note**: Sometimes the development moves very fast. It is highly
recommended that you update your branch of `develop` before creating a
pull request to send us your changes. This makes everyone's lives
easier (including yours) and helps us out on the development team.
Thanks!

- Does the pull request solve a **related** issue?
- If so, can you reference the issue?
- What does the pull request accomplish? Use a list if needed.
- If it includes major visual changes please add screenshots.

### CODE REVIEW

**Comment by rejas** [comment]
Hi @Alvinger thanks for the PR but I am wondering what is it doing? It seems to be fixing stuff and adding stuff without explaining it. The changelog entry isnt very specific and the PR title neither. If this changes more than one thing please consider submitting a PR for each, that makes it easier to review it.
Also: why change lets to var and "=>" to function all over the place?

**Comment by Alvinger** [comment]
Hi,
Sorry. I talked with sdetweil about some bugs in the calendar logic with recurring events. Please drop the PR.
J

Johan Alvinger | Västerled 184, 16772 Bromma | johan@alvinger.com | +46767798870

**Comment by sdetweil** [comment]
@rejas  the ()=> to function() is because he wants to run on IOS 9.5 which doesn't support it.

**Comment by sdetweil** [comment]
the calendar fixes do not work for sharing events cross timezone and locale

**Comment by MichMich** [comment]
This PR has A LOT of changes but zero to none info on what it does. @sdetweil is this something I should merge?

**Comment by sdetweil** [comment]
no..  the calendar side we are still working thru. i don't think we want to change back to function() from arrow => 

he wants older IOS platform,  but u support PI..

**Comment by MichMich** [comment]
Ok. Closing this for now. If you are resubmitting a PR, please add some more info and try to make the PR as compact as possible. Thanks!

**Pull request closed without merging**
