### PR TITLE
Weather - forecast change day of week

### PR DESCRIPTION
**Pull request by flopp999**
change name of day to today and tomorrow
added text to changelog.md

### CODE REVIEW

**Comment by flopp999** [comment]
I may have done a mistake here
This PR is based on Develop but the PR are against Develop

**Comment by rejas** [comment]
Please run `lint:prettier` to fix code style issues that break the travis tests.

**Comment by flopp999** [comment]
> Please run `lint:prettier` to fix code style issues that break the travis tests.

I have done this on the website, is it possible to do this on the web?
sorry, but I am pretty new to use github

**Comment by rejas** [comment]
:-) Are you familiar with how git works?

**Comment by flopp999** [comment]
> :-) Are you familiar with how git works?

not very, but I will try it now :)

**Comment by flopp999** [comment]
> :-) Are you familiar with how git works?

I have no idea how to fetch my PR, anyone can help me with the command?

I have fetched Develop branch

**Comment by flopp999** [comment]
I have now manually made the lines prettier

**Comment by rejas** [comment]
Will ty to guide you although I am in  a meeting:
- First, you fork the repository in github. That has already happened I see
- Now run in your command line on your pc in a directory of your choice (assuming you have "git" command line tools installed):
`git clone https://github.com/flopp999/MagicMirror.git`
- Now you have your copy of Magicmirror on your PC and can work on it.
- Depending on your OS and expertise it makes sense to use a graphical tool to help you with git, I recommend gitkraken or sourcetree.

**Comment by rejas** [comment]
Once you have done this we can go further together, ghot to go to a meeting now.

**Comment by MichMich** [comment]
I fixed the linter issues, but Travis is still failing. 

It seems one of the tests is still expecting the weather to display all days in full format. So it is failing. 

The test needs to be adjusted to the new behaviour. See: https://github.com/MichMich/MagicMirror/blob/master/tests/e2e/modules/weather_spec.js#L185-L194

**Comment by flopp999** [comment]
> I fixed the linter issues, but Travis is still failing.
> 
> It seems one of the tests is still expecting the weather to display all days in full format. So it is failing.
> 
> The test needs to be adjusted to the new behaviour. See: https://github.com/MichMich/MagicMirror/blob/master/tests/e2e/modules/weather_spec.js#L185-L194

I have now change the "const days"

**Review by rejas — APPROVED** [review]
Looks good. Nice idea and work!

**Comment by MichMich** [comment]
Merged! Thanks for your contribution.

**Pull request merged**
