### PR TITLE
Refactor common weather methods into utils class

### PR DESCRIPTION
**Pull request by rejas**

### CODE REVIEW

**Comment by rejas** [comment]
so why not merge it directly ;-)

**Comment by khassel** [comment]
well, from the new `Collaboration.md` (which you approved and btw is still unmerged ...) :

> wait for all approvals requested (or the author decides something different in the comments)

you requested more than 1 ...

**Comment by rejas** [comment]
> well, from the new `Collaboration.md` (which you approved and btw is still unmerged ...) :


> > wait for all approvals requested (or the author decides something different in the comments)
> 
> you requested more than 1 ...

true true :-) so, in that case i shouldnt have added any reviewers. I assume you get notifications for new PRs anyway like I do.

as for the collaboration.md, waiting for @sdetweil for his review too, just liek you did here :-)

**Comment by khassel** [comment]
> as for the collaboration.md, waiting for @sdetweil for his review too, just liek you did here :-)

nearly, you added him there, not I ...

**Comment by rejas** [comment]
I thought for that PR it would make sense to have his "blessing" too

**Comment by khassel** [comment]
understood ;-)

**Pull request merged**
