### PR TITLE
Add support for reloading the server when you modify a file

### PR DESCRIPTION
**Pull request by alexiri**
As discussed in #549.

### CODE REVIEW

**Comment by MichMich** [comment]
Not sure what to do with this PR. Is it still relevant?

**Comment by alexiri** [comment]
Hi @MichMich, I'm not sure why you think it wouldn't be relevant any more. Has this been implemented some other way?

**Comment by roramirez** [comment]
I think is relevant when do you work in develop mode. I testing the patch but I not sure whats files are observed for reload. The modules included by default not reload in case of changed.

**Comment by alexiri** [comment]
@roramirez the `reload` module doesn't watch any files, it only reloads the web page if the server gets restarted. I use [supervisor](https://github.com/petruisfan/node-supervisor) to watch the files for changes like this: `supervisor -e 'node,js,json,css' serveronly`

When a file changes, supervisor restarts the server and then the reload module sees that and reloads the page.

**Comment by MichMich** [comment]
Reloading can be done via PM2, which is included in the installer now. Due to the high impact change, I close this PR for now. Feel free to reopen if you think it could use improvement.

**Pull request closed without merging**
