### PR TITLE
configMerge() and Correct test of Compliments module

### PR DESCRIPTION
**Pull request by bugsounet**
PR Number: 16/16... configMerge()

related to [#2130](https://github.com/MichMich/MagicMirror/issues/2130) and others...

1) If you don't want to respond in public ... find my mail ...
2) because i'm nice ... i will recreate it... but: don't count on me for other PR... (you know why... see your mail)

### CODE REVIEW

**Comment by bugsounet** [comment]
what's this kind of error with Compliments module ?

**Comment by rejas** [comment]
Maybe your merge code doesnt handle the config style in that module correctly?

**Comment by sdetweil** [comment]
you change the function name to MMmergeConfig

but the code still trying to call old merge config

see the build log ( hate that the build log is one more click away than before )

**Comment by bugsounet** [comment]
It's done Sam, result is the same

**Comment by bugsounet** [comment]
If ... that i think ... I have to put my v1.1.0 ... :'(

I will do some test in local

**Comment by bugsounet** [comment]
no it's good...

anytime: Array(1)
0: "Hey there sexy!"
length: 1
__proto__: Array(0)

test config:
anytime: Array(4)
0: "test!"
1: "test2"
2: "test3"
3: "test4"

I don't merge the Array but it's normal

**Comment by bugsounet** [comment]
@rejas : it's a check test erreur ...
`AssertionError: expected 'You look nice!' to be one of [ 'Anytime here' ]`

it's logical !
i can be one result of: `evening: ["Wow, you look hot!", "You look nice!", "Hi, sexy!"],` OR result of `anytime`

in the script you check ONLY `anytime` result...

I test the check config ... i have `evening` or `anytime` result

**Comment by bugsounet** [comment]
so 2 PR of My PR 16 ... fixed ... but I have just say ONLY one...

**Comment by rejas** [comment]
Ah, now I see what happened here: Your PR merges the user-config (and therefore the test config) deep into the default config where the non-anytime fields are set.
Before your PR those fields where overwritten and therefor empty. Now they are filled with the default values and the tests can randomyl fail.

Unfortunately any user who has not overwritten those fields in his own config will now start to see those default compliments. Is that a behaviour you are willing to have @MichMich and @bugsounet ? IMO any change that that leads to other behaviour after an update is non-acceptable...

**Comment by MichMich** [comment]
Hmm... valid point, let discuss here: https://github.com/MichMich/MagicMirror/issues/2130#issuecomment-696024633_

**Comment by MichMich** [comment]
Closed in favor of: https://github.com/MichMich/MagicMirror/pull/2134

**Pull request closed without merging**
