### PR TITLE
Clean up updatenotifications and nunjuck templating

### PR DESCRIPTION
**Pull request by fewieden**
Does the pull request solve a **related** issue?

No

What does the pull request accomplish? Use a list if needed.
- Switch from manual DOM creation to nunjuck templating
- Fix async/await issues
- Removed exceptions in code and replaced them with jest mocks

If it includes major visual changes please add screenshots.
  - Top is nunjuck template
  - Bottom is current rendering
updatenotifications

### CODE REVIEW

**Comment by fewieden** [comment]
I bumped ESLint to support ECMAScript 2018. It complained about the object literal spread operator which is supported since node v8.3

image

**Comment by MichMich** [comment]
Sorry, am I missing something in the image? I don't see a difference between the top and bottom.

**Comment by fewieden** [comment]
@MichMich that's good, it should look the same.

I just added it as a reference, since I changed the whole rendering of the module.

**Review by rejas — APPROVED** [review]
Nice cleanup!

**Comment by MichMich** [comment]
If you feel like it ... the alert module could use the same TLC. 😅

**Pull request merged**
