### PR TITLE
Update nl.json

### PR DESCRIPTION
**Pull request by rico24**
- Added the missing variables based on the en.json file.

### CODE REVIEW

**Comment by MichMich** [comment]
Could you please add an updated changelog?

**Comment by rico24** [comment]
> Could you please add an updated changelog?

@MichMich What's the best way to do? Creating a new pull request or is there some way to add it to the current pull request? 
I would prefer the last option, but can't seem to find the correct way in the Github GUI, so help is more than welcome ;)

**Comment by MichMich** [comment]
If you change the changelog.me in the branch you did the PR from, the PR will automatically be updated and include the changelog. 👍🏻

**Comment by rico24** [comment]
@MichMich Nice to see the PR is automatically updated with the adjusted CHANGELOG.MD

**Comment by rejas** [comment]
Yeah, now you have to merge the develop branch into your branch and fix the merge conflict (basically edit the CHANGELOG so that all new entries are still in :-)

**Comment by MichMich** [comment]
Merged! Thanks for your contribution!

**Comment by Tv-igtmomsp** [comment]
Great work!! ✅💸

**Pull request merged**
