### PR TITLE
Relative full day events

### LINKED ISSUE #2424: Calendar module enhancement: displaying full day events without time
With relative timeformat, upcoming full day events are displayed like this: 

> Wednesday at 12:00 AM

which doesn't make much sense to me. I've tried to look into the documentation and the code, and it seems like there's no way to configure it at the moment. 

`calendar()` method from moments.js used in the relative time display can't format without time by default, but does allow using custom calendar formatters. They are a rather tricky, because due to different localizations one size won't fit all, but I believe I've nailed it by putting adapted locale-specific calendars into translation files.

Would you consider adding it to the main repository? The details of the change can be found [here](https://github.com/MichMich/MagicMirror/commit/5903adadf9af64b00fe9f21bebec98e58e773476). I've updated translation files for the languages I know, but others require at least minimal understanding of grammar, so I don't think I can't do it myself. Also, for configuring the calendar from translation files, I'm using coreTranslations directly because in this case I don't want the fallback to English version, but rather to default localized calendar from moments.js.

I am also thinking about using `dateFormat` from config to replace the default `"sameElse": "L"`, allowing customization in relative format too, what do you think of it?

### PR DESCRIPTION
**Pull request by AmpioRosso**
Fixes #2424
- Don't display start time of full date events when using relative dates.
- Use the fullDateEventDateFormat when showing full day events more than a week out

### CODE REVIEW

**Comment by josselynL** [comment]
Is this PR will be implemented ? :) Thank you.

**Comment by MichMich** [comment]
The tests are failing. Not sure why though.

**Comment by rejas** [comment]
Maybe after a merge from develop those tests run fine?

**Comment by khassel** [comment]
the tests failed because they run before my latest test-fix, so I think thats unrelated to this PR, but test details are not available anymore. May @MichMich can restart the tests? Otherwise @AmpioRosso could add a fake commit (e.g. with a minimal change in changelog) to start a new pipeline.

**Comment by khassel** [comment]
my first answer in not correct, after I read @rejas answer again the actual `develop` branch must be merged to get the fixed tests ...

**Comment by rejas** [comment]
Merging develop into this PR does help as can be seen in #2737

Maybe @AmpioRosso can do this here or @MichMich merges the other one :-)

**Comment by MichMich** [comment]
Merged https://github.com/MichMich/MagicMirror/pull/2737

**Pull request merged**
