### PR TITLE
electron: add missing fullscreen option

### PR DESCRIPTION
**Pull request by khassel**
follow up for https://github.com/MichMich/MagicMirror/pull/3187

@bugsounet can you please confirm that this now works for you?

### CODE REVIEW

**Comment by bugsounet** [comment]
works but ...

```js
webPreferences: {
        fullscreen: false
      }
```
not work

**Comment by khassel** [comment]
```js
  electronOptions: {
    width: 800,
    height: 600,
    fullscreen: false,
  },
```

works on my side

**Comment by bugsounet** [comment]
tested with your `electronOptions: {}` and don't work for me :/

**Comment by khassel** [comment]
strange, I used this in `config.js`:

```js
/* MagicMirror       Config Sample
 *
 * By Michael Teeuw https://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information on how you can configure this file
 * see https://docs.magicmirror.builders/configuration/introduction.html
 * and https://docs.magicmirror.builders/modules/configuration.html
 */
let config = {

  electronOptions: {
    width: 800,
    height: 600,
    fullscreen: false,
  },

        address: "0.0.0.0",     // Address to listen on, can be:
                                                        // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
                                                        // - another specific IPv4/6 to listen on a specific interface
                                                        // - "0.0.0.0", "::" to listen on any interface
                                                        // Default, when address config is left out or empty, is "localhost"
        port: 8080,
...
```

and it is 800x600 with taskbar, tested on a pi 4.

Did you test on a pi?

**Comment by bugsounet** [comment]
ah shit, it's me ... I have set it in webPreferences of electronOptions :/

So it's works :)

**Comment by bugsounet** [comment]
(we open the bets? e2e will work or not ??)

**Comment by khassel** [comment]
> (we open the bets? e2e will work or not ??)

I hate the e2e tests ...

**Comment by bugsounet** [comment]
it will works `PASS e2e tests/e2e/modules_position_spec.js`

**Review by rejas — APPROVED** [review]

**Pull request merged**
