### PR TITLE
Updated Changelog to reference eslint-plugin-jsdoc dependency bump

### PR DESCRIPTION
**Pull request by Clarkcj12**
Added update for eslint-plugin-jsdoc depency bump

Hello and thank you for wanting to contribute to the MagicMirror project

**Please make sure that you have followed these 4 rules before submitting your Pull Request:**

> 1) Base your pull requests against the `develop` branch.
>
>
> 2) Include these infos in the description:
>  * Does the pull request solve a **related** issue?
>  * If so, can you reference the issue like this `Fixes #<issue_number>`?
>  * What does the pull request accomplish? Use a list if needed.
>  * If it includes major visual changes please add screenshots.
>
>
> 3) Please run `npm run lint:prettier` before submitting so that
> style issues are fixed.
>
>
> 4) Don't forget to add an entry about your changes to
> the CHANGELOG.md file.

**Note**: Sometimes the development moves very fast. It is highly
recommended that you update your branch of `develop` before creating a
pull request to send us your changes. This makes everyone's lives
easier (including yours) and helps us out on the development team.

Thanks again and have a nice day!

### CODE REVIEW

**Comment by MichMich** [comment]
Which PR does this refer to?

**Comment by Clarkcj12** [comment]
@MichMich Pull Request #2594 .

**Comment by rejas** [comment]
hi @Clarkcj12 please try to provide all changes in one PR so that they are easier to review.

**Comment by MichMich** [comment]
Please add the changelog to that PR: https://github.com/MichMich/MagicMirror/pull/2594

Thanks!

**Pull request closed without merging**
