### PR TITLE
Add new log level "debug"

### PR DESCRIPTION
**Pull request by rejas**
Added a new log level for usage during development.

Can be used in https://github.com/MichMich/MagicMirror/pull/2178/files# so that no debug flags need to be when logging during development.

### CODE REVIEW

**Comment by khassel** [comment]
With the change of 

````
logLevel: ["DEBUG", "INFO", "LOG", "WARN", "ERROR"],
````

in the `config.sample.js` now everybody using this sample as starting config has `DEBUG` enabled. This is also the default, if logLevel is not set. 

@rejas  Was this intended?

**Comment by rejas** [comment]
@khassel not really... PR incoming :-)

**Comment by rejas** [comment]
the question would be @MichMich @sdetweil @khassel what log level would be sufficient for the sample? Dont want to spam too much noise but dont want to miss too much. info? log? warn?

**Comment by khassel** [comment]
for me the "old" config with `logLevel: ["INFO", "LOG", "WARN", "ERROR"],` would be o.k.

**Comment by sdetweil** [comment]
correct  don't need debug in the sample as default setting

**Pull request merged**
