### PR TITLE
Updated Dark Sky Module

### PR DESCRIPTION
**Pull request by nhubbard**
> Please send your pull requests the develop branch.
> Don't forget to add the change to CHANGELOG.md.

**Note**: Sometimes the development moves very fast. It is highly
recommended that you update your branch of `develop` before creating a
pull request to send us your changes. This makes everyone's lives
easier (including yours) and helps us out on the development team.
Thanks!

* Does the pull request solve a **related** issue? Discussed on Slack.
* If so, can you reference the issue?
* What does the pull request accomplish? Use a list if needed.
    * Update the Dark Sky module to match the latest bleeding-edge API changes.
* If it includes major visual changes please add screenshots.

### CODE REVIEW

**Comment by MichMich** [comment]
It still contains changes to something outside of the new weather module ... ;)

**Comment by nhubbard** [comment]
Shoot.

**Comment by nhubbard** [comment]
@MichMich Okay, I give up. I just (un?)fixed the indentation.

**Comment by MichMich** [comment]
Thanks. You can ignore all the errors for now, we well clean it up before the merge with develop.

**Pull request merged**
