### PR TITLE
Added config option to calendar-icons for recurring- and fullday-events

### PR DESCRIPTION
**Pull request by rejas**
Inspired by #2023 I whipped up something so that fullday events and recurring events can have different symbols set.

### CODE REVIEW

**Comment by rejas** [comment]
Converting to draft to first get some feedback on how the config is changed and if that is ok.

**Comment by MichMich** [comment]
Looks good to me, do you want me to merge?

**Comment by rejas** [comment]
I'd like to add a test for it before merging it. Give me this weekend @MichMich  :-)

**Comment by rejas** [comment]
Tests fail becuase now I added a new test for checking if setting maximumEntries per calendar works. Will fix the code in this PR too or should I open a new ticket and pr @MichMich ?

**Comment by MichMich** [comment]
You can do it in this PR.

**Comment by rejas** [comment]
Ready for merging :-)

**Pull request merged**
