### PR TITLE
Add UTC timestamp to console log

### PR DESCRIPTION
**Pull request by qistoph**
This PR adds a timestamp to the logging/stdout. This is helpful for troubleshooting. It works for output on the console (like with `node serveronly`) and for the log file `.pms/logs/mm-out.log` when using pm2.

The timestamp is in UTC, which is how the module I've found for this, uses. If that's an issue and you'd prefer local time, please let me know and I'll see what I can do.

### CODE REVIEW

**Comment by qistoph** [comment]
Hmmm, the Travis CI build keeps failing. I don't understand why and can't reproduce locally... Any suggestions?

Local output:
```
$ node --version
v8.16.1
$ npm --version
6.4.1
$ nvm --version
0.34.0
$ npm ci
npm WARN prepare removing existing node_modules/ before installation
[... snip ...]
MagicMirror installation successful!

> magicmirror@2.9.0-develop install-fonts /home/lu/MagicMirror
> cd fonts && npm install

audited 1 package in 0.541s
found 0 vulnerabilities

added 1020 packages in 10.998s
```

Travis CI:
```
$ node --version
v8.16.1
$ npm --version
6.4.1
$ nvm --version
0.34.0
$ npm ci 
npm WARN prepare removing existing node_modules/ before installation
npm ERR! merge not accessible from console-stamp

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-09-06T06_13_46_276Z-debug.log
[... snip ...]
```

**Comment by MichMich** [comment]
@roramirez Do you have time to check this travis issue?

**Comment by roramirez** [comment]
@qistoph Please, sync your branch with last version `develop`

**Comment by MichMich** [comment]
Please submit a new PR. Thanks!

**Pull request closed without merging**
