### PR TITLE
Added getTranslations() to the documentation

### PR DESCRIPTION
**Pull request by paviro**

### CODE REVIEW

**Comment by MichMich** [comment]
Thanks. Maybe we should note in the documentation that it isn't fully finished yet (no fallback in case a translation isn't present yet.)

**Comment by paviro** [comment]
Maybe but isn't it normal to add all used translations to every file anyway even if they are not translated yet? At least I would work that way, so people know what still needs to be translated.

**Comment by MichMich** [comment]
What if I add a translation in dutch to your repo (via a PR), and you add a feature that needs a translation. Then you don't have a dutch translation available yet. You want a nice fallback for that without going thru all the available translation files.

**Comment by paviro** [comment]
Yes that's right. I would add it to all translation files in the fallback language but maybe thats just me 😀

**Comment by MichMich** [comment]
It's a good approach, but the system should have a decent fallback mechanism as well. In addition to the fallback mechanism, I really want to have a global translation system implemented. Since a lot of words used in the modules are used more than once ("Tomorrow", "Today", "Loading ...", etc ...) - But this is not something we currently have to put into the Readme.

**Comment by paviro** [comment]
Yes the global system should definitely be there! I will add a note to the documentation about the other thing.

**Comment by MichMich** [comment]
Just add a reference to the issue (#191) as well, so people can read up on the current state.

**Comment by MichMich** [comment]
A bit too late, but `this.translate` should be mentioned under Module instance methods. (Since it is ...)

**Pull request merged**
