### PR TITLE
fix ISSUE_TEMPLATE

### PR DESCRIPTION
**Pull request by khassel**
fix for #3167

### CODE REVIEW

**Review by rejas — APPROVED** [review]

**Comment by khassel** [comment]
strange these 2 old tests which are required to get the merge button visible ... 

any ideas?

could try to push this commit directly on `master`

**Comment by rejas** [comment]
> strange these 2 old tests which are required to get the merge button visible ...

very strange, especially that 14.x one... 

> any ideas?
> 
> could try to push this commit directly on `master`

I would be okay with that, if github / git allows it :-)

**Comment by rejas** [comment]
oh wait, wouldnt then the update notification be triggered for all users?

**Comment by khassel** [comment]
> oh wait, wouldnt then the update notification be triggered for all users?

no, I wrote this already in the issue.

as expected:
```bash
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: 2 of 2 required status checks are expected.
To github.com:MichMich/MagicMirror.git
 ! [remote rejected]   master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:MichMich/MagicMirror.git'
```

So I think this can only be merged by @MichMich . If the "Squash and merge" button is disabled for him too he can disabled the check rule, do the merge and then enable this again.

**Comment by rejas** [comment]
After a good nights sleep I'd be fine with merging it to develop. We can live another two month with this issue after having it  for so long :-)

**Comment by khassel** [comment]
@rejas moved to `develop` and now ready to merge

I will play with a `master` merge later to may find the cause of the node v14/v16 tests, couldn't reproduce this on my fork ...

**Review by rejas — APPROVED** [review]

**Pull request merged**
