### PR TITLE
Added Russian Translations

### PR DESCRIPTION
**Pull request by morozgrafix**
**Added:**
- Russian Translations

**Fixed:**
- corrected .gitignore rules for default modules (Reasoning behind change: when I added translation for `alert` module `git add` was telling me that `.gitignore` rule excludes files and folders under `modules/default`)

I also noticed that `.gitignore:56` has following declaration:

```
# Don't ignore the node_helper nore module.
!/modules/node_helper
!/modules/node_helper/**
``` 
but I don't think this directory structure exists today (also there is a small typo)

### CODE REVIEW

**Comment by nhubbard** [comment]
@morozgrafix Looks good, but there is a pull request that was merged from @MichMich in there that already occurred in the master branch. I recommend that you close this pull request and re-add it after updating your branch. Otherwise, looks good!

**Comment by morozgrafix** [comment]
Thanks I will do that.

**Comment by morozgrafix** [comment]
@nhubbard Sorry I'm a bit confused. I think my branch was updated with latest master yesterday and commit log shows similar pattern as #596 that was approved. I think my fork is in sync with master at this point.

**Comment by morozgrafix** [comment]
Are you talking about this one? https://github.com/MichMich/MagicMirror/commit/41ca7e6d308b939747502e7360ac731534d22306

**Comment by roramirez** [comment]
@morozgrafix Could be the extra merges included in this Pull Request.

An Pull Request with two commit are more beautiful :). 

Close the Pull Request is not neccesarry. You can override your branch and pushed with --force

**Comment by morozgrafix** [comment]
@roramirez thanks, I'm in process of making a new PR at the moment. Ended up in a weird mess :) and started over. I need more coffee this morning.

**Comment by morozgrafix** [comment]
Closing, proposed changes are in #601

**Pull request closed without merging**
