### PR TITLE
Make logger a little more configurable

### PR DESCRIPTION
**Pull request by rejas**
I dont want to have all infos logged on the console once I deploy my MagicMirror. Therefor I added a config entry "logLevel" where one can specify an array of loglevels you wants to see. 

Any comments on the idea so far before I implement more?

### CODE REVIEW

**Comment by MichMich** [comment]
Maybe it's an idea to follow the log levels defined in the RFC 5424 specification: `emergency`, `alert`, `critical`, `error`, `warning`, `notice`, `info`, and `debug`.

**Comment by rejas** [comment]
Will take a look at those...

**Comment by rejas** [comment]
Mhhh... not sure if we can those log levels from the RFC are all needed here:

              0       Emergency: system is unusable
              1       Alert: action must be taken immediately
              2       Critical: critical conditions
              3       Error: error conditions
              4       Warning: warning conditions
              5       Notice: normal but significant condition
              6       Informational: informational messages
              7       Debug: debug-level messages

Could be a little overengineered if we use all of them. Plus we would have to deprecate those that are not in there (like console.log)...

**Comment by rejas** [comment]
So in my mind its ready for review. As I wrote, adding the RFC log levels seems to be a little too complex for this scenario. Plus one would have to add some warnings for deprecated methods and such. 
Any more comments @MichMich ?

**Comment by MichMich** [comment]
Hm, I agree. In that case, let's use the defaults for `console`:

- `log`
- `info`
- `warn`
- `error`

**Comment by sdetweil** [comment]
just saw this pr, how does this compare to the MMM-Logging module?  which merges all reporting into a single log,  server and client side?

**Pull request merged**
