### PR TITLE
clockBold + Remove Custom CSS

### PR DESCRIPTION
**Pull request by nhubbard**
Don't worry, I have a reason. Git would not ignore my changes, so I removed it. **It will be re-added in a second pull request.**

### CODE REVIEW

**Comment by MichMich** [comment]
Could you explain the use of this pull request? It makes the minutes bold? Why would that be preferred?
Also, because the custom.css is re-added, it might overwrite the custom.css file people modified.

**Comment by nhubbard** [comment]
It looks a lot cooler, and it, in a controlled test that I did, was preferred by 29 of 30 people surveyed. (The last person was uncooperative.)

**Comment by CFenner** [comment]
Why don't you add this as an option? Other users might like it the way it is.

**Comment by MichMich** [comment]
Isn't it easier to just make a custom change in your custom.css? I agree with @CFenner. Most users will just want the current style.

**Comment by djsunrise19** [comment]
As an option would be great, I think.

**Comment by nhubbard** [comment]
Okay... I'll attempt this. Thanks for the feedback, guys!

**Pull request closed without merging**
