### PR TITLE
add Collaboration.md

### PR DESCRIPTION
**Pull request by khassel**
As already discussed here the first shot of the collaboration rules.

We can discuss this in the comments until ready to merge.

### CODE REVIEW

**Review by rejas — APPROVED** [review]
looks good!

**Review by KristjanESPERANTO — APPROVED** [review]
Even though I'm not an official reviewer, it looks good to me too :slightly_smiling_face:

**Comment by rejas** [comment]
Good morning @sdetweil are you fine with these ?

**Review by sdetweil — APPROVED** [review]
yes, looks good

**Comment by rejas** [comment]
by the way, might it make sense to add @MichMich to the discurs channel too?

**Pull request merged**
