### PR TITLE
deprecate module currentweather and weatherforecast

### PR DESCRIPTION
**Pull request by buxxi**
- Adding logging when using deprecated weather-modules (had to add a NodeHelper for each)
- Updating sample config file to use the new weather module
- Added comment in code about not accepting new features
- Added warning in the old weather modules readme

### CODE REVIEW

**Comment by MichMich** [comment]
Thanks. I like this. Might give some issues with your other weather PR. Which one would you like me to merge first?

**Comment by buxxi** [comment]
The other one, this one is easier to redo :)

**Comment by MichMich** [comment]
Merged the other one. Is the weatherEndpoint still necessary in the config?

**Comment by buxxi** [comment]
Yes, both before and after the other pull request.
Using forecast/daily will just get stuck on "Loading..." without specifying it, that's why I defined it like that in the sample config.

Could possibly make it so it makes sane guesses for weatherEndpoint based on type when it's not specified?

**Comment by MichMich** [comment]
I think indeed it's a good idea to use a default one that works no matter what type of account you have. The simpler the necessary config, the better.

**Review by rejas — APPROVED** [review]

**Comment by buxxi** [comment]
Removed the default value for weatherEndpoint and if it's not set have sane defaults.

**Comment by MichMich** [comment]
Thanks for your great contribution!

**Pull request merged**
