### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by roramirez**
Revert commit introduced in #1827. The change introduce a failure for all e2e tests. 

This change revert the commit 2fbedca746655f38fa89a6436afa888f88d518db

--
Happy new year ("20".repeat(2))

### CODE REVIEW

**Comment by sdetweil** [comment]
NO.. we need the helper fix.. need to fix CI some other way..

**Comment by sdetweil** [comment]
the vendor tests still fail.

**Comment by MichMich** [comment]
@sdetweil I Will test this PR tonight. If this fixes the issue I’ll merge it since we need Travis to complete successfully in order to release 2.10 today (according to release schedule).

**Comment by sdetweil** [comment]
How do we fix the  testing cache to have the helper in the main node_modules instead the modules/node_modules?

**Comment by MichMich** [comment]
Will try tonight. Don’t want to have the helper in an external repo anyway. Might need to push that change onto the next release.

**Comment by sdetweil** [comment]
I think the helper being erased is a big problem. I think it is a security fix that is erasing. If modules not listed but installed, they are removed

**Comment by MichMich** [comment]
Will look into it. Hope I can fix it before release. 

Vriendelijke groeten,
Michael Teeuw

---
Sent from my iPhone.

Michael Teeuw
Xonay Media
www.xonaymedia.nl
06 51 71 36 15

**Comment by sdetweil** [comment]
Another user reported that install failed to install the helper file. Which
means it was cloned and then erased on npm install

https://forum.magicmirror.builders/topic/11883/black-screen-on-startup

**Comment by MichMich** [comment]
Reading that, I’m not confident it was caused by an NPM install. At at least not an non install ran in the correct folder. But non the less I will try to look for a solution. First priority is to get Travis to work again.

**Comment by sdetweil** [comment]
Ok. I am for stable system. Test system later. The vendor stuff has been
failing for quite a while now.
Only the weather tests are affected so far by the node_helper.

**Comment by sdetweil** [comment]
We have a whole quarter to solve the Travis  problems

**Comment by MichMich** [comment]
I can't release without Travis. Releases are blocked. And for a good reason. Wel work on a solution now.

**Comment by MichMich** [comment]
@sdetweil the node helper is no longer part op de node_modules folder. Now looking for the weather tests fails.

**Comment by roramirez** [comment]
> I think the helper being erased is a big problem. I think it is a security fix that is erasing. If modules not listed but installed, they are removed


I can understand why will be the better if we has a node helper in external repository and what kind of issue could fix include in this way. We should keep this code in main code of project, its to more easy maintent this code in this repo.

**Comment by sdetweil** [comment]
I asked multiple times for Mich to create the repo on his GitHub, but got no action. So I created it on mine. 

Mich is welcome to move it to his.
I  trying to stop user acceptance problems

**Comment by MichMich** [comment]
This is already fixed. The node helper is already outside the modules folder (in /js to be exactly). It is aliased so you can just use the same require statement. (Non breaking). 

I want to keep everything in one repo to keep it simple. This accomplishes that.

**Comment by sdetweil** [comment]
As for the Travis problem there are electron version dependencies on some of the libraries used by the test cases. Spectron, for example.
I updated that one to match the electron version.
Don't know if there are other lib problems too.

Tests run locally after install work great.
So how do we get those libs updated in Travis environment?  

There is no change mgmt guidance for the Travis tests

**Comment by sdetweil** [comment]
Helper in js. good! I didn't see that as a possibility.

**Comment by roramirez** [comment]
> As for the Travis problem there are electron version dependencies on some of the libraries used by the test cases. Spectron, for example.
> I updated that one to match the electron version.
> Don't know if there are other lib problems too.
> 
> Tests run locally after install work great.(weather works, vendor still fails, but still reports ok)
> So how do we get those libs updated in Travis environment?
> 
> There is no change mgmt guidance for the Travis tests

What O.S, npm and node versions are you using? 

Could you paste here the package.json in your local environment?

Also, `npm list`

**Comment by sdetweil** [comment]
Will do. Node 10.1x.0, npm 6.1x.0
Tried on raspian, Ubuntu, 

All tests fail on macOs Catalina. 10.15.2

I am away for most of the rest of the day
I posted a new package-lock with this pr. which solved the problem originally (Travis went from failing to passing)

I did a clone, checkout for develop, npm install, then ran two testcase sets

**Comment by sdetweil** [comment]
looks like the screen setup for travis has changed

https://electronjs.org/docs/tutorial/testing-on-headless-ci

when I do export DISPLAY=:0
and then run the npm run test:e2e (locally) it works 
but not the vendor tests..

the vendor tests are because the port didn't get set when using the js/electron.js  launch
I added debug to the vendor_spec.js and here is the output of the before, launching js/electron.js
the port is not set 

  Vendors
starting js/electron
electron path=/home/sam/MagicMirror/node_modules/.bin/electron
new electron app =[object Object]
parms={"host":"127.0.0.1","**port":9515**,"quitTimeout":1000,"startTimeout":5000,"waitTimeout":5000,"connectionRetryCount":10,"connectionRetryTimeout":30000,"nodePath":"/usr/bin/node","path":"/home/sam/MagicMirror/node_modules/.bin/electron","args":["/home/sam/MagicMirror/tests/e2e/../../js/electron.js"],"chromeDriverArgs":[],"env":{},"workingDirectory":"/home/sam/MagicMirror","webdriverOptions":{},"requireName":"require"}

if I change the get urls to the 9515 port, the it works.. 

this didn't work  (tests/e2e/from vendor_spec.js)
	describe("Get list vendors", function () {

		before(function () {
			process.env.MM_CONFIG_FILE = "tests/configs/env.js";  // < ----
		});

that before() is never called. 
and if u move the process.env. to before the app.start() it doesn't work there either..

**Comment by sdetweil** [comment]
the untouched e2e test also works on macOS catalina after doing export DISPLAY=:0
i had to change the address for the vedor tests to port 9515, but it worked then

**Pull request merged**
