### PR TITLE
Updated weathericons to latest version and fixed weatherforecast.js w…

### PR DESCRIPTION
**Pull request by RedNax67**
This PR adresses the following:

Updated to weathericons to the (at the time of writing) latest version.
Updated default weatherforecast module to work with the new icons (shouldn't really have worked with the old ones, but did for some reason).

There should be noticable differences although i haven't checked every single icon against the older version.

Primary reason for this is so the MMM-WunderGround module can shed it's copy of the new weathericon files and to make them available systemwide.

### CODE REVIEW

**Comment by MichMich** [comment]
**Please answer these questions when sending a PR:**
Does the pull request solve a related issue? [yes | no]
If so, can you reference the issue?
What does the pull request accomplish? (please list)
If it includes major visual changes please add screenshots.

Also, don't forget to add the modified CHANGELOG.MD.

Thanks!

**Comment by MichMich** [comment]
Thanks for adding the changelog. Before I can accept the PR, I need the questions above to be answered, since I currently don't see the added value of this change. Especially since you note "Currentweather didn't have an issue oddly". Thanks!

**Comment by RedNax67** [comment]
Well, It was a bit odd that the currentweather module didn't have an issue using the exact same icon the weatherforecast module wasn't displaying using the updated iconfiles.

Another reason for the PR is your post in this thread: https://forum.magicmirror.builders/topic/306/the-mirror-that-wasn-t-a-mirror/6

**Comment by MichMich** [comment]
Thanks!

**Pull request merged**
