### PR TITLE
Add news feed broadcast or update for default newsfeed module 

### PR DESCRIPTION
**Pull request by cybex-dev**
* Does the pull request solve a **related** issue?
Nope.

* What does the pull request accomplish? Use a list if needed.
Using the default `newsfeed` module, it can now broadcast news feed items to other modules, alternatively broadcast only news feed updates.

A minor feature, yet it is something useful.

### CODE REVIEW

**Comment by nischi** [comment]
Please merge that in, i need that also for my module [MMM-News-QR](https://github.com/nischi/MMM-News-QR). Then i do not need to poll all the time. That would be awesome.

**Comment by MichMich** [comment]
Merged.

**Comment by nischi** [comment]
Any plans by when you release that?

**Comment by MichMich** [comment]
1-7-2019. I release a new master every first of a quarter.

**Comment by nischi** [comment]
Nice to know :)

**Comment by thobach** [comment]
@cybex-dev Receiving a notification 1) every second and 2) whenever a news item changes, seem both a bit overkill to me as it pollutes also the log output. Should this rather be configurable, or do you have other suggestions how to avoid log outputs being so much pulled? Thanks!

**Comment by cybex-dev** [comment]
@thobach That is a good suggestion, I will make some changes to it allowing for more configurable notifications, thanks :)

**Pull request merged**
