### PR TITLE
Fix grunt errors in root_path.js and syntax in da.json

### PR DESCRIPTION
**Pull request by qistoph**
root_path.js failed grunt testing, but passed Travis-CI somehow... (https://travis-ci.org/qistoph/MagicMirror/jobs/194886345)

translations/da.json missed a comma

### CODE REVIEW

**Comment by MichMich** [comment]
Thanks! Didn't notice it didn't pass the tests.

**Comment by morozgrafix** [comment]
That's odd that grunt exited with code 0 after finding errors. ¯\_(ツ)_/¯

**Comment by roramirez** [comment]
Yesterday I've see that.  https://travis-ci.org/MichMich/MagicMirror/jobs/194887311. I thinked is Travis say ok is ok.

Is  so stranger.  Anybody have an idea what can be?

**Comment by morozgrafix** [comment]
when i run grunt locally and it detects those type of errors, grunt exits with exit code 3 which should theoretically result in failing the task and failing the Travis build.
maybe it's worth trying to run `grunt --verbose` to see if there is anything odd at the runtime.

**Comment by qistoph** [comment]
Actually, I've already tested it and it exited with an error (code: 3) as expected. 

https://travis-ci.org/qistoph/MagicMirror/builds/195136182

**Comment by roramirez** [comment]
Nice, maybe was a hiccup of Travis.

**Pull request merged**
