### PR TITLE
Customize classes for table.

### PR DESCRIPTION
**Pull request by Ybbet**
MagicMirror offers helper classes in the main.css. Therefore, we give
the possibility to indicate the class that we want.

### CODE REVIEW

**Comment by Ybbet** [comment]
Hi.
The changelog is adde to the PR

**Comment by MichMich** [comment]
The indents (mainly of the comments) seem to be a bit malformed.

**Comment by Ybbet** [comment]
I used the eslint format in the project. The last commit will resolved the indentation.
Sorry for all those errors. It's my first time with your project :-D
All checks have passed.

**Comment by MichMich** [comment]
Sorry, the indents are still messed up. It passes the linter, but it doesn't look very readable.

**Comment by Ybbet** [comment]
What is the size of the tab you use? It will be easier like that.

**Comment by Ybbet** [comment]
And now, with a diff between the original files and mine, the tabulation are back in life.

**Comment by MichMich** [comment]
Awesome. Thanks!

**Comment by Ybbet** [comment]
You're welcome.

**Pull request merged**
