### PR TITLE
Update Compliments Module - Add Advice API

### PR DESCRIPTION
**Pull request by ndom91**
Add Advice API (https://api.adviceslip.com/) Option instead of hard coded compliments.

### CODE REVIEW

**Comment by MichMich** [comment]
Thanks! Could you send a PR to the documentation repo to describe the option?

**Comment by ndom91** [comment]
Yeah no problem, give me a few.

**Comment by hangorazvan** [comment]
Not working! Did you make tests? If yes, how?

console log
`Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'currentweather' in Some of life's best lessons are learnt at the worst times.`

**Comment by sdetweil** [comment]
tests are done with the travis system on each push. 
where is that error?

**Comment by hangorazvan** [comment]
this error is in console for compliments.js at

```
if (this.currentWeatherType in this.config.compliments) {
	compliments.push.apply(compliments, this.config.compliments[this.currentWeatherType]);
}
```
and compliments are dead, no change

**Pull request merged**
